/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChartCandles type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChartCandles{}

// ChartCandles struct for ChartCandles
type ChartCandles struct {
	// status
	S string `json:"s"`
	// array of candle timestamps
	T []int32 `json:"t"`
	// array of candle open-price
	O []float32 `json:"o"`
	// array of candle high-price
	H []float32 `json:"h"`
	// array of candle low-price
	L []float32 `json:"l"`
	// array of candle close-price
	C []float32 `json:"c"`
	// array of volumes (value in native units)
	V []float32 `json:"v"`
	// text of error message
	ErrMsg *string `json:"err_msg,omitempty"`
}

type _ChartCandles ChartCandles

// NewChartCandles instantiates a new ChartCandles object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChartCandles(s string, t []int32, o []float32, h []float32, l []float32, c []float32, v []float32) *ChartCandles {
	this := ChartCandles{}
	this.S = s
	this.T = t
	this.O = o
	this.H = h
	this.L = l
	this.C = c
	this.V = v
	return &this
}

// NewChartCandlesWithDefaults instantiates a new ChartCandles object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChartCandlesWithDefaults() *ChartCandles {
	this := ChartCandles{}
	return &this
}

// GetS returns the S field value
func (o *ChartCandles) GetS() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.S
}

// GetSOk returns a tuple with the S field value
// and a boolean to check if the value has been set.
func (o *ChartCandles) GetSOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.S, true
}

// SetS sets field value
func (o *ChartCandles) SetS(v string) {
	o.S = v
}

// GetT returns the T field value
func (o *ChartCandles) GetT() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.T
}

// GetTOk returns a tuple with the T field value
// and a boolean to check if the value has been set.
func (o *ChartCandles) GetTOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.T, true
}

// SetT sets field value
func (o *ChartCandles) SetT(v []int32) {
	o.T = v
}

// GetO returns the O field value
func (o *ChartCandles) GetO() []float32 {
	if o == nil {
		var ret []float32
		return ret
	}

	return o.O
}

// GetOOk returns a tuple with the O field value
// and a boolean to check if the value has been set.
func (o *ChartCandles) GetOOk() ([]float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.O, true
}

// SetO sets field value
func (o *ChartCandles) SetO(v []float32) {
	o.O = v
}

// GetH returns the H field value
func (o *ChartCandles) GetH() []float32 {
	if o == nil {
		var ret []float32
		return ret
	}

	return o.H
}

// GetHOk returns a tuple with the H field value
// and a boolean to check if the value has been set.
func (o *ChartCandles) GetHOk() ([]float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.H, true
}

// SetH sets field value
func (o *ChartCandles) SetH(v []float32) {
	o.H = v
}

// GetL returns the L field value
func (o *ChartCandles) GetL() []float32 {
	if o == nil {
		var ret []float32
		return ret
	}

	return o.L
}

// GetLOk returns a tuple with the L field value
// and a boolean to check if the value has been set.
func (o *ChartCandles) GetLOk() ([]float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.L, true
}

// SetL sets field value
func (o *ChartCandles) SetL(v []float32) {
	o.L = v
}

// GetC returns the C field value
func (o *ChartCandles) GetC() []float32 {
	if o == nil {
		var ret []float32
		return ret
	}

	return o.C
}

// GetCOk returns a tuple with the C field value
// and a boolean to check if the value has been set.
func (o *ChartCandles) GetCOk() ([]float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.C, true
}

// SetC sets field value
func (o *ChartCandles) SetC(v []float32) {
	o.C = v
}

// GetV returns the V field value
func (o *ChartCandles) GetV() []float32 {
	if o == nil {
		var ret []float32
		return ret
	}

	return o.V
}

// GetVOk returns a tuple with the V field value
// and a boolean to check if the value has been set.
func (o *ChartCandles) GetVOk() ([]float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.V, true
}

// SetV sets field value
func (o *ChartCandles) SetV(v []float32) {
	o.V = v
}

// GetErrMsg returns the ErrMsg field value if set, zero value otherwise.
func (o *ChartCandles) GetErrMsg() string {
	if o == nil || IsNil(o.ErrMsg) {
		var ret string
		return ret
	}
	return *o.ErrMsg
}

// GetErrMsgOk returns a tuple with the ErrMsg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartCandles) GetErrMsgOk() (*string, bool) {
	if o == nil || IsNil(o.ErrMsg) {
		return nil, false
	}
	return o.ErrMsg, true
}

// HasErrMsg returns a boolean if a field has been set.
func (o *ChartCandles) HasErrMsg() bool {
	if o != nil && !IsNil(o.ErrMsg) {
		return true
	}

	return false
}

// SetErrMsg gets a reference to the given string and assigns it to the ErrMsg field.
func (o *ChartCandles) SetErrMsg(v string) {
	o.ErrMsg = &v
}

func (o ChartCandles) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChartCandles) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["s"] = o.S
	toSerialize["t"] = o.T
	toSerialize["o"] = o.O
	toSerialize["h"] = o.H
	toSerialize["l"] = o.L
	toSerialize["c"] = o.C
	toSerialize["v"] = o.V
	if !IsNil(o.ErrMsg) {
		toSerialize["err_msg"] = o.ErrMsg
	}
	return toSerialize, nil
}

func (o *ChartCandles) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"s",
		"t",
		"o",
		"h",
		"l",
		"c",
		"v",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChartCandles := _ChartCandles{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChartCandles)

	if err != nil {
		return err
	}

	*o = ChartCandles(varChartCandles)

	return err
}

type NullableChartCandles struct {
	value *ChartCandles
	isSet bool
}

func (v NullableChartCandles) Get() *ChartCandles {
	return v.value
}

func (v *NullableChartCandles) Set(val *ChartCandles) {
	v.value = val
	v.isSet = true
}

func (v NullableChartCandles) IsSet() bool {
	return v.isSet
}

func (v *NullableChartCandles) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChartCandles(val *ChartCandles) *NullableChartCandles {
	return &NullableChartCandles{value: val, isSet: true}
}

func (v NullableChartCandles) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChartCandles) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


