/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PairInfoRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PairInfoRequest{}

// PairInfoRequest struct for PairInfoRequest
type PairInfoRequest struct {
	Address string `json:"address"`
	Network NetworkType `json:"network"`
}

type _PairInfoRequest PairInfoRequest

// NewPairInfoRequest instantiates a new PairInfoRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPairInfoRequest(address string, network NetworkType) *PairInfoRequest {
	this := PairInfoRequest{}
	this.Address = address
	this.Network = network
	return &this
}

// NewPairInfoRequestWithDefaults instantiates a new PairInfoRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPairInfoRequestWithDefaults() *PairInfoRequest {
	this := PairInfoRequest{}
	return &this
}

// GetAddress returns the Address field value
func (o *PairInfoRequest) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *PairInfoRequest) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *PairInfoRequest) SetAddress(v string) {
	o.Address = v
}

// GetNetwork returns the Network field value
func (o *PairInfoRequest) GetNetwork() NetworkType {
	if o == nil {
		var ret NetworkType
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *PairInfoRequest) GetNetworkOk() (*NetworkType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *PairInfoRequest) SetNetwork(v NetworkType) {
	o.Network = v
}

func (o PairInfoRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PairInfoRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["network"] = o.Network
	return toSerialize, nil
}

func (o *PairInfoRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"network",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPairInfoRequest := _PairInfoRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPairInfoRequest)

	if err != nil {
		return err
	}

	*o = PairInfoRequest(varPairInfoRequest)

	return err
}

type NullablePairInfoRequest struct {
	value *PairInfoRequest
	isSet bool
}

func (v NullablePairInfoRequest) Get() *PairInfoRequest {
	return v.value
}

func (v *NullablePairInfoRequest) Set(val *PairInfoRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePairInfoRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePairInfoRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePairInfoRequest(val *PairInfoRequest) *NullablePairInfoRequest {
	return &NullablePairInfoRequest{value: val, isSet: true}
}

func (v NullablePairInfoRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePairInfoRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


