/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NftAssetInfoListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NftAssetInfoListRequest{}

// NftAssetInfoListRequest struct for NftAssetInfoListRequest
type NftAssetInfoListRequest struct {
	CollectionAddress string `json:"collection_address"`
	Network NetworkType `json:"network"`
	Cursor *string `json:"cursor,omitempty"`
	Count int32 `json:"count"`
}

type _NftAssetInfoListRequest NftAssetInfoListRequest

// NewNftAssetInfoListRequest instantiates a new NftAssetInfoListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNftAssetInfoListRequest(collectionAddress string, network NetworkType, count int32) *NftAssetInfoListRequest {
	this := NftAssetInfoListRequest{}
	this.CollectionAddress = collectionAddress
	this.Network = network
	this.Count = count
	return &this
}

// NewNftAssetInfoListRequestWithDefaults instantiates a new NftAssetInfoListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNftAssetInfoListRequestWithDefaults() *NftAssetInfoListRequest {
	this := NftAssetInfoListRequest{}
	var count int32 = 10
	this.Count = count
	return &this
}

// GetCollectionAddress returns the CollectionAddress field value
func (o *NftAssetInfoListRequest) GetCollectionAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CollectionAddress
}

// GetCollectionAddressOk returns a tuple with the CollectionAddress field value
// and a boolean to check if the value has been set.
func (o *NftAssetInfoListRequest) GetCollectionAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CollectionAddress, true
}

// SetCollectionAddress sets field value
func (o *NftAssetInfoListRequest) SetCollectionAddress(v string) {
	o.CollectionAddress = v
}

// GetNetwork returns the Network field value
func (o *NftAssetInfoListRequest) GetNetwork() NetworkType {
	if o == nil {
		var ret NetworkType
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *NftAssetInfoListRequest) GetNetworkOk() (*NetworkType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *NftAssetInfoListRequest) SetNetwork(v NetworkType) {
	o.Network = v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *NftAssetInfoListRequest) GetCursor() string {
	if o == nil || IsNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftAssetInfoListRequest) GetCursorOk() (*string, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *NftAssetInfoListRequest) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *NftAssetInfoListRequest) SetCursor(v string) {
	o.Cursor = &v
}

// GetCount returns the Count field value
func (o *NftAssetInfoListRequest) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *NftAssetInfoListRequest) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *NftAssetInfoListRequest) SetCount(v int32) {
	o.Count = v
}

func (o NftAssetInfoListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NftAssetInfoListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["collection_address"] = o.CollectionAddress
	toSerialize["network"] = o.Network
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	toSerialize["count"] = o.Count
	return toSerialize, nil
}

func (o *NftAssetInfoListRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"collection_address",
		"network",
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNftAssetInfoListRequest := _NftAssetInfoListRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNftAssetInfoListRequest)

	if err != nil {
		return err
	}

	*o = NftAssetInfoListRequest(varNftAssetInfoListRequest)

	return err
}

type NullableNftAssetInfoListRequest struct {
	value *NftAssetInfoListRequest
	isSet bool
}

func (v NullableNftAssetInfoListRequest) Get() *NftAssetInfoListRequest {
	return v.value
}

func (v *NullableNftAssetInfoListRequest) Set(val *NftAssetInfoListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNftAssetInfoListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNftAssetInfoListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNftAssetInfoListRequest(val *NftAssetInfoListRequest) *NullableNftAssetInfoListRequest {
	return &NullableNftAssetInfoListRequest{value: val, isSet: true}
}

func (v NullableNftAssetInfoListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNftAssetInfoListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


