/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TonTxData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TonTxData{}

// TonTxData struct for TonTxData
type TonTxData struct {
	SeqNo int32 `json:"seq_no"`
	ShardId int32 `json:"shard_id"`
	WorkChain int32 `json:"work_chain"`
}

type _TonTxData TonTxData

// NewTonTxData instantiates a new TonTxData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTonTxData(seqNo int32, shardId int32, workChain int32) *TonTxData {
	this := TonTxData{}
	this.SeqNo = seqNo
	this.ShardId = shardId
	this.WorkChain = workChain
	return &this
}

// NewTonTxDataWithDefaults instantiates a new TonTxData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTonTxDataWithDefaults() *TonTxData {
	this := TonTxData{}
	return &this
}

// GetSeqNo returns the SeqNo field value
func (o *TonTxData) GetSeqNo() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SeqNo
}

// GetSeqNoOk returns a tuple with the SeqNo field value
// and a boolean to check if the value has been set.
func (o *TonTxData) GetSeqNoOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SeqNo, true
}

// SetSeqNo sets field value
func (o *TonTxData) SetSeqNo(v int32) {
	o.SeqNo = v
}

// GetShardId returns the ShardId field value
func (o *TonTxData) GetShardId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ShardId
}

// GetShardIdOk returns a tuple with the ShardId field value
// and a boolean to check if the value has been set.
func (o *TonTxData) GetShardIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShardId, true
}

// SetShardId sets field value
func (o *TonTxData) SetShardId(v int32) {
	o.ShardId = v
}

// GetWorkChain returns the WorkChain field value
func (o *TonTxData) GetWorkChain() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WorkChain
}

// GetWorkChainOk returns a tuple with the WorkChain field value
// and a boolean to check if the value has been set.
func (o *TonTxData) GetWorkChainOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkChain, true
}

// SetWorkChain sets field value
func (o *TonTxData) SetWorkChain(v int32) {
	o.WorkChain = v
}

func (o TonTxData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TonTxData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["seq_no"] = o.SeqNo
	toSerialize["shard_id"] = o.ShardId
	toSerialize["work_chain"] = o.WorkChain
	return toSerialize, nil
}

func (o *TonTxData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"seq_no",
		"shard_id",
		"work_chain",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTonTxData := _TonTxData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTonTxData)

	if err != nil {
		return err
	}

	*o = TonTxData(varTonTxData)

	return err
}

type NullableTonTxData struct {
	value *TonTxData
	isSet bool
}

func (v NullableTonTxData) Get() *TonTxData {
	return v.value
}

func (v *NullableTonTxData) Set(val *TonTxData) {
	v.value = val
	v.isSet = true
}

func (v NullableTonTxData) IsSet() bool {
	return v.isSet
}

func (v *NullableTonTxData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTonTxData(val *TonTxData) *NullableTonTxData {
	return &NullableTonTxData{value: val, isSet: true}
}

func (v NullableTonTxData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTonTxData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


