/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// TypeToken the model 'TypeToken'
type TypeToken string

// List of TypeToken
const (
	STABLE TypeToken = "stable"
	WRAPPED TypeToken = "wrapped"
	COMMON TypeToken = "common"
)

// All allowed values of TypeToken enum
var AllowedTypeTokenEnumValues = []TypeToken{
	"stable",
	"wrapped",
	"common",
}

func (v *TypeToken) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TypeToken(value)
	for _, existing := range AllowedTypeTokenEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TypeToken", value)
}

// NewTypeTokenFromValue returns a pointer to a valid TypeToken
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTypeTokenFromValue(v string) (*TypeToken, error) {
	ev := TypeToken(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TypeToken: valid values are %v", v, AllowedTypeTokenEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TypeToken) IsValid() bool {
	for _, existing := range AllowedTypeTokenEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TypeToken value
func (v TypeToken) Ptr() *TypeToken {
	return &v
}

type NullableTypeToken struct {
	value *TypeToken
	isSet bool
}

func (v NullableTypeToken) Get() *TypeToken {
	return v.value
}

func (v *NullableTypeToken) Set(val *TypeToken) {
	v.value = val
	v.isSet = true
}

func (v NullableTypeToken) IsSet() bool {
	return v.isSet
}

func (v *NullableTypeToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypeToken(val *TypeToken) *NullableTypeToken {
	return &NullableTypeToken{value: val, isSet: true}
}

func (v NullableTypeToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypeToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

