/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdatePairsStatusRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePairsStatusRequest{}

// UpdatePairsStatusRequest struct for UpdatePairsStatusRequest
type UpdatePairsStatusRequest struct {
	Pairs []UpdatePairsStatusRequestPairsInner `json:"pairs"`
}

type _UpdatePairsStatusRequest UpdatePairsStatusRequest

// NewUpdatePairsStatusRequest instantiates a new UpdatePairsStatusRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePairsStatusRequest(pairs []UpdatePairsStatusRequestPairsInner) *UpdatePairsStatusRequest {
	this := UpdatePairsStatusRequest{}
	this.Pairs = pairs
	return &this
}

// NewUpdatePairsStatusRequestWithDefaults instantiates a new UpdatePairsStatusRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePairsStatusRequestWithDefaults() *UpdatePairsStatusRequest {
	this := UpdatePairsStatusRequest{}
	return &this
}

// GetPairs returns the Pairs field value
func (o *UpdatePairsStatusRequest) GetPairs() []UpdatePairsStatusRequestPairsInner {
	if o == nil {
		var ret []UpdatePairsStatusRequestPairsInner
		return ret
	}

	return o.Pairs
}

// GetPairsOk returns a tuple with the Pairs field value
// and a boolean to check if the value has been set.
func (o *UpdatePairsStatusRequest) GetPairsOk() ([]UpdatePairsStatusRequestPairsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pairs, true
}

// SetPairs sets field value
func (o *UpdatePairsStatusRequest) SetPairs(v []UpdatePairsStatusRequestPairsInner) {
	o.Pairs = v
}

func (o UpdatePairsStatusRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePairsStatusRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pairs"] = o.Pairs
	return toSerialize, nil
}

func (o *UpdatePairsStatusRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pairs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdatePairsStatusRequest := _UpdatePairsStatusRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdatePairsStatusRequest)

	if err != nil {
		return err
	}

	*o = UpdatePairsStatusRequest(varUpdatePairsStatusRequest)

	return err
}

type NullableUpdatePairsStatusRequest struct {
	value *UpdatePairsStatusRequest
	isSet bool
}

func (v NullableUpdatePairsStatusRequest) Get() *UpdatePairsStatusRequest {
	return v.value
}

func (v *NullableUpdatePairsStatusRequest) Set(val *UpdatePairsStatusRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePairsStatusRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePairsStatusRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePairsStatusRequest(val *UpdatePairsStatusRequest) *NullableUpdatePairsStatusRequest {
	return &NullableUpdatePairsStatusRequest{value: val, isSet: true}
}

func (v NullableUpdatePairsStatusRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePairsStatusRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


