/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FarmListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FarmListRequest{}

// FarmListRequest struct for FarmListRequest
type FarmListRequest struct {
	Networks []NetworkType `json:"networks,omitempty"`
	FactoryAddresses []string `json:"factory_addresses,omitempty"`
	SortBy *string `json:"sort_by,omitempty"`
	SortValue *string `json:"sort_value,omitempty"`
	OrderBy *OrderBy `json:"order_by,omitempty"`
	Search *string `json:"search,omitempty"`
	Cursor *string `json:"cursor,omitempty"`
	Count int32 `json:"count"`
}

type _FarmListRequest FarmListRequest

// NewFarmListRequest instantiates a new FarmListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFarmListRequest(count int32) *FarmListRequest {
	this := FarmListRequest{}
	var sortBy string = "liquidity"
	this.SortBy = &sortBy
	var orderBy OrderBy = DESC
	this.OrderBy = &orderBy
	this.Count = count
	return &this
}

// NewFarmListRequestWithDefaults instantiates a new FarmListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFarmListRequestWithDefaults() *FarmListRequest {
	this := FarmListRequest{}
	var sortBy string = "liquidity"
	this.SortBy = &sortBy
	var orderBy OrderBy = DESC
	this.OrderBy = &orderBy
	var count int32 = 10
	this.Count = count
	return &this
}

// GetNetworks returns the Networks field value if set, zero value otherwise.
func (o *FarmListRequest) GetNetworks() []NetworkType {
	if o == nil || IsNil(o.Networks) {
		var ret []NetworkType
		return ret
	}
	return o.Networks
}

// GetNetworksOk returns a tuple with the Networks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmListRequest) GetNetworksOk() ([]NetworkType, bool) {
	if o == nil || IsNil(o.Networks) {
		return nil, false
	}
	return o.Networks, true
}

// HasNetworks returns a boolean if a field has been set.
func (o *FarmListRequest) HasNetworks() bool {
	if o != nil && !IsNil(o.Networks) {
		return true
	}

	return false
}

// SetNetworks gets a reference to the given []NetworkType and assigns it to the Networks field.
func (o *FarmListRequest) SetNetworks(v []NetworkType) {
	o.Networks = v
}

// GetFactoryAddresses returns the FactoryAddresses field value if set, zero value otherwise.
func (o *FarmListRequest) GetFactoryAddresses() []string {
	if o == nil || IsNil(o.FactoryAddresses) {
		var ret []string
		return ret
	}
	return o.FactoryAddresses
}

// GetFactoryAddressesOk returns a tuple with the FactoryAddresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmListRequest) GetFactoryAddressesOk() ([]string, bool) {
	if o == nil || IsNil(o.FactoryAddresses) {
		return nil, false
	}
	return o.FactoryAddresses, true
}

// HasFactoryAddresses returns a boolean if a field has been set.
func (o *FarmListRequest) HasFactoryAddresses() bool {
	if o != nil && !IsNil(o.FactoryAddresses) {
		return true
	}

	return false
}

// SetFactoryAddresses gets a reference to the given []string and assigns it to the FactoryAddresses field.
func (o *FarmListRequest) SetFactoryAddresses(v []string) {
	o.FactoryAddresses = v
}

// GetSortBy returns the SortBy field value if set, zero value otherwise.
func (o *FarmListRequest) GetSortBy() string {
	if o == nil || IsNil(o.SortBy) {
		var ret string
		return ret
	}
	return *o.SortBy
}

// GetSortByOk returns a tuple with the SortBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmListRequest) GetSortByOk() (*string, bool) {
	if o == nil || IsNil(o.SortBy) {
		return nil, false
	}
	return o.SortBy, true
}

// HasSortBy returns a boolean if a field has been set.
func (o *FarmListRequest) HasSortBy() bool {
	if o != nil && !IsNil(o.SortBy) {
		return true
	}

	return false
}

// SetSortBy gets a reference to the given string and assigns it to the SortBy field.
func (o *FarmListRequest) SetSortBy(v string) {
	o.SortBy = &v
}

// GetSortValue returns the SortValue field value if set, zero value otherwise.
func (o *FarmListRequest) GetSortValue() string {
	if o == nil || IsNil(o.SortValue) {
		var ret string
		return ret
	}
	return *o.SortValue
}

// GetSortValueOk returns a tuple with the SortValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmListRequest) GetSortValueOk() (*string, bool) {
	if o == nil || IsNil(o.SortValue) {
		return nil, false
	}
	return o.SortValue, true
}

// HasSortValue returns a boolean if a field has been set.
func (o *FarmListRequest) HasSortValue() bool {
	if o != nil && !IsNil(o.SortValue) {
		return true
	}

	return false
}

// SetSortValue gets a reference to the given string and assigns it to the SortValue field.
func (o *FarmListRequest) SetSortValue(v string) {
	o.SortValue = &v
}

// GetOrderBy returns the OrderBy field value if set, zero value otherwise.
func (o *FarmListRequest) GetOrderBy() OrderBy {
	if o == nil || IsNil(o.OrderBy) {
		var ret OrderBy
		return ret
	}
	return *o.OrderBy
}

// GetOrderByOk returns a tuple with the OrderBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmListRequest) GetOrderByOk() (*OrderBy, bool) {
	if o == nil || IsNil(o.OrderBy) {
		return nil, false
	}
	return o.OrderBy, true
}

// HasOrderBy returns a boolean if a field has been set.
func (o *FarmListRequest) HasOrderBy() bool {
	if o != nil && !IsNil(o.OrderBy) {
		return true
	}

	return false
}

// SetOrderBy gets a reference to the given OrderBy and assigns it to the OrderBy field.
func (o *FarmListRequest) SetOrderBy(v OrderBy) {
	o.OrderBy = &v
}

// GetSearch returns the Search field value if set, zero value otherwise.
func (o *FarmListRequest) GetSearch() string {
	if o == nil || IsNil(o.Search) {
		var ret string
		return ret
	}
	return *o.Search
}

// GetSearchOk returns a tuple with the Search field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmListRequest) GetSearchOk() (*string, bool) {
	if o == nil || IsNil(o.Search) {
		return nil, false
	}
	return o.Search, true
}

// HasSearch returns a boolean if a field has been set.
func (o *FarmListRequest) HasSearch() bool {
	if o != nil && !IsNil(o.Search) {
		return true
	}

	return false
}

// SetSearch gets a reference to the given string and assigns it to the Search field.
func (o *FarmListRequest) SetSearch(v string) {
	o.Search = &v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *FarmListRequest) GetCursor() string {
	if o == nil || IsNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmListRequest) GetCursorOk() (*string, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *FarmListRequest) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *FarmListRequest) SetCursor(v string) {
	o.Cursor = &v
}

// GetCount returns the Count field value
func (o *FarmListRequest) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *FarmListRequest) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *FarmListRequest) SetCount(v int32) {
	o.Count = v
}

func (o FarmListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FarmListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Networks) {
		toSerialize["networks"] = o.Networks
	}
	if !IsNil(o.FactoryAddresses) {
		toSerialize["factory_addresses"] = o.FactoryAddresses
	}
	if !IsNil(o.SortBy) {
		toSerialize["sort_by"] = o.SortBy
	}
	if !IsNil(o.SortValue) {
		toSerialize["sort_value"] = o.SortValue
	}
	if !IsNil(o.OrderBy) {
		toSerialize["order_by"] = o.OrderBy
	}
	if !IsNil(o.Search) {
		toSerialize["search"] = o.Search
	}
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	toSerialize["count"] = o.Count
	return toSerialize, nil
}

func (o *FarmListRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFarmListRequest := _FarmListRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFarmListRequest)

	if err != nil {
		return err
	}

	*o = FarmListRequest(varFarmListRequest)

	return err
}

type NullableFarmListRequest struct {
	value *FarmListRequest
	isSet bool
}

func (v NullableFarmListRequest) Get() *FarmListRequest {
	return v.value
}

func (v *NullableFarmListRequest) Set(val *FarmListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFarmListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFarmListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFarmListRequest(val *FarmListRequest) *NullableFarmListRequest {
	return &NullableFarmListRequest{value: val, isSet: true}
}

func (v NullableFarmListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFarmListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


