/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DexInfoList200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DexInfoList200Response{}

// DexInfoList200Response struct for DexInfoList200Response
type DexInfoList200Response struct {
	Items []DexInfo `json:"items"`
	Count int32 `json:"count"`
}

type _DexInfoList200Response DexInfoList200Response

// NewDexInfoList200Response instantiates a new DexInfoList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDexInfoList200Response(items []DexInfo, count int32) *DexInfoList200Response {
	this := DexInfoList200Response{}
	this.Items = items
	this.Count = count
	return &this
}

// NewDexInfoList200ResponseWithDefaults instantiates a new DexInfoList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDexInfoList200ResponseWithDefaults() *DexInfoList200Response {
	this := DexInfoList200Response{}
	return &this
}

// GetItems returns the Items field value
func (o *DexInfoList200Response) GetItems() []DexInfo {
	if o == nil {
		var ret []DexInfo
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *DexInfoList200Response) GetItemsOk() ([]DexInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *DexInfoList200Response) SetItems(v []DexInfo) {
	o.Items = v
}

// GetCount returns the Count field value
func (o *DexInfoList200Response) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *DexInfoList200Response) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *DexInfoList200Response) SetCount(v int32) {
	o.Count = v
}

func (o DexInfoList200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DexInfoList200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["count"] = o.Count
	return toSerialize, nil
}

func (o *DexInfoList200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDexInfoList200Response := _DexInfoList200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDexInfoList200Response)

	if err != nil {
		return err
	}

	*o = DexInfoList200Response(varDexInfoList200Response)

	return err
}

type NullableDexInfoList200Response struct {
	value *DexInfoList200Response
	isSet bool
}

func (v NullableDexInfoList200Response) Get() *DexInfoList200Response {
	return v.value
}

func (v *NullableDexInfoList200Response) Set(val *DexInfoList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDexInfoList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDexInfoList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDexInfoList200Response(val *DexInfoList200Response) *NullableDexInfoList200Response {
	return &NullableDexInfoList200Response{value: val, isSet: true}
}

func (v NullableDexInfoList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDexInfoList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


