/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NftCollectionInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NftCollectionInfo{}

// NftCollectionInfo struct for NftCollectionInfo
type NftCollectionInfo struct {
	ChainId int32 `json:"chain_id"`
	Address string `json:"address"`
	Owner *string `json:"owner,omitempty"`
	Name string `json:"name"`
	Symbol string `json:"symbol"`
	ItemsTotal *int32 `json:"items_total,omitempty"`
	OwnersTotal *int32 `json:"owners_total,omitempty"`
	FloorPrice *int32 `json:"floor_price,omitempty"`
	Assets []NftAssetInfo `json:"assets,omitempty"`
}

type _NftCollectionInfo NftCollectionInfo

// NewNftCollectionInfo instantiates a new NftCollectionInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNftCollectionInfo(chainId int32, address string, name string, symbol string) *NftCollectionInfo {
	this := NftCollectionInfo{}
	this.ChainId = chainId
	this.Address = address
	this.Name = name
	this.Symbol = symbol
	return &this
}

// NewNftCollectionInfoWithDefaults instantiates a new NftCollectionInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNftCollectionInfoWithDefaults() *NftCollectionInfo {
	this := NftCollectionInfo{}
	return &this
}

// GetChainId returns the ChainId field value
func (o *NftCollectionInfo) GetChainId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *NftCollectionInfo) GetChainIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *NftCollectionInfo) SetChainId(v int32) {
	o.ChainId = v
}

// GetAddress returns the Address field value
func (o *NftCollectionInfo) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *NftCollectionInfo) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *NftCollectionInfo) SetAddress(v string) {
	o.Address = v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *NftCollectionInfo) GetOwner() string {
	if o == nil || IsNil(o.Owner) {
		var ret string
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftCollectionInfo) GetOwnerOk() (*string, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *NftCollectionInfo) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given string and assigns it to the Owner field.
func (o *NftCollectionInfo) SetOwner(v string) {
	o.Owner = &v
}

// GetName returns the Name field value
func (o *NftCollectionInfo) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NftCollectionInfo) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NftCollectionInfo) SetName(v string) {
	o.Name = v
}

// GetSymbol returns the Symbol field value
func (o *NftCollectionInfo) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *NftCollectionInfo) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *NftCollectionInfo) SetSymbol(v string) {
	o.Symbol = v
}

// GetItemsTotal returns the ItemsTotal field value if set, zero value otherwise.
func (o *NftCollectionInfo) GetItemsTotal() int32 {
	if o == nil || IsNil(o.ItemsTotal) {
		var ret int32
		return ret
	}
	return *o.ItemsTotal
}

// GetItemsTotalOk returns a tuple with the ItemsTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftCollectionInfo) GetItemsTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.ItemsTotal) {
		return nil, false
	}
	return o.ItemsTotal, true
}

// HasItemsTotal returns a boolean if a field has been set.
func (o *NftCollectionInfo) HasItemsTotal() bool {
	if o != nil && !IsNil(o.ItemsTotal) {
		return true
	}

	return false
}

// SetItemsTotal gets a reference to the given int32 and assigns it to the ItemsTotal field.
func (o *NftCollectionInfo) SetItemsTotal(v int32) {
	o.ItemsTotal = &v
}

// GetOwnersTotal returns the OwnersTotal field value if set, zero value otherwise.
func (o *NftCollectionInfo) GetOwnersTotal() int32 {
	if o == nil || IsNil(o.OwnersTotal) {
		var ret int32
		return ret
	}
	return *o.OwnersTotal
}

// GetOwnersTotalOk returns a tuple with the OwnersTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftCollectionInfo) GetOwnersTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.OwnersTotal) {
		return nil, false
	}
	return o.OwnersTotal, true
}

// HasOwnersTotal returns a boolean if a field has been set.
func (o *NftCollectionInfo) HasOwnersTotal() bool {
	if o != nil && !IsNil(o.OwnersTotal) {
		return true
	}

	return false
}

// SetOwnersTotal gets a reference to the given int32 and assigns it to the OwnersTotal field.
func (o *NftCollectionInfo) SetOwnersTotal(v int32) {
	o.OwnersTotal = &v
}

// GetFloorPrice returns the FloorPrice field value if set, zero value otherwise.
func (o *NftCollectionInfo) GetFloorPrice() int32 {
	if o == nil || IsNil(o.FloorPrice) {
		var ret int32
		return ret
	}
	return *o.FloorPrice
}

// GetFloorPriceOk returns a tuple with the FloorPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftCollectionInfo) GetFloorPriceOk() (*int32, bool) {
	if o == nil || IsNil(o.FloorPrice) {
		return nil, false
	}
	return o.FloorPrice, true
}

// HasFloorPrice returns a boolean if a field has been set.
func (o *NftCollectionInfo) HasFloorPrice() bool {
	if o != nil && !IsNil(o.FloorPrice) {
		return true
	}

	return false
}

// SetFloorPrice gets a reference to the given int32 and assigns it to the FloorPrice field.
func (o *NftCollectionInfo) SetFloorPrice(v int32) {
	o.FloorPrice = &v
}

// GetAssets returns the Assets field value if set, zero value otherwise.
func (o *NftCollectionInfo) GetAssets() []NftAssetInfo {
	if o == nil || IsNil(o.Assets) {
		var ret []NftAssetInfo
		return ret
	}
	return o.Assets
}

// GetAssetsOk returns a tuple with the Assets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftCollectionInfo) GetAssetsOk() ([]NftAssetInfo, bool) {
	if o == nil || IsNil(o.Assets) {
		return nil, false
	}
	return o.Assets, true
}

// HasAssets returns a boolean if a field has been set.
func (o *NftCollectionInfo) HasAssets() bool {
	if o != nil && !IsNil(o.Assets) {
		return true
	}

	return false
}

// SetAssets gets a reference to the given []NftAssetInfo and assigns it to the Assets field.
func (o *NftCollectionInfo) SetAssets(v []NftAssetInfo) {
	o.Assets = v
}

func (o NftCollectionInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NftCollectionInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["chain_id"] = o.ChainId
	toSerialize["address"] = o.Address
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	toSerialize["name"] = o.Name
	toSerialize["symbol"] = o.Symbol
	if !IsNil(o.ItemsTotal) {
		toSerialize["items_total"] = o.ItemsTotal
	}
	if !IsNil(o.OwnersTotal) {
		toSerialize["owners_total"] = o.OwnersTotal
	}
	if !IsNil(o.FloorPrice) {
		toSerialize["floor_price"] = o.FloorPrice
	}
	if !IsNil(o.Assets) {
		toSerialize["assets"] = o.Assets
	}
	return toSerialize, nil
}

func (o *NftCollectionInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"chain_id",
		"address",
		"name",
		"symbol",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNftCollectionInfo := _NftCollectionInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNftCollectionInfo)

	if err != nil {
		return err
	}

	*o = NftCollectionInfo(varNftCollectionInfo)

	return err
}

type NullableNftCollectionInfo struct {
	value *NftCollectionInfo
	isSet bool
}

func (v NullableNftCollectionInfo) Get() *NftCollectionInfo {
	return v.value
}

func (v *NullableNftCollectionInfo) Set(val *NftCollectionInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableNftCollectionInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableNftCollectionInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNftCollectionInfo(val *NftCollectionInfo) *NullableNftCollectionInfo {
	return &NullableNftCollectionInfo{value: val, isSet: true}
}

func (v NullableNftCollectionInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNftCollectionInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


