/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TokenList200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenList200Response{}

// TokenList200Response struct for TokenList200Response
type TokenList200Response struct {
	Items []TokenInfo `json:"items,omitempty"`
	NextCursor *string `json:"nextCursor,omitempty"`
	BackCursor *string `json:"backCursor,omitempty"`
}

// NewTokenList200Response instantiates a new TokenList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenList200Response() *TokenList200Response {
	this := TokenList200Response{}
	return &this
}

// NewTokenList200ResponseWithDefaults instantiates a new TokenList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenList200ResponseWithDefaults() *TokenList200Response {
	this := TokenList200Response{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *TokenList200Response) GetItems() []TokenInfo {
	if o == nil || IsNil(o.Items) {
		var ret []TokenInfo
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenList200Response) GetItemsOk() ([]TokenInfo, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *TokenList200Response) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []TokenInfo and assigns it to the Items field.
func (o *TokenList200Response) SetItems(v []TokenInfo) {
	o.Items = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *TokenList200Response) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenList200Response) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *TokenList200Response) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *TokenList200Response) SetNextCursor(v string) {
	o.NextCursor = &v
}

// GetBackCursor returns the BackCursor field value if set, zero value otherwise.
func (o *TokenList200Response) GetBackCursor() string {
	if o == nil || IsNil(o.BackCursor) {
		var ret string
		return ret
	}
	return *o.BackCursor
}

// GetBackCursorOk returns a tuple with the BackCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenList200Response) GetBackCursorOk() (*string, bool) {
	if o == nil || IsNil(o.BackCursor) {
		return nil, false
	}
	return o.BackCursor, true
}

// HasBackCursor returns a boolean if a field has been set.
func (o *TokenList200Response) HasBackCursor() bool {
	if o != nil && !IsNil(o.BackCursor) {
		return true
	}

	return false
}

// SetBackCursor gets a reference to the given string and assigns it to the BackCursor field.
func (o *TokenList200Response) SetBackCursor(v string) {
	o.BackCursor = &v
}

func (o TokenList200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenList200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.NextCursor) {
		toSerialize["nextCursor"] = o.NextCursor
	}
	if !IsNil(o.BackCursor) {
		toSerialize["backCursor"] = o.BackCursor
	}
	return toSerialize, nil
}

type NullableTokenList200Response struct {
	value *TokenList200Response
	isSet bool
}

func (v NullableTokenList200Response) Get() *TokenList200Response {
	return v.value
}

func (v *NullableTokenList200Response) Set(val *TokenList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenList200Response(val *TokenList200Response) *NullableTokenList200Response {
	return &NullableTokenList200Response{value: val, isSet: true}
}

func (v NullableTokenList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


