/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TokenListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenListRequest{}

// TokenListRequest struct for TokenListRequest
type TokenListRequest struct {
	// Filter by blockchain networks
	Networks []NetworkType `json:"networks,omitempty"`
	// Sorting field
	SortBy *string `json:"sort_by,omitempty"`
	SortValue *string `json:"sort_value,omitempty"`
	Res *ResolutionType `json:"res,omitempty"`
	OrderBy *OrderBy `json:"order_by,omitempty"`
	// Cursor for pagination
	Cursor *string `json:"cursor,omitempty"`
	Count int32 `json:"count"`
}

type _TokenListRequest TokenListRequest

// NewTokenListRequest instantiates a new TokenListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenListRequest(count int32) *TokenListRequest {
	this := TokenListRequest{}
	var sortBy string = "liquidity"
	this.SortBy = &sortBy
	var orderBy OrderBy = DESC
	this.OrderBy = &orderBy
	this.Count = count
	return &this
}

// NewTokenListRequestWithDefaults instantiates a new TokenListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenListRequestWithDefaults() *TokenListRequest {
	this := TokenListRequest{}
	var sortBy string = "liquidity"
	this.SortBy = &sortBy
	var orderBy OrderBy = DESC
	this.OrderBy = &orderBy
	var count int32 = 10
	this.Count = count
	return &this
}

// GetNetworks returns the Networks field value if set, zero value otherwise.
func (o *TokenListRequest) GetNetworks() []NetworkType {
	if o == nil || IsNil(o.Networks) {
		var ret []NetworkType
		return ret
	}
	return o.Networks
}

// GetNetworksOk returns a tuple with the Networks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenListRequest) GetNetworksOk() ([]NetworkType, bool) {
	if o == nil || IsNil(o.Networks) {
		return nil, false
	}
	return o.Networks, true
}

// HasNetworks returns a boolean if a field has been set.
func (o *TokenListRequest) HasNetworks() bool {
	if o != nil && !IsNil(o.Networks) {
		return true
	}

	return false
}

// SetNetworks gets a reference to the given []NetworkType and assigns it to the Networks field.
func (o *TokenListRequest) SetNetworks(v []NetworkType) {
	o.Networks = v
}

// GetSortBy returns the SortBy field value if set, zero value otherwise.
func (o *TokenListRequest) GetSortBy() string {
	if o == nil || IsNil(o.SortBy) {
		var ret string
		return ret
	}
	return *o.SortBy
}

// GetSortByOk returns a tuple with the SortBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenListRequest) GetSortByOk() (*string, bool) {
	if o == nil || IsNil(o.SortBy) {
		return nil, false
	}
	return o.SortBy, true
}

// HasSortBy returns a boolean if a field has been set.
func (o *TokenListRequest) HasSortBy() bool {
	if o != nil && !IsNil(o.SortBy) {
		return true
	}

	return false
}

// SetSortBy gets a reference to the given string and assigns it to the SortBy field.
func (o *TokenListRequest) SetSortBy(v string) {
	o.SortBy = &v
}

// GetSortValue returns the SortValue field value if set, zero value otherwise.
func (o *TokenListRequest) GetSortValue() string {
	if o == nil || IsNil(o.SortValue) {
		var ret string
		return ret
	}
	return *o.SortValue
}

// GetSortValueOk returns a tuple with the SortValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenListRequest) GetSortValueOk() (*string, bool) {
	if o == nil || IsNil(o.SortValue) {
		return nil, false
	}
	return o.SortValue, true
}

// HasSortValue returns a boolean if a field has been set.
func (o *TokenListRequest) HasSortValue() bool {
	if o != nil && !IsNil(o.SortValue) {
		return true
	}

	return false
}

// SetSortValue gets a reference to the given string and assigns it to the SortValue field.
func (o *TokenListRequest) SetSortValue(v string) {
	o.SortValue = &v
}

// GetRes returns the Res field value if set, zero value otherwise.
func (o *TokenListRequest) GetRes() ResolutionType {
	if o == nil || IsNil(o.Res) {
		var ret ResolutionType
		return ret
	}
	return *o.Res
}

// GetResOk returns a tuple with the Res field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenListRequest) GetResOk() (*ResolutionType, bool) {
	if o == nil || IsNil(o.Res) {
		return nil, false
	}
	return o.Res, true
}

// HasRes returns a boolean if a field has been set.
func (o *TokenListRequest) HasRes() bool {
	if o != nil && !IsNil(o.Res) {
		return true
	}

	return false
}

// SetRes gets a reference to the given ResolutionType and assigns it to the Res field.
func (o *TokenListRequest) SetRes(v ResolutionType) {
	o.Res = &v
}

// GetOrderBy returns the OrderBy field value if set, zero value otherwise.
func (o *TokenListRequest) GetOrderBy() OrderBy {
	if o == nil || IsNil(o.OrderBy) {
		var ret OrderBy
		return ret
	}
	return *o.OrderBy
}

// GetOrderByOk returns a tuple with the OrderBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenListRequest) GetOrderByOk() (*OrderBy, bool) {
	if o == nil || IsNil(o.OrderBy) {
		return nil, false
	}
	return o.OrderBy, true
}

// HasOrderBy returns a boolean if a field has been set.
func (o *TokenListRequest) HasOrderBy() bool {
	if o != nil && !IsNil(o.OrderBy) {
		return true
	}

	return false
}

// SetOrderBy gets a reference to the given OrderBy and assigns it to the OrderBy field.
func (o *TokenListRequest) SetOrderBy(v OrderBy) {
	o.OrderBy = &v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *TokenListRequest) GetCursor() string {
	if o == nil || IsNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenListRequest) GetCursorOk() (*string, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *TokenListRequest) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *TokenListRequest) SetCursor(v string) {
	o.Cursor = &v
}

// GetCount returns the Count field value
func (o *TokenListRequest) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *TokenListRequest) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *TokenListRequest) SetCount(v int32) {
	o.Count = v
}

func (o TokenListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Networks) {
		toSerialize["networks"] = o.Networks
	}
	if !IsNil(o.SortBy) {
		toSerialize["sort_by"] = o.SortBy
	}
	if !IsNil(o.SortValue) {
		toSerialize["sort_value"] = o.SortValue
	}
	if !IsNil(o.Res) {
		toSerialize["res"] = o.Res
	}
	if !IsNil(o.OrderBy) {
		toSerialize["order_by"] = o.OrderBy
	}
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	toSerialize["count"] = o.Count
	return toSerialize, nil
}

func (o *TokenListRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenListRequest := _TokenListRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokenListRequest)

	if err != nil {
		return err
	}

	*o = TokenListRequest(varTokenListRequest)

	return err
}

type NullableTokenListRequest struct {
	value *TokenListRequest
	isSet bool
}

func (v NullableTokenListRequest) Get() *TokenListRequest {
	return v.value
}

func (v *NullableTokenListRequest) Set(val *TokenListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenListRequest(val *TokenListRequest) *NullableTokenListRequest {
	return &NullableTokenListRequest{value: val, isSet: true}
}

func (v NullableTokenListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


