/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TokenInfoMainPool type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenInfoMainPool{}

// TokenInfoMainPool Main control pool information
type TokenInfoMainPool struct {
	Address *string `json:"address,omitempty"`
	Ticker *string `json:"ticker,omitempty"`
	LiquidityUsd *float32 `json:"liquidity_usd,omitempty"`
}

// NewTokenInfoMainPool instantiates a new TokenInfoMainPool object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenInfoMainPool() *TokenInfoMainPool {
	this := TokenInfoMainPool{}
	return &this
}

// NewTokenInfoMainPoolWithDefaults instantiates a new TokenInfoMainPool object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenInfoMainPoolWithDefaults() *TokenInfoMainPool {
	this := TokenInfoMainPool{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *TokenInfoMainPool) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfoMainPool) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *TokenInfoMainPool) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *TokenInfoMainPool) SetAddress(v string) {
	o.Address = &v
}

// GetTicker returns the Ticker field value if set, zero value otherwise.
func (o *TokenInfoMainPool) GetTicker() string {
	if o == nil || IsNil(o.Ticker) {
		var ret string
		return ret
	}
	return *o.Ticker
}

// GetTickerOk returns a tuple with the Ticker field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfoMainPool) GetTickerOk() (*string, bool) {
	if o == nil || IsNil(o.Ticker) {
		return nil, false
	}
	return o.Ticker, true
}

// HasTicker returns a boolean if a field has been set.
func (o *TokenInfoMainPool) HasTicker() bool {
	if o != nil && !IsNil(o.Ticker) {
		return true
	}

	return false
}

// SetTicker gets a reference to the given string and assigns it to the Ticker field.
func (o *TokenInfoMainPool) SetTicker(v string) {
	o.Ticker = &v
}

// GetLiquidityUsd returns the LiquidityUsd field value if set, zero value otherwise.
func (o *TokenInfoMainPool) GetLiquidityUsd() float32 {
	if o == nil || IsNil(o.LiquidityUsd) {
		var ret float32
		return ret
	}
	return *o.LiquidityUsd
}

// GetLiquidityUsdOk returns a tuple with the LiquidityUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfoMainPool) GetLiquidityUsdOk() (*float32, bool) {
	if o == nil || IsNil(o.LiquidityUsd) {
		return nil, false
	}
	return o.LiquidityUsd, true
}

// HasLiquidityUsd returns a boolean if a field has been set.
func (o *TokenInfoMainPool) HasLiquidityUsd() bool {
	if o != nil && !IsNil(o.LiquidityUsd) {
		return true
	}

	return false
}

// SetLiquidityUsd gets a reference to the given float32 and assigns it to the LiquidityUsd field.
func (o *TokenInfoMainPool) SetLiquidityUsd(v float32) {
	o.LiquidityUsd = &v
}

func (o TokenInfoMainPool) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenInfoMainPool) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Ticker) {
		toSerialize["ticker"] = o.Ticker
	}
	if !IsNil(o.LiquidityUsd) {
		toSerialize["liquidity_usd"] = o.LiquidityUsd
	}
	return toSerialize, nil
}

type NullableTokenInfoMainPool struct {
	value *TokenInfoMainPool
	isSet bool
}

func (v NullableTokenInfoMainPool) Get() *TokenInfoMainPool {
	return v.value
}

func (v *NullableTokenInfoMainPool) Set(val *TokenInfoMainPool) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenInfoMainPool) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenInfoMainPool) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenInfoMainPool(val *TokenInfoMainPool) *NullableTokenInfoMainPool {
	return &NullableTokenInfoMainPool{value: val, isSet: true}
}

func (v NullableTokenInfoMainPool) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenInfoMainPool) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


