/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DexInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DexInfo{}

// DexInfo struct for DexInfo
type DexInfo struct {
	// The unique identifier of the DEX.
	Name string `json:"name"`
	// The total value locked across all networks and protocols.
	TotalTvl float64 `json:"total_tvl"`
	// The total number of trading pairs across all networks and protocols.
	TotalPairs int32 `json:"total_pairs"`
	// The total number of distinct blockchain networks supported.
	TotalNetworks int32 `json:"total_networks"`
	// A list of networks supported by the DEX, detailing each network's protocols.
	SupportedNetworks []NetworkInfo `json:"supported_networks,omitempty"`
}

type _DexInfo DexInfo

// NewDexInfo instantiates a new DexInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDexInfo(name string, totalTvl float64, totalPairs int32, totalNetworks int32) *DexInfo {
	this := DexInfo{}
	this.Name = name
	this.TotalTvl = totalTvl
	this.TotalPairs = totalPairs
	this.TotalNetworks = totalNetworks
	return &this
}

// NewDexInfoWithDefaults instantiates a new DexInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDexInfoWithDefaults() *DexInfo {
	this := DexInfo{}
	return &this
}

// GetName returns the Name field value
func (o *DexInfo) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DexInfo) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DexInfo) SetName(v string) {
	o.Name = v
}

// GetTotalTvl returns the TotalTvl field value
func (o *DexInfo) GetTotalTvl() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.TotalTvl
}

// GetTotalTvlOk returns a tuple with the TotalTvl field value
// and a boolean to check if the value has been set.
func (o *DexInfo) GetTotalTvlOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalTvl, true
}

// SetTotalTvl sets field value
func (o *DexInfo) SetTotalTvl(v float64) {
	o.TotalTvl = v
}

// GetTotalPairs returns the TotalPairs field value
func (o *DexInfo) GetTotalPairs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalPairs
}

// GetTotalPairsOk returns a tuple with the TotalPairs field value
// and a boolean to check if the value has been set.
func (o *DexInfo) GetTotalPairsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalPairs, true
}

// SetTotalPairs sets field value
func (o *DexInfo) SetTotalPairs(v int32) {
	o.TotalPairs = v
}

// GetTotalNetworks returns the TotalNetworks field value
func (o *DexInfo) GetTotalNetworks() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalNetworks
}

// GetTotalNetworksOk returns a tuple with the TotalNetworks field value
// and a boolean to check if the value has been set.
func (o *DexInfo) GetTotalNetworksOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalNetworks, true
}

// SetTotalNetworks sets field value
func (o *DexInfo) SetTotalNetworks(v int32) {
	o.TotalNetworks = v
}

// GetSupportedNetworks returns the SupportedNetworks field value if set, zero value otherwise.
func (o *DexInfo) GetSupportedNetworks() []NetworkInfo {
	if o == nil || IsNil(o.SupportedNetworks) {
		var ret []NetworkInfo
		return ret
	}
	return o.SupportedNetworks
}

// GetSupportedNetworksOk returns a tuple with the SupportedNetworks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DexInfo) GetSupportedNetworksOk() ([]NetworkInfo, bool) {
	if o == nil || IsNil(o.SupportedNetworks) {
		return nil, false
	}
	return o.SupportedNetworks, true
}

// HasSupportedNetworks returns a boolean if a field has been set.
func (o *DexInfo) HasSupportedNetworks() bool {
	if o != nil && !IsNil(o.SupportedNetworks) {
		return true
	}

	return false
}

// SetSupportedNetworks gets a reference to the given []NetworkInfo and assigns it to the SupportedNetworks field.
func (o *DexInfo) SetSupportedNetworks(v []NetworkInfo) {
	o.SupportedNetworks = v
}

func (o DexInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DexInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["total_tvl"] = o.TotalTvl
	toSerialize["total_pairs"] = o.TotalPairs
	toSerialize["total_networks"] = o.TotalNetworks
	if !IsNil(o.SupportedNetworks) {
		toSerialize["supported_networks"] = o.SupportedNetworks
	}
	return toSerialize, nil
}

func (o *DexInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"total_tvl",
		"total_pairs",
		"total_networks",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDexInfo := _DexInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDexInfo)

	if err != nil {
		return err
	}

	*o = DexInfo(varDexInfo)

	return err
}

type NullableDexInfo struct {
	value *DexInfo
	isSet bool
}

func (v NullableDexInfo) Get() *DexInfo {
	return v.value
}

func (v *NullableDexInfo) Set(val *DexInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableDexInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableDexInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDexInfo(val *DexInfo) *NullableDexInfo {
	return &NullableDexInfo{value: val, isSet: true}
}

func (v NullableDexInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDexInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


