/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PairInfoVolume type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PairInfoVolume{}

// PairInfoVolume struct for PairInfoVolume
type PairInfoVolume struct {
	M5 float32 `json:"m5"`
	H1 float32 `json:"h1"`
	H6 float32 `json:"h6"`
	H24 float32 `json:"h24"`
}

type _PairInfoVolume PairInfoVolume

// NewPairInfoVolume instantiates a new PairInfoVolume object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPairInfoVolume(m5 float32, h1 float32, h6 float32, h24 float32) *PairInfoVolume {
	this := PairInfoVolume{}
	this.M5 = m5
	this.H1 = h1
	this.H6 = h6
	this.H24 = h24
	return &this
}

// NewPairInfoVolumeWithDefaults instantiates a new PairInfoVolume object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPairInfoVolumeWithDefaults() *PairInfoVolume {
	this := PairInfoVolume{}
	return &this
}

// GetM5 returns the M5 field value
func (o *PairInfoVolume) GetM5() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.M5
}

// GetM5Ok returns a tuple with the M5 field value
// and a boolean to check if the value has been set.
func (o *PairInfoVolume) GetM5Ok() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.M5, true
}

// SetM5 sets field value
func (o *PairInfoVolume) SetM5(v float32) {
	o.M5 = v
}

// GetH1 returns the H1 field value
func (o *PairInfoVolume) GetH1() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.H1
}

// GetH1Ok returns a tuple with the H1 field value
// and a boolean to check if the value has been set.
func (o *PairInfoVolume) GetH1Ok() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.H1, true
}

// SetH1 sets field value
func (o *PairInfoVolume) SetH1(v float32) {
	o.H1 = v
}

// GetH6 returns the H6 field value
func (o *PairInfoVolume) GetH6() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.H6
}

// GetH6Ok returns a tuple with the H6 field value
// and a boolean to check if the value has been set.
func (o *PairInfoVolume) GetH6Ok() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.H6, true
}

// SetH6 sets field value
func (o *PairInfoVolume) SetH6(v float32) {
	o.H6 = v
}

// GetH24 returns the H24 field value
func (o *PairInfoVolume) GetH24() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.H24
}

// GetH24Ok returns a tuple with the H24 field value
// and a boolean to check if the value has been set.
func (o *PairInfoVolume) GetH24Ok() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.H24, true
}

// SetH24 sets field value
func (o *PairInfoVolume) SetH24(v float32) {
	o.H24 = v
}

func (o PairInfoVolume) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PairInfoVolume) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["m5"] = o.M5
	toSerialize["h1"] = o.H1
	toSerialize["h6"] = o.H6
	toSerialize["h24"] = o.H24
	return toSerialize, nil
}

func (o *PairInfoVolume) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"m5",
		"h1",
		"h6",
		"h24",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPairInfoVolume := _PairInfoVolume{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPairInfoVolume)

	if err != nil {
		return err
	}

	*o = PairInfoVolume(varPairInfoVolume)

	return err
}

type NullablePairInfoVolume struct {
	value *PairInfoVolume
	isSet bool
}

func (v NullablePairInfoVolume) Get() *PairInfoVolume {
	return v.value
}

func (v *NullablePairInfoVolume) Set(val *PairInfoVolume) {
	v.value = val
	v.isSet = true
}

func (v NullablePairInfoVolume) IsSet() bool {
	return v.isSet
}

func (v *NullablePairInfoVolume) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePairInfoVolume(val *PairInfoVolume) *NullablePairInfoVolume {
	return &NullablePairInfoVolume{value: val, isSet: true}
}

func (v NullablePairInfoVolume) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePairInfoVolume) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


