/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RouterInformation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RouterInformation{}

// RouterInformation struct for RouterInformation
type RouterInformation struct {
	FromToken BaseToken `json:"from_token"`
	ToToken BaseToken `json:"to_token"`
	FeeAvgUSD *string `json:"feeAvgUSD,omitempty"`
	MaxHops *int32 `json:"maxHops,omitempty"`
	Route []RouterHop `json:"route"`
}

type _RouterInformation RouterInformation

// NewRouterInformation instantiates a new RouterInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRouterInformation(fromToken BaseToken, toToken BaseToken, route []RouterHop) *RouterInformation {
	this := RouterInformation{}
	this.FromToken = fromToken
	this.ToToken = toToken
	this.Route = route
	return &this
}

// NewRouterInformationWithDefaults instantiates a new RouterInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRouterInformationWithDefaults() *RouterInformation {
	this := RouterInformation{}
	return &this
}

// GetFromToken returns the FromToken field value
func (o *RouterInformation) GetFromToken() BaseToken {
	if o == nil {
		var ret BaseToken
		return ret
	}

	return o.FromToken
}

// GetFromTokenOk returns a tuple with the FromToken field value
// and a boolean to check if the value has been set.
func (o *RouterInformation) GetFromTokenOk() (*BaseToken, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromToken, true
}

// SetFromToken sets field value
func (o *RouterInformation) SetFromToken(v BaseToken) {
	o.FromToken = v
}

// GetToToken returns the ToToken field value
func (o *RouterInformation) GetToToken() BaseToken {
	if o == nil {
		var ret BaseToken
		return ret
	}

	return o.ToToken
}

// GetToTokenOk returns a tuple with the ToToken field value
// and a boolean to check if the value has been set.
func (o *RouterInformation) GetToTokenOk() (*BaseToken, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToToken, true
}

// SetToToken sets field value
func (o *RouterInformation) SetToToken(v BaseToken) {
	o.ToToken = v
}

// GetFeeAvgUSD returns the FeeAvgUSD field value if set, zero value otherwise.
func (o *RouterInformation) GetFeeAvgUSD() string {
	if o == nil || IsNil(o.FeeAvgUSD) {
		var ret string
		return ret
	}
	return *o.FeeAvgUSD
}

// GetFeeAvgUSDOk returns a tuple with the FeeAvgUSD field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RouterInformation) GetFeeAvgUSDOk() (*string, bool) {
	if o == nil || IsNil(o.FeeAvgUSD) {
		return nil, false
	}
	return o.FeeAvgUSD, true
}

// HasFeeAvgUSD returns a boolean if a field has been set.
func (o *RouterInformation) HasFeeAvgUSD() bool {
	if o != nil && !IsNil(o.FeeAvgUSD) {
		return true
	}

	return false
}

// SetFeeAvgUSD gets a reference to the given string and assigns it to the FeeAvgUSD field.
func (o *RouterInformation) SetFeeAvgUSD(v string) {
	o.FeeAvgUSD = &v
}

// GetMaxHops returns the MaxHops field value if set, zero value otherwise.
func (o *RouterInformation) GetMaxHops() int32 {
	if o == nil || IsNil(o.MaxHops) {
		var ret int32
		return ret
	}
	return *o.MaxHops
}

// GetMaxHopsOk returns a tuple with the MaxHops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RouterInformation) GetMaxHopsOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxHops) {
		return nil, false
	}
	return o.MaxHops, true
}

// HasMaxHops returns a boolean if a field has been set.
func (o *RouterInformation) HasMaxHops() bool {
	if o != nil && !IsNil(o.MaxHops) {
		return true
	}

	return false
}

// SetMaxHops gets a reference to the given int32 and assigns it to the MaxHops field.
func (o *RouterInformation) SetMaxHops(v int32) {
	o.MaxHops = &v
}

// GetRoute returns the Route field value
func (o *RouterInformation) GetRoute() []RouterHop {
	if o == nil {
		var ret []RouterHop
		return ret
	}

	return o.Route
}

// GetRouteOk returns a tuple with the Route field value
// and a boolean to check if the value has been set.
func (o *RouterInformation) GetRouteOk() ([]RouterHop, bool) {
	if o == nil {
		return nil, false
	}
	return o.Route, true
}

// SetRoute sets field value
func (o *RouterInformation) SetRoute(v []RouterHop) {
	o.Route = v
}

func (o RouterInformation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RouterInformation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["from_token"] = o.FromToken
	toSerialize["to_token"] = o.ToToken
	if !IsNil(o.FeeAvgUSD) {
		toSerialize["feeAvgUSD"] = o.FeeAvgUSD
	}
	if !IsNil(o.MaxHops) {
		toSerialize["maxHops"] = o.MaxHops
	}
	toSerialize["route"] = o.Route
	return toSerialize, nil
}

func (o *RouterInformation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"from_token",
		"to_token",
		"route",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRouterInformation := _RouterInformation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRouterInformation)

	if err != nil {
		return err
	}

	*o = RouterInformation(varRouterInformation)

	return err
}

type NullableRouterInformation struct {
	value *RouterInformation
	isSet bool
}

func (v NullableRouterInformation) Get() *RouterInformation {
	return v.value
}

func (v *NullableRouterInformation) Set(val *RouterInformation) {
	v.value = val
	v.isSet = true
}

func (v NullableRouterInformation) IsSet() bool {
	return v.isSet
}

func (v *NullableRouterInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRouterInformation(val *RouterInformation) *NullableRouterInformation {
	return &NullableRouterInformation{value: val, isSet: true}
}

func (v NullableRouterInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRouterInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


