/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WalletInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WalletInfo{}

// WalletInfo struct for WalletInfo
type WalletInfo struct {
	Address string `json:"address"`
	ChainId int32 `json:"chain_id"`
	TotalAmountUsd float32 `json:"total_amount_usd"`
	Tokens []WalletTokenInfo `json:"tokens"`
}

type _WalletInfo WalletInfo

// NewWalletInfo instantiates a new WalletInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWalletInfo(address string, chainId int32, totalAmountUsd float32, tokens []WalletTokenInfo) *WalletInfo {
	this := WalletInfo{}
	this.Address = address
	this.ChainId = chainId
	this.TotalAmountUsd = totalAmountUsd
	this.Tokens = tokens
	return &this
}

// NewWalletInfoWithDefaults instantiates a new WalletInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWalletInfoWithDefaults() *WalletInfo {
	this := WalletInfo{}
	return &this
}

// GetAddress returns the Address field value
func (o *WalletInfo) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *WalletInfo) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *WalletInfo) SetAddress(v string) {
	o.Address = v
}

// GetChainId returns the ChainId field value
func (o *WalletInfo) GetChainId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *WalletInfo) GetChainIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *WalletInfo) SetChainId(v int32) {
	o.ChainId = v
}

// GetTotalAmountUsd returns the TotalAmountUsd field value
func (o *WalletInfo) GetTotalAmountUsd() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalAmountUsd
}

// GetTotalAmountUsdOk returns a tuple with the TotalAmountUsd field value
// and a boolean to check if the value has been set.
func (o *WalletInfo) GetTotalAmountUsdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalAmountUsd, true
}

// SetTotalAmountUsd sets field value
func (o *WalletInfo) SetTotalAmountUsd(v float32) {
	o.TotalAmountUsd = v
}

// GetTokens returns the Tokens field value
func (o *WalletInfo) GetTokens() []WalletTokenInfo {
	if o == nil {
		var ret []WalletTokenInfo
		return ret
	}

	return o.Tokens
}

// GetTokensOk returns a tuple with the Tokens field value
// and a boolean to check if the value has been set.
func (o *WalletInfo) GetTokensOk() ([]WalletTokenInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tokens, true
}

// SetTokens sets field value
func (o *WalletInfo) SetTokens(v []WalletTokenInfo) {
	o.Tokens = v
}

func (o WalletInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WalletInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["chain_id"] = o.ChainId
	toSerialize["total_amount_usd"] = o.TotalAmountUsd
	toSerialize["tokens"] = o.Tokens
	return toSerialize, nil
}

func (o *WalletInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"chain_id",
		"total_amount_usd",
		"tokens",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWalletInfo := _WalletInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWalletInfo)

	if err != nil {
		return err
	}

	*o = WalletInfo(varWalletInfo)

	return err
}

type NullableWalletInfo struct {
	value *WalletInfo
	isSet bool
}

func (v NullableWalletInfo) Get() *WalletInfo {
	return v.value
}

func (v *NullableWalletInfo) Set(val *WalletInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableWalletInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableWalletInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWalletInfo(val *WalletInfo) *NullableWalletInfo {
	return &NullableWalletInfo{value: val, isSet: true}
}

func (v NullableWalletInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWalletInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


