/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TxnPairStat type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TxnPairStat{}

// TxnPairStat struct for TxnPairStat
type TxnPairStat struct {
	Buys int32 `json:"buys"`
	Sells int32 `json:"sells"`
}

type _TxnPairStat TxnPairStat

// NewTxnPairStat instantiates a new TxnPairStat object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTxnPairStat(buys int32, sells int32) *TxnPairStat {
	this := TxnPairStat{}
	this.Buys = buys
	this.Sells = sells
	return &this
}

// NewTxnPairStatWithDefaults instantiates a new TxnPairStat object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTxnPairStatWithDefaults() *TxnPairStat {
	this := TxnPairStat{}
	return &this
}

// GetBuys returns the Buys field value
func (o *TxnPairStat) GetBuys() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Buys
}

// GetBuysOk returns a tuple with the Buys field value
// and a boolean to check if the value has been set.
func (o *TxnPairStat) GetBuysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Buys, true
}

// SetBuys sets field value
func (o *TxnPairStat) SetBuys(v int32) {
	o.Buys = v
}

// GetSells returns the Sells field value
func (o *TxnPairStat) GetSells() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Sells
}

// GetSellsOk returns a tuple with the Sells field value
// and a boolean to check if the value has been set.
func (o *TxnPairStat) GetSellsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sells, true
}

// SetSells sets field value
func (o *TxnPairStat) SetSells(v int32) {
	o.Sells = v
}

func (o TxnPairStat) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TxnPairStat) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["buys"] = o.Buys
	toSerialize["sells"] = o.Sells
	return toSerialize, nil
}

func (o *TxnPairStat) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"buys",
		"sells",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTxnPairStat := _TxnPairStat{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTxnPairStat)

	if err != nil {
		return err
	}

	*o = TxnPairStat(varTxnPairStat)

	return err
}

type NullableTxnPairStat struct {
	value *TxnPairStat
	isSet bool
}

func (v NullableTxnPairStat) Get() *TxnPairStat {
	return v.value
}

func (v *NullableTxnPairStat) Set(val *TxnPairStat) {
	v.value = val
	v.isSet = true
}

func (v NullableTxnPairStat) IsSet() bool {
	return v.isSet
}

func (v *NullableTxnPairStat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTxnPairStat(val *TxnPairStat) *NullableTxnPairStat {
	return &NullableTxnPairStat{value: val, isSet: true}
}

func (v NullableTxnPairStat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTxnPairStat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


