/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LiquidityEventData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LiquidityEventData{}

// LiquidityEventData struct for LiquidityEventData
type LiquidityEventData struct {
	Tokens []LiquidityTokenChange `json:"tokens"`
	LiquidityUsd *float32 `json:"liquidity_usd,omitempty"`
}

type _LiquidityEventData LiquidityEventData

// NewLiquidityEventData instantiates a new LiquidityEventData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLiquidityEventData(tokens []LiquidityTokenChange) *LiquidityEventData {
	this := LiquidityEventData{}
	this.Tokens = tokens
	return &this
}

// NewLiquidityEventDataWithDefaults instantiates a new LiquidityEventData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLiquidityEventDataWithDefaults() *LiquidityEventData {
	this := LiquidityEventData{}
	return &this
}

// GetTokens returns the Tokens field value
func (o *LiquidityEventData) GetTokens() []LiquidityTokenChange {
	if o == nil {
		var ret []LiquidityTokenChange
		return ret
	}

	return o.Tokens
}

// GetTokensOk returns a tuple with the Tokens field value
// and a boolean to check if the value has been set.
func (o *LiquidityEventData) GetTokensOk() ([]LiquidityTokenChange, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tokens, true
}

// SetTokens sets field value
func (o *LiquidityEventData) SetTokens(v []LiquidityTokenChange) {
	o.Tokens = v
}

// GetLiquidityUsd returns the LiquidityUsd field value if set, zero value otherwise.
func (o *LiquidityEventData) GetLiquidityUsd() float32 {
	if o == nil || IsNil(o.LiquidityUsd) {
		var ret float32
		return ret
	}
	return *o.LiquidityUsd
}

// GetLiquidityUsdOk returns a tuple with the LiquidityUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LiquidityEventData) GetLiquidityUsdOk() (*float32, bool) {
	if o == nil || IsNil(o.LiquidityUsd) {
		return nil, false
	}
	return o.LiquidityUsd, true
}

// HasLiquidityUsd returns a boolean if a field has been set.
func (o *LiquidityEventData) HasLiquidityUsd() bool {
	if o != nil && !IsNil(o.LiquidityUsd) {
		return true
	}

	return false
}

// SetLiquidityUsd gets a reference to the given float32 and assigns it to the LiquidityUsd field.
func (o *LiquidityEventData) SetLiquidityUsd(v float32) {
	o.LiquidityUsd = &v
}

func (o LiquidityEventData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LiquidityEventData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tokens"] = o.Tokens
	if !IsNil(o.LiquidityUsd) {
		toSerialize["liquidity_usd"] = o.LiquidityUsd
	}
	return toSerialize, nil
}

func (o *LiquidityEventData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tokens",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLiquidityEventData := _LiquidityEventData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLiquidityEventData)

	if err != nil {
		return err
	}

	*o = LiquidityEventData(varLiquidityEventData)

	return err
}

type NullableLiquidityEventData struct {
	value *LiquidityEventData
	isSet bool
}

func (v NullableLiquidityEventData) Get() *LiquidityEventData {
	return v.value
}

func (v *NullableLiquidityEventData) Set(val *LiquidityEventData) {
	v.value = val
	v.isSet = true
}

func (v NullableLiquidityEventData) IsSet() bool {
	return v.isSet
}

func (v *NullableLiquidityEventData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLiquidityEventData(val *LiquidityEventData) *NullableLiquidityEventData {
	return &NullableLiquidityEventData{value: val, isSet: true}
}

func (v NullableLiquidityEventData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLiquidityEventData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


