/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PairState State of a trading pair
type PairState int32

// List of PairState
const (
	_0 PairState = 0
	_1 PairState = 1
	_2 PairState = 2
	_50 PairState = 50
	_51 PairState = 51
	_52 PairState = 52
	_53 PairState = 53
	_54 PairState = 54
)

// All allowed values of PairState enum
var AllowedPairStateEnumValues = []PairState{
	0,
	1,
	2,
	50,
	51,
	52,
	53,
	54,
}

func (v *PairState) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PairState(value)
	for _, existing := range AllowedPairStateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PairState", value)
}

// NewPairStateFromValue returns a pointer to a valid PairState
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPairStateFromValue(v int32) (*PairState, error) {
	ev := PairState(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PairState: valid values are %v", v, AllowedPairStateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PairState) IsValid() bool {
	for _, existing := range AllowedPairStateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PairState value
func (v PairState) Ptr() *PairState {
	return &v
}

type NullablePairState struct {
	value *PairState
	isSet bool
}

func (v NullablePairState) Get() *PairState {
	return v.value
}

func (v *NullablePairState) Set(val *PairState) {
	v.value = val
	v.isSet = true
}

func (v NullablePairState) IsSet() bool {
	return v.isSet
}

func (v *NullablePairState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePairState(val *PairState) *NullablePairState {
	return &NullablePairState{value: val, isSet: true}
}

func (v NullablePairState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePairState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

