/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LiquidityTokenChange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LiquidityTokenChange{}

// LiquidityTokenChange struct for LiquidityTokenChange
type LiquidityTokenChange struct {
	Address string `json:"address"`
	Symbol *string `json:"symbol,omitempty"`
	Amount float32 `json:"amount"`
	PriceUsd float32 `json:"price_usd"`
}

type _LiquidityTokenChange LiquidityTokenChange

// NewLiquidityTokenChange instantiates a new LiquidityTokenChange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLiquidityTokenChange(address string, amount float32, priceUsd float32) *LiquidityTokenChange {
	this := LiquidityTokenChange{}
	this.Address = address
	this.Amount = amount
	this.PriceUsd = priceUsd
	return &this
}

// NewLiquidityTokenChangeWithDefaults instantiates a new LiquidityTokenChange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLiquidityTokenChangeWithDefaults() *LiquidityTokenChange {
	this := LiquidityTokenChange{}
	return &this
}

// GetAddress returns the Address field value
func (o *LiquidityTokenChange) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *LiquidityTokenChange) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *LiquidityTokenChange) SetAddress(v string) {
	o.Address = v
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *LiquidityTokenChange) GetSymbol() string {
	if o == nil || IsNil(o.Symbol) {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LiquidityTokenChange) GetSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.Symbol) {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *LiquidityTokenChange) HasSymbol() bool {
	if o != nil && !IsNil(o.Symbol) {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *LiquidityTokenChange) SetSymbol(v string) {
	o.Symbol = &v
}

// GetAmount returns the Amount field value
func (o *LiquidityTokenChange) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *LiquidityTokenChange) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *LiquidityTokenChange) SetAmount(v float32) {
	o.Amount = v
}

// GetPriceUsd returns the PriceUsd field value
func (o *LiquidityTokenChange) GetPriceUsd() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PriceUsd
}

// GetPriceUsdOk returns a tuple with the PriceUsd field value
// and a boolean to check if the value has been set.
func (o *LiquidityTokenChange) GetPriceUsdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceUsd, true
}

// SetPriceUsd sets field value
func (o *LiquidityTokenChange) SetPriceUsd(v float32) {
	o.PriceUsd = v
}

func (o LiquidityTokenChange) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LiquidityTokenChange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	if !IsNil(o.Symbol) {
		toSerialize["symbol"] = o.Symbol
	}
	toSerialize["amount"] = o.Amount
	toSerialize["price_usd"] = o.PriceUsd
	return toSerialize, nil
}

func (o *LiquidityTokenChange) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"amount",
		"price_usd",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLiquidityTokenChange := _LiquidityTokenChange{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLiquidityTokenChange)

	if err != nil {
		return err
	}

	*o = LiquidityTokenChange(varLiquidityTokenChange)

	return err
}

type NullableLiquidityTokenChange struct {
	value *LiquidityTokenChange
	isSet bool
}

func (v NullableLiquidityTokenChange) Get() *LiquidityTokenChange {
	return v.value
}

func (v *NullableLiquidityTokenChange) Set(val *LiquidityTokenChange) {
	v.value = val
	v.isSet = true
}

func (v NullableLiquidityTokenChange) IsSet() bool {
	return v.isSet
}

func (v *NullableLiquidityTokenChange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLiquidityTokenChange(val *LiquidityTokenChange) *NullableLiquidityTokenChange {
	return &NullableLiquidityTokenChange{value: val, isSet: true}
}

func (v NullableLiquidityTokenChange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLiquidityTokenChange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


