/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WalletTokenInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WalletTokenInfo{}

// WalletTokenInfo struct for WalletTokenInfo
type WalletTokenInfo struct {
	Address string `json:"address"`
	Symbol string `json:"symbol"`
	Amount string `json:"amount"`
	AmountUsd string `json:"amount_usd"`
	PriceUsd string `json:"price_usd"`
}

type _WalletTokenInfo WalletTokenInfo

// NewWalletTokenInfo instantiates a new WalletTokenInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWalletTokenInfo(address string, symbol string, amount string, amountUsd string, priceUsd string) *WalletTokenInfo {
	this := WalletTokenInfo{}
	this.Address = address
	this.Symbol = symbol
	this.Amount = amount
	this.AmountUsd = amountUsd
	this.PriceUsd = priceUsd
	return &this
}

// NewWalletTokenInfoWithDefaults instantiates a new WalletTokenInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWalletTokenInfoWithDefaults() *WalletTokenInfo {
	this := WalletTokenInfo{}
	return &this
}

// GetAddress returns the Address field value
func (o *WalletTokenInfo) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *WalletTokenInfo) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *WalletTokenInfo) SetAddress(v string) {
	o.Address = v
}

// GetSymbol returns the Symbol field value
func (o *WalletTokenInfo) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *WalletTokenInfo) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *WalletTokenInfo) SetSymbol(v string) {
	o.Symbol = v
}

// GetAmount returns the Amount field value
func (o *WalletTokenInfo) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *WalletTokenInfo) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *WalletTokenInfo) SetAmount(v string) {
	o.Amount = v
}

// GetAmountUsd returns the AmountUsd field value
func (o *WalletTokenInfo) GetAmountUsd() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AmountUsd
}

// GetAmountUsdOk returns a tuple with the AmountUsd field value
// and a boolean to check if the value has been set.
func (o *WalletTokenInfo) GetAmountUsdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountUsd, true
}

// SetAmountUsd sets field value
func (o *WalletTokenInfo) SetAmountUsd(v string) {
	o.AmountUsd = v
}

// GetPriceUsd returns the PriceUsd field value
func (o *WalletTokenInfo) GetPriceUsd() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PriceUsd
}

// GetPriceUsdOk returns a tuple with the PriceUsd field value
// and a boolean to check if the value has been set.
func (o *WalletTokenInfo) GetPriceUsdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceUsd, true
}

// SetPriceUsd sets field value
func (o *WalletTokenInfo) SetPriceUsd(v string) {
	o.PriceUsd = v
}

func (o WalletTokenInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WalletTokenInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["symbol"] = o.Symbol
	toSerialize["amount"] = o.Amount
	toSerialize["amount_usd"] = o.AmountUsd
	toSerialize["price_usd"] = o.PriceUsd
	return toSerialize, nil
}

func (o *WalletTokenInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"symbol",
		"amount",
		"amount_usd",
		"price_usd",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWalletTokenInfo := _WalletTokenInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWalletTokenInfo)

	if err != nil {
		return err
	}

	*o = WalletTokenInfo(varWalletTokenInfo)

	return err
}

type NullableWalletTokenInfo struct {
	value *WalletTokenInfo
	isSet bool
}

func (v NullableWalletTokenInfo) Get() *WalletTokenInfo {
	return v.value
}

func (v *NullableWalletTokenInfo) Set(val *WalletTokenInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableWalletTokenInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableWalletTokenInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWalletTokenInfo(val *WalletTokenInfo) *NullableWalletTokenInfo {
	return &NullableWalletTokenInfo{value: val, isSet: true}
}

func (v NullableWalletTokenInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWalletTokenInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


