/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BaseToken type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseToken{}

// BaseToken struct for BaseToken
type BaseToken struct {
	Name string `json:"name"`
	Symbol string `json:"symbol"`
	Address string `json:"address"`
	ChainId int32 `json:"chain_id"`
	PriceUsd *float32 `json:"price_usd,omitempty"`
}

type _BaseToken BaseToken

// NewBaseToken instantiates a new BaseToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseToken(name string, symbol string, address string, chainId int32) *BaseToken {
	this := BaseToken{}
	this.Name = name
	this.Symbol = symbol
	this.Address = address
	this.ChainId = chainId
	return &this
}

// NewBaseTokenWithDefaults instantiates a new BaseToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseTokenWithDefaults() *BaseToken {
	this := BaseToken{}
	return &this
}

// GetName returns the Name field value
func (o *BaseToken) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BaseToken) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BaseToken) SetName(v string) {
	o.Name = v
}

// GetSymbol returns the Symbol field value
func (o *BaseToken) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *BaseToken) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *BaseToken) SetSymbol(v string) {
	o.Symbol = v
}

// GetAddress returns the Address field value
func (o *BaseToken) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *BaseToken) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *BaseToken) SetAddress(v string) {
	o.Address = v
}

// GetChainId returns the ChainId field value
func (o *BaseToken) GetChainId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *BaseToken) GetChainIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *BaseToken) SetChainId(v int32) {
	o.ChainId = v
}

// GetPriceUsd returns the PriceUsd field value if set, zero value otherwise.
func (o *BaseToken) GetPriceUsd() float32 {
	if o == nil || IsNil(o.PriceUsd) {
		var ret float32
		return ret
	}
	return *o.PriceUsd
}

// GetPriceUsdOk returns a tuple with the PriceUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseToken) GetPriceUsdOk() (*float32, bool) {
	if o == nil || IsNil(o.PriceUsd) {
		return nil, false
	}
	return o.PriceUsd, true
}

// HasPriceUsd returns a boolean if a field has been set.
func (o *BaseToken) HasPriceUsd() bool {
	if o != nil && !IsNil(o.PriceUsd) {
		return true
	}

	return false
}

// SetPriceUsd gets a reference to the given float32 and assigns it to the PriceUsd field.
func (o *BaseToken) SetPriceUsd(v float32) {
	o.PriceUsd = &v
}

func (o BaseToken) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseToken) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["symbol"] = o.Symbol
	toSerialize["address"] = o.Address
	toSerialize["chain_id"] = o.ChainId
	if !IsNil(o.PriceUsd) {
		toSerialize["price_usd"] = o.PriceUsd
	}
	return toSerialize, nil
}

func (o *BaseToken) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"symbol",
		"address",
		"chain_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBaseToken := _BaseToken{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBaseToken)

	if err != nil {
		return err
	}

	*o = BaseToken(varBaseToken)

	return err
}

type NullableBaseToken struct {
	value *BaseToken
	isSet bool
}

func (v NullableBaseToken) Get() *BaseToken {
	return v.value
}

func (v *NullableBaseToken) Set(val *BaseToken) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseToken) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseToken(val *BaseToken) *NullableBaseToken {
	return &NullableBaseToken{value: val, isSet: true}
}

func (v NullableBaseToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


