/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TokenInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenInfo{}

// TokenInfo Full token information with price and liquidity data
type TokenInfo struct {
	Name *string `json:"name,omitempty"`
	Symbol *string `json:"symbol,omitempty"`
	Address *string `json:"address,omitempty"`
	ChainId *int32 `json:"chain_id,omitempty"`
	PriceUsd *float32 `json:"price_usd,omitempty"`
	Decimals *int32 `json:"decimals,omitempty"`
	TotalSupply *float32 `json:"total_supply,omitempty"`
	TotalTvl *float32 `json:"total_tvl,omitempty"`
	MainPool *TokenInfoMainPool `json:"main_pool,omitempty"`
	// Price changes over requested time resolutions
	PriceChanges []TokenInfoPriceChangesInner `json:"price_changes,omitempty"`
}

// NewTokenInfo instantiates a new TokenInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenInfo() *TokenInfo {
	this := TokenInfo{}
	return &this
}

// NewTokenInfoWithDefaults instantiates a new TokenInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenInfoWithDefaults() *TokenInfo {
	this := TokenInfo{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TokenInfo) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfo) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TokenInfo) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TokenInfo) SetName(v string) {
	o.Name = &v
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *TokenInfo) GetSymbol() string {
	if o == nil || IsNil(o.Symbol) {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfo) GetSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.Symbol) {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *TokenInfo) HasSymbol() bool {
	if o != nil && !IsNil(o.Symbol) {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *TokenInfo) SetSymbol(v string) {
	o.Symbol = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *TokenInfo) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfo) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *TokenInfo) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *TokenInfo) SetAddress(v string) {
	o.Address = &v
}

// GetChainId returns the ChainId field value if set, zero value otherwise.
func (o *TokenInfo) GetChainId() int32 {
	if o == nil || IsNil(o.ChainId) {
		var ret int32
		return ret
	}
	return *o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfo) GetChainIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ChainId) {
		return nil, false
	}
	return o.ChainId, true
}

// HasChainId returns a boolean if a field has been set.
func (o *TokenInfo) HasChainId() bool {
	if o != nil && !IsNil(o.ChainId) {
		return true
	}

	return false
}

// SetChainId gets a reference to the given int32 and assigns it to the ChainId field.
func (o *TokenInfo) SetChainId(v int32) {
	o.ChainId = &v
}

// GetPriceUsd returns the PriceUsd field value if set, zero value otherwise.
func (o *TokenInfo) GetPriceUsd() float32 {
	if o == nil || IsNil(o.PriceUsd) {
		var ret float32
		return ret
	}
	return *o.PriceUsd
}

// GetPriceUsdOk returns a tuple with the PriceUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfo) GetPriceUsdOk() (*float32, bool) {
	if o == nil || IsNil(o.PriceUsd) {
		return nil, false
	}
	return o.PriceUsd, true
}

// HasPriceUsd returns a boolean if a field has been set.
func (o *TokenInfo) HasPriceUsd() bool {
	if o != nil && !IsNil(o.PriceUsd) {
		return true
	}

	return false
}

// SetPriceUsd gets a reference to the given float32 and assigns it to the PriceUsd field.
func (o *TokenInfo) SetPriceUsd(v float32) {
	o.PriceUsd = &v
}

// GetDecimals returns the Decimals field value if set, zero value otherwise.
func (o *TokenInfo) GetDecimals() int32 {
	if o == nil || IsNil(o.Decimals) {
		var ret int32
		return ret
	}
	return *o.Decimals
}

// GetDecimalsOk returns a tuple with the Decimals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfo) GetDecimalsOk() (*int32, bool) {
	if o == nil || IsNil(o.Decimals) {
		return nil, false
	}
	return o.Decimals, true
}

// HasDecimals returns a boolean if a field has been set.
func (o *TokenInfo) HasDecimals() bool {
	if o != nil && !IsNil(o.Decimals) {
		return true
	}

	return false
}

// SetDecimals gets a reference to the given int32 and assigns it to the Decimals field.
func (o *TokenInfo) SetDecimals(v int32) {
	o.Decimals = &v
}

// GetTotalSupply returns the TotalSupply field value if set, zero value otherwise.
func (o *TokenInfo) GetTotalSupply() float32 {
	if o == nil || IsNil(o.TotalSupply) {
		var ret float32
		return ret
	}
	return *o.TotalSupply
}

// GetTotalSupplyOk returns a tuple with the TotalSupply field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfo) GetTotalSupplyOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalSupply) {
		return nil, false
	}
	return o.TotalSupply, true
}

// HasTotalSupply returns a boolean if a field has been set.
func (o *TokenInfo) HasTotalSupply() bool {
	if o != nil && !IsNil(o.TotalSupply) {
		return true
	}

	return false
}

// SetTotalSupply gets a reference to the given float32 and assigns it to the TotalSupply field.
func (o *TokenInfo) SetTotalSupply(v float32) {
	o.TotalSupply = &v
}

// GetTotalTvl returns the TotalTvl field value if set, zero value otherwise.
func (o *TokenInfo) GetTotalTvl() float32 {
	if o == nil || IsNil(o.TotalTvl) {
		var ret float32
		return ret
	}
	return *o.TotalTvl
}

// GetTotalTvlOk returns a tuple with the TotalTvl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfo) GetTotalTvlOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalTvl) {
		return nil, false
	}
	return o.TotalTvl, true
}

// HasTotalTvl returns a boolean if a field has been set.
func (o *TokenInfo) HasTotalTvl() bool {
	if o != nil && !IsNil(o.TotalTvl) {
		return true
	}

	return false
}

// SetTotalTvl gets a reference to the given float32 and assigns it to the TotalTvl field.
func (o *TokenInfo) SetTotalTvl(v float32) {
	o.TotalTvl = &v
}

// GetMainPool returns the MainPool field value if set, zero value otherwise.
func (o *TokenInfo) GetMainPool() TokenInfoMainPool {
	if o == nil || IsNil(o.MainPool) {
		var ret TokenInfoMainPool
		return ret
	}
	return *o.MainPool
}

// GetMainPoolOk returns a tuple with the MainPool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfo) GetMainPoolOk() (*TokenInfoMainPool, bool) {
	if o == nil || IsNil(o.MainPool) {
		return nil, false
	}
	return o.MainPool, true
}

// HasMainPool returns a boolean if a field has been set.
func (o *TokenInfo) HasMainPool() bool {
	if o != nil && !IsNil(o.MainPool) {
		return true
	}

	return false
}

// SetMainPool gets a reference to the given TokenInfoMainPool and assigns it to the MainPool field.
func (o *TokenInfo) SetMainPool(v TokenInfoMainPool) {
	o.MainPool = &v
}

// GetPriceChanges returns the PriceChanges field value if set, zero value otherwise.
func (o *TokenInfo) GetPriceChanges() []TokenInfoPriceChangesInner {
	if o == nil || IsNil(o.PriceChanges) {
		var ret []TokenInfoPriceChangesInner
		return ret
	}
	return o.PriceChanges
}

// GetPriceChangesOk returns a tuple with the PriceChanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfo) GetPriceChangesOk() ([]TokenInfoPriceChangesInner, bool) {
	if o == nil || IsNil(o.PriceChanges) {
		return nil, false
	}
	return o.PriceChanges, true
}

// HasPriceChanges returns a boolean if a field has been set.
func (o *TokenInfo) HasPriceChanges() bool {
	if o != nil && !IsNil(o.PriceChanges) {
		return true
	}

	return false
}

// SetPriceChanges gets a reference to the given []TokenInfoPriceChangesInner and assigns it to the PriceChanges field.
func (o *TokenInfo) SetPriceChanges(v []TokenInfoPriceChangesInner) {
	o.PriceChanges = v
}

func (o TokenInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Symbol) {
		toSerialize["symbol"] = o.Symbol
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.ChainId) {
		toSerialize["chain_id"] = o.ChainId
	}
	if !IsNil(o.PriceUsd) {
		toSerialize["price_usd"] = o.PriceUsd
	}
	if !IsNil(o.Decimals) {
		toSerialize["decimals"] = o.Decimals
	}
	if !IsNil(o.TotalSupply) {
		toSerialize["total_supply"] = o.TotalSupply
	}
	if !IsNil(o.TotalTvl) {
		toSerialize["total_tvl"] = o.TotalTvl
	}
	if !IsNil(o.MainPool) {
		toSerialize["main_pool"] = o.MainPool
	}
	if !IsNil(o.PriceChanges) {
		toSerialize["price_changes"] = o.PriceChanges
	}
	return toSerialize, nil
}

type NullableTokenInfo struct {
	value *TokenInfo
	isSet bool
}

func (v NullableTokenInfo) Get() *TokenInfo {
	return v.value
}

func (v *NullableTokenInfo) Set(val *TokenInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenInfo(val *TokenInfo) *NullableTokenInfo {
	return &NullableTokenInfo{value: val, isSet: true}
}

func (v NullableTokenInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


