/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Token type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Token{}

// Token struct for Token
type Token struct {
	Name string `json:"name"`
	Symbol string `json:"symbol"`
	Address string `json:"address"`
	ChainId int32 `json:"chain_id"`
	PriceUsd float32 `json:"price_usd"`
	PriceNative float32 `json:"price_native"`
	Position int32 `json:"position"`
	Decimals int32 `json:"decimals"`
	Reserve float32 `json:"reserve"`
	TotalSupply float32 `json:"total_supply"`
}

type _Token Token

// NewToken instantiates a new Token object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewToken(name string, symbol string, address string, chainId int32, priceUsd float32, priceNative float32, position int32, decimals int32, reserve float32, totalSupply float32) *Token {
	this := Token{}
	this.Name = name
	this.Symbol = symbol
	this.Address = address
	this.ChainId = chainId
	this.PriceUsd = priceUsd
	this.PriceNative = priceNative
	this.Position = position
	this.Decimals = decimals
	this.Reserve = reserve
	this.TotalSupply = totalSupply
	return &this
}

// NewTokenWithDefaults instantiates a new Token object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenWithDefaults() *Token {
	this := Token{}
	return &this
}

// GetName returns the Name field value
func (o *Token) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Token) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Token) SetName(v string) {
	o.Name = v
}

// GetSymbol returns the Symbol field value
func (o *Token) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *Token) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *Token) SetSymbol(v string) {
	o.Symbol = v
}

// GetAddress returns the Address field value
func (o *Token) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *Token) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *Token) SetAddress(v string) {
	o.Address = v
}

// GetChainId returns the ChainId field value
func (o *Token) GetChainId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *Token) GetChainIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *Token) SetChainId(v int32) {
	o.ChainId = v
}

// GetPriceUsd returns the PriceUsd field value
func (o *Token) GetPriceUsd() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PriceUsd
}

// GetPriceUsdOk returns a tuple with the PriceUsd field value
// and a boolean to check if the value has been set.
func (o *Token) GetPriceUsdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceUsd, true
}

// SetPriceUsd sets field value
func (o *Token) SetPriceUsd(v float32) {
	o.PriceUsd = v
}

// GetPriceNative returns the PriceNative field value
func (o *Token) GetPriceNative() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PriceNative
}

// GetPriceNativeOk returns a tuple with the PriceNative field value
// and a boolean to check if the value has been set.
func (o *Token) GetPriceNativeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceNative, true
}

// SetPriceNative sets field value
func (o *Token) SetPriceNative(v float32) {
	o.PriceNative = v
}

// GetPosition returns the Position field value
func (o *Token) GetPosition() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Position
}

// GetPositionOk returns a tuple with the Position field value
// and a boolean to check if the value has been set.
func (o *Token) GetPositionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Position, true
}

// SetPosition sets field value
func (o *Token) SetPosition(v int32) {
	o.Position = v
}

// GetDecimals returns the Decimals field value
func (o *Token) GetDecimals() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Decimals
}

// GetDecimalsOk returns a tuple with the Decimals field value
// and a boolean to check if the value has been set.
func (o *Token) GetDecimalsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Decimals, true
}

// SetDecimals sets field value
func (o *Token) SetDecimals(v int32) {
	o.Decimals = v
}

// GetReserve returns the Reserve field value
func (o *Token) GetReserve() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Reserve
}

// GetReserveOk returns a tuple with the Reserve field value
// and a boolean to check if the value has been set.
func (o *Token) GetReserveOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reserve, true
}

// SetReserve sets field value
func (o *Token) SetReserve(v float32) {
	o.Reserve = v
}

// GetTotalSupply returns the TotalSupply field value
func (o *Token) GetTotalSupply() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalSupply
}

// GetTotalSupplyOk returns a tuple with the TotalSupply field value
// and a boolean to check if the value has been set.
func (o *Token) GetTotalSupplyOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalSupply, true
}

// SetTotalSupply sets field value
func (o *Token) SetTotalSupply(v float32) {
	o.TotalSupply = v
}

func (o Token) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Token) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["symbol"] = o.Symbol
	toSerialize["address"] = o.Address
	toSerialize["chain_id"] = o.ChainId
	toSerialize["price_usd"] = o.PriceUsd
	toSerialize["price_native"] = o.PriceNative
	toSerialize["position"] = o.Position
	toSerialize["decimals"] = o.Decimals
	toSerialize["reserve"] = o.Reserve
	toSerialize["total_supply"] = o.TotalSupply
	return toSerialize, nil
}

func (o *Token) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"symbol",
		"address",
		"chain_id",
		"price_usd",
		"price_native",
		"position",
		"decimals",
		"reserve",
		"total_supply",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varToken := _Token{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varToken)

	if err != nil {
		return err
	}

	*o = Token(varToken)

	return err
}

type NullableToken struct {
	value *Token
	isSet bool
}

func (v NullableToken) Get() *Token {
	return v.value
}

func (v *NullableToken) Set(val *Token) {
	v.value = val
	v.isSet = true
}

func (v NullableToken) IsSet() bool {
	return v.isSet
}

func (v *NullableToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToken(val *Token) *NullableToken {
	return &NullableToken{value: val, isSet: true}
}

func (v NullableToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


