/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PairOrderBookListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PairOrderBookListRequest{}

// PairOrderBookListRequest struct for PairOrderBookListRequest
type PairOrderBookListRequest struct {
	Address string `json:"address"`
	Network NetworkType `json:"network"`
	Page *int32 `json:"page,omitempty"`
	Cursor *string `json:"cursor,omitempty"`
	MakerAddress *string `json:"maker_address,omitempty"`
	OrderBy *OrderBy `json:"order_by,omitempty"`
	TxType []TxType `json:"tx_type,omitempty"`
	// timestamp in RFC3339 with UTC
	MinTimestamp *string `json:"min_timestamp,omitempty"`
	// timestamp in RFC3339 with UTC
	MaxTimestamp *string `json:"max_timestamp,omitempty"`
	Count int32 `json:"count"`
}

type _PairOrderBookListRequest PairOrderBookListRequest

// NewPairOrderBookListRequest instantiates a new PairOrderBookListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPairOrderBookListRequest(address string, network NetworkType, count int32) *PairOrderBookListRequest {
	this := PairOrderBookListRequest{}
	this.Address = address
	this.Network = network
	var page int32 = 1
	this.Page = &page
	var orderBy OrderBy = DESC
	this.OrderBy = &orderBy
	this.Count = count
	return &this
}

// NewPairOrderBookListRequestWithDefaults instantiates a new PairOrderBookListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPairOrderBookListRequestWithDefaults() *PairOrderBookListRequest {
	this := PairOrderBookListRequest{}
	var page int32 = 1
	this.Page = &page
	var orderBy OrderBy = DESC
	this.OrderBy = &orderBy
	var count int32 = 10
	this.Count = count
	return &this
}

// GetAddress returns the Address field value
func (o *PairOrderBookListRequest) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *PairOrderBookListRequest) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *PairOrderBookListRequest) SetAddress(v string) {
	o.Address = v
}

// GetNetwork returns the Network field value
func (o *PairOrderBookListRequest) GetNetwork() NetworkType {
	if o == nil {
		var ret NetworkType
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *PairOrderBookListRequest) GetNetworkOk() (*NetworkType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *PairOrderBookListRequest) SetNetwork(v NetworkType) {
	o.Network = v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *PairOrderBookListRequest) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairOrderBookListRequest) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *PairOrderBookListRequest) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *PairOrderBookListRequest) SetPage(v int32) {
	o.Page = &v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *PairOrderBookListRequest) GetCursor() string {
	if o == nil || IsNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairOrderBookListRequest) GetCursorOk() (*string, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *PairOrderBookListRequest) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *PairOrderBookListRequest) SetCursor(v string) {
	o.Cursor = &v
}

// GetMakerAddress returns the MakerAddress field value if set, zero value otherwise.
func (o *PairOrderBookListRequest) GetMakerAddress() string {
	if o == nil || IsNil(o.MakerAddress) {
		var ret string
		return ret
	}
	return *o.MakerAddress
}

// GetMakerAddressOk returns a tuple with the MakerAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairOrderBookListRequest) GetMakerAddressOk() (*string, bool) {
	if o == nil || IsNil(o.MakerAddress) {
		return nil, false
	}
	return o.MakerAddress, true
}

// HasMakerAddress returns a boolean if a field has been set.
func (o *PairOrderBookListRequest) HasMakerAddress() bool {
	if o != nil && !IsNil(o.MakerAddress) {
		return true
	}

	return false
}

// SetMakerAddress gets a reference to the given string and assigns it to the MakerAddress field.
func (o *PairOrderBookListRequest) SetMakerAddress(v string) {
	o.MakerAddress = &v
}

// GetOrderBy returns the OrderBy field value if set, zero value otherwise.
func (o *PairOrderBookListRequest) GetOrderBy() OrderBy {
	if o == nil || IsNil(o.OrderBy) {
		var ret OrderBy
		return ret
	}
	return *o.OrderBy
}

// GetOrderByOk returns a tuple with the OrderBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairOrderBookListRequest) GetOrderByOk() (*OrderBy, bool) {
	if o == nil || IsNil(o.OrderBy) {
		return nil, false
	}
	return o.OrderBy, true
}

// HasOrderBy returns a boolean if a field has been set.
func (o *PairOrderBookListRequest) HasOrderBy() bool {
	if o != nil && !IsNil(o.OrderBy) {
		return true
	}

	return false
}

// SetOrderBy gets a reference to the given OrderBy and assigns it to the OrderBy field.
func (o *PairOrderBookListRequest) SetOrderBy(v OrderBy) {
	o.OrderBy = &v
}

// GetTxType returns the TxType field value if set, zero value otherwise.
func (o *PairOrderBookListRequest) GetTxType() []TxType {
	if o == nil || IsNil(o.TxType) {
		var ret []TxType
		return ret
	}
	return o.TxType
}

// GetTxTypeOk returns a tuple with the TxType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairOrderBookListRequest) GetTxTypeOk() ([]TxType, bool) {
	if o == nil || IsNil(o.TxType) {
		return nil, false
	}
	return o.TxType, true
}

// HasTxType returns a boolean if a field has been set.
func (o *PairOrderBookListRequest) HasTxType() bool {
	if o != nil && !IsNil(o.TxType) {
		return true
	}

	return false
}

// SetTxType gets a reference to the given []TxType and assigns it to the TxType field.
func (o *PairOrderBookListRequest) SetTxType(v []TxType) {
	o.TxType = v
}

// GetMinTimestamp returns the MinTimestamp field value if set, zero value otherwise.
func (o *PairOrderBookListRequest) GetMinTimestamp() string {
	if o == nil || IsNil(o.MinTimestamp) {
		var ret string
		return ret
	}
	return *o.MinTimestamp
}

// GetMinTimestampOk returns a tuple with the MinTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairOrderBookListRequest) GetMinTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.MinTimestamp) {
		return nil, false
	}
	return o.MinTimestamp, true
}

// HasMinTimestamp returns a boolean if a field has been set.
func (o *PairOrderBookListRequest) HasMinTimestamp() bool {
	if o != nil && !IsNil(o.MinTimestamp) {
		return true
	}

	return false
}

// SetMinTimestamp gets a reference to the given string and assigns it to the MinTimestamp field.
func (o *PairOrderBookListRequest) SetMinTimestamp(v string) {
	o.MinTimestamp = &v
}

// GetMaxTimestamp returns the MaxTimestamp field value if set, zero value otherwise.
func (o *PairOrderBookListRequest) GetMaxTimestamp() string {
	if o == nil || IsNil(o.MaxTimestamp) {
		var ret string
		return ret
	}
	return *o.MaxTimestamp
}

// GetMaxTimestampOk returns a tuple with the MaxTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairOrderBookListRequest) GetMaxTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.MaxTimestamp) {
		return nil, false
	}
	return o.MaxTimestamp, true
}

// HasMaxTimestamp returns a boolean if a field has been set.
func (o *PairOrderBookListRequest) HasMaxTimestamp() bool {
	if o != nil && !IsNil(o.MaxTimestamp) {
		return true
	}

	return false
}

// SetMaxTimestamp gets a reference to the given string and assigns it to the MaxTimestamp field.
func (o *PairOrderBookListRequest) SetMaxTimestamp(v string) {
	o.MaxTimestamp = &v
}

// GetCount returns the Count field value
func (o *PairOrderBookListRequest) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *PairOrderBookListRequest) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *PairOrderBookListRequest) SetCount(v int32) {
	o.Count = v
}

func (o PairOrderBookListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PairOrderBookListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["network"] = o.Network
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	if !IsNil(o.MakerAddress) {
		toSerialize["maker_address"] = o.MakerAddress
	}
	if !IsNil(o.OrderBy) {
		toSerialize["order_by"] = o.OrderBy
	}
	if !IsNil(o.TxType) {
		toSerialize["tx_type"] = o.TxType
	}
	if !IsNil(o.MinTimestamp) {
		toSerialize["min_timestamp"] = o.MinTimestamp
	}
	if !IsNil(o.MaxTimestamp) {
		toSerialize["max_timestamp"] = o.MaxTimestamp
	}
	toSerialize["count"] = o.Count
	return toSerialize, nil
}

func (o *PairOrderBookListRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"network",
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPairOrderBookListRequest := _PairOrderBookListRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPairOrderBookListRequest)

	if err != nil {
		return err
	}

	*o = PairOrderBookListRequest(varPairOrderBookListRequest)

	return err
}

type NullablePairOrderBookListRequest struct {
	value *PairOrderBookListRequest
	isSet bool
}

func (v NullablePairOrderBookListRequest) Get() *PairOrderBookListRequest {
	return v.value
}

func (v *NullablePairOrderBookListRequest) Set(val *PairOrderBookListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePairOrderBookListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePairOrderBookListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePairOrderBookListRequest(val *PairOrderBookListRequest) *NullablePairOrderBookListRequest {
	return &NullablePairOrderBookListRequest{value: val, isSet: true}
}

func (v NullablePairOrderBookListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePairOrderBookListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


