/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NftCollectionOrderBookListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NftCollectionOrderBookListRequest{}

// NftCollectionOrderBookListRequest struct for NftCollectionOrderBookListRequest
type NftCollectionOrderBookListRequest struct {
	Address string `json:"address"`
	Network NetworkType `json:"network"`
	Cursor *string `json:"cursor,omitempty"`
	Count int32 `json:"count"`
}

type _NftCollectionOrderBookListRequest NftCollectionOrderBookListRequest

// NewNftCollectionOrderBookListRequest instantiates a new NftCollectionOrderBookListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNftCollectionOrderBookListRequest(address string, network NetworkType, count int32) *NftCollectionOrderBookListRequest {
	this := NftCollectionOrderBookListRequest{}
	this.Address = address
	this.Network = network
	this.Count = count
	return &this
}

// NewNftCollectionOrderBookListRequestWithDefaults instantiates a new NftCollectionOrderBookListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNftCollectionOrderBookListRequestWithDefaults() *NftCollectionOrderBookListRequest {
	this := NftCollectionOrderBookListRequest{}
	var count int32 = 10
	this.Count = count
	return &this
}

// GetAddress returns the Address field value
func (o *NftCollectionOrderBookListRequest) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *NftCollectionOrderBookListRequest) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *NftCollectionOrderBookListRequest) SetAddress(v string) {
	o.Address = v
}

// GetNetwork returns the Network field value
func (o *NftCollectionOrderBookListRequest) GetNetwork() NetworkType {
	if o == nil {
		var ret NetworkType
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *NftCollectionOrderBookListRequest) GetNetworkOk() (*NetworkType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *NftCollectionOrderBookListRequest) SetNetwork(v NetworkType) {
	o.Network = v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *NftCollectionOrderBookListRequest) GetCursor() string {
	if o == nil || IsNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftCollectionOrderBookListRequest) GetCursorOk() (*string, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *NftCollectionOrderBookListRequest) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *NftCollectionOrderBookListRequest) SetCursor(v string) {
	o.Cursor = &v
}

// GetCount returns the Count field value
func (o *NftCollectionOrderBookListRequest) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *NftCollectionOrderBookListRequest) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *NftCollectionOrderBookListRequest) SetCount(v int32) {
	o.Count = v
}

func (o NftCollectionOrderBookListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NftCollectionOrderBookListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["network"] = o.Network
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	toSerialize["count"] = o.Count
	return toSerialize, nil
}

func (o *NftCollectionOrderBookListRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"network",
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNftCollectionOrderBookListRequest := _NftCollectionOrderBookListRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNftCollectionOrderBookListRequest)

	if err != nil {
		return err
	}

	*o = NftCollectionOrderBookListRequest(varNftCollectionOrderBookListRequest)

	return err
}

type NullableNftCollectionOrderBookListRequest struct {
	value *NftCollectionOrderBookListRequest
	isSet bool
}

func (v NullableNftCollectionOrderBookListRequest) Get() *NftCollectionOrderBookListRequest {
	return v.value
}

func (v *NullableNftCollectionOrderBookListRequest) Set(val *NftCollectionOrderBookListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNftCollectionOrderBookListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNftCollectionOrderBookListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNftCollectionOrderBookListRequest(val *NftCollectionOrderBookListRequest) *NullableNftCollectionOrderBookListRequest {
	return &NullableNftCollectionOrderBookListRequest{value: val, isSet: true}
}

func (v NullableNftCollectionOrderBookListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNftCollectionOrderBookListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


