/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NftCollectionOrderBookList200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NftCollectionOrderBookList200Response{}

// NftCollectionOrderBookList200Response struct for NftCollectionOrderBookList200Response
type NftCollectionOrderBookList200Response struct {
	Items []NftTransaction `json:"items"`
	NextCursor *string `json:"nextCursor,omitempty"`
	BackCursor *string `json:"backCursor,omitempty"`
}

type _NftCollectionOrderBookList200Response NftCollectionOrderBookList200Response

// NewNftCollectionOrderBookList200Response instantiates a new NftCollectionOrderBookList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNftCollectionOrderBookList200Response(items []NftTransaction) *NftCollectionOrderBookList200Response {
	this := NftCollectionOrderBookList200Response{}
	this.Items = items
	return &this
}

// NewNftCollectionOrderBookList200ResponseWithDefaults instantiates a new NftCollectionOrderBookList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNftCollectionOrderBookList200ResponseWithDefaults() *NftCollectionOrderBookList200Response {
	this := NftCollectionOrderBookList200Response{}
	return &this
}

// GetItems returns the Items field value
func (o *NftCollectionOrderBookList200Response) GetItems() []NftTransaction {
	if o == nil {
		var ret []NftTransaction
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *NftCollectionOrderBookList200Response) GetItemsOk() ([]NftTransaction, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *NftCollectionOrderBookList200Response) SetItems(v []NftTransaction) {
	o.Items = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *NftCollectionOrderBookList200Response) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftCollectionOrderBookList200Response) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *NftCollectionOrderBookList200Response) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *NftCollectionOrderBookList200Response) SetNextCursor(v string) {
	o.NextCursor = &v
}

// GetBackCursor returns the BackCursor field value if set, zero value otherwise.
func (o *NftCollectionOrderBookList200Response) GetBackCursor() string {
	if o == nil || IsNil(o.BackCursor) {
		var ret string
		return ret
	}
	return *o.BackCursor
}

// GetBackCursorOk returns a tuple with the BackCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftCollectionOrderBookList200Response) GetBackCursorOk() (*string, bool) {
	if o == nil || IsNil(o.BackCursor) {
		return nil, false
	}
	return o.BackCursor, true
}

// HasBackCursor returns a boolean if a field has been set.
func (o *NftCollectionOrderBookList200Response) HasBackCursor() bool {
	if o != nil && !IsNil(o.BackCursor) {
		return true
	}

	return false
}

// SetBackCursor gets a reference to the given string and assigns it to the BackCursor field.
func (o *NftCollectionOrderBookList200Response) SetBackCursor(v string) {
	o.BackCursor = &v
}

func (o NftCollectionOrderBookList200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NftCollectionOrderBookList200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	if !IsNil(o.NextCursor) {
		toSerialize["nextCursor"] = o.NextCursor
	}
	if !IsNil(o.BackCursor) {
		toSerialize["backCursor"] = o.BackCursor
	}
	return toSerialize, nil
}

func (o *NftCollectionOrderBookList200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNftCollectionOrderBookList200Response := _NftCollectionOrderBookList200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNftCollectionOrderBookList200Response)

	if err != nil {
		return err
	}

	*o = NftCollectionOrderBookList200Response(varNftCollectionOrderBookList200Response)

	return err
}

type NullableNftCollectionOrderBookList200Response struct {
	value *NftCollectionOrderBookList200Response
	isSet bool
}

func (v NullableNftCollectionOrderBookList200Response) Get() *NftCollectionOrderBookList200Response {
	return v.value
}

func (v *NullableNftCollectionOrderBookList200Response) Set(val *NftCollectionOrderBookList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableNftCollectionOrderBookList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableNftCollectionOrderBookList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNftCollectionOrderBookList200Response(val *NftCollectionOrderBookList200Response) *NullableNftCollectionOrderBookList200Response {
	return &NullableNftCollectionOrderBookList200Response{value: val, isSet: true}
}

func (v NullableNftCollectionOrderBookList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNftCollectionOrderBookList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


