/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NftTransaction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NftTransaction{}

// NftTransaction struct for NftTransaction
type NftTransaction struct {
	Timestamp string `json:"timestamp"`
	Hash string `json:"hash"`
	FromAddress string `json:"from_address"`
	ToAddress string `json:"to_address"`
	Address string `json:"address"`
	TokenId string `json:"token_id"`
	EventType string `json:"event_type"`
	BlockNumber int32 `json:"block_number"`
	ChainId int32 `json:"chain_id"`
}

type _NftTransaction NftTransaction

// NewNftTransaction instantiates a new NftTransaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNftTransaction(timestamp string, hash string, fromAddress string, toAddress string, address string, tokenId string, eventType string, blockNumber int32, chainId int32) *NftTransaction {
	this := NftTransaction{}
	this.Timestamp = timestamp
	this.Hash = hash
	this.FromAddress = fromAddress
	this.ToAddress = toAddress
	this.Address = address
	this.TokenId = tokenId
	this.EventType = eventType
	this.BlockNumber = blockNumber
	this.ChainId = chainId
	return &this
}

// NewNftTransactionWithDefaults instantiates a new NftTransaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNftTransactionWithDefaults() *NftTransaction {
	this := NftTransaction{}
	return &this
}

// GetTimestamp returns the Timestamp field value
func (o *NftTransaction) GetTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *NftTransaction) GetTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *NftTransaction) SetTimestamp(v string) {
	o.Timestamp = v
}

// GetHash returns the Hash field value
func (o *NftTransaction) GetHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hash
}

// GetHashOk returns a tuple with the Hash field value
// and a boolean to check if the value has been set.
func (o *NftTransaction) GetHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hash, true
}

// SetHash sets field value
func (o *NftTransaction) SetHash(v string) {
	o.Hash = v
}

// GetFromAddress returns the FromAddress field value
func (o *NftTransaction) GetFromAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FromAddress
}

// GetFromAddressOk returns a tuple with the FromAddress field value
// and a boolean to check if the value has been set.
func (o *NftTransaction) GetFromAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromAddress, true
}

// SetFromAddress sets field value
func (o *NftTransaction) SetFromAddress(v string) {
	o.FromAddress = v
}

// GetToAddress returns the ToAddress field value
func (o *NftTransaction) GetToAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToAddress
}

// GetToAddressOk returns a tuple with the ToAddress field value
// and a boolean to check if the value has been set.
func (o *NftTransaction) GetToAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToAddress, true
}

// SetToAddress sets field value
func (o *NftTransaction) SetToAddress(v string) {
	o.ToAddress = v
}

// GetAddress returns the Address field value
func (o *NftTransaction) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *NftTransaction) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *NftTransaction) SetAddress(v string) {
	o.Address = v
}

// GetTokenId returns the TokenId field value
func (o *NftTransaction) GetTokenId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value
// and a boolean to check if the value has been set.
func (o *NftTransaction) GetTokenIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenId, true
}

// SetTokenId sets field value
func (o *NftTransaction) SetTokenId(v string) {
	o.TokenId = v
}

// GetEventType returns the EventType field value
func (o *NftTransaction) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *NftTransaction) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *NftTransaction) SetEventType(v string) {
	o.EventType = v
}

// GetBlockNumber returns the BlockNumber field value
func (o *NftTransaction) GetBlockNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BlockNumber
}

// GetBlockNumberOk returns a tuple with the BlockNumber field value
// and a boolean to check if the value has been set.
func (o *NftTransaction) GetBlockNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlockNumber, true
}

// SetBlockNumber sets field value
func (o *NftTransaction) SetBlockNumber(v int32) {
	o.BlockNumber = v
}

// GetChainId returns the ChainId field value
func (o *NftTransaction) GetChainId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *NftTransaction) GetChainIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *NftTransaction) SetChainId(v int32) {
	o.ChainId = v
}

func (o NftTransaction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NftTransaction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["hash"] = o.Hash
	toSerialize["from_address"] = o.FromAddress
	toSerialize["to_address"] = o.ToAddress
	toSerialize["address"] = o.Address
	toSerialize["token_id"] = o.TokenId
	toSerialize["event_type"] = o.EventType
	toSerialize["block_number"] = o.BlockNumber
	toSerialize["chain_id"] = o.ChainId
	return toSerialize, nil
}

func (o *NftTransaction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"timestamp",
		"hash",
		"from_address",
		"to_address",
		"address",
		"token_id",
		"event_type",
		"block_number",
		"chain_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNftTransaction := _NftTransaction{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNftTransaction)

	if err != nil {
		return err
	}

	*o = NftTransaction(varNftTransaction)

	return err
}

type NullableNftTransaction struct {
	value *NftTransaction
	isSet bool
}

func (v NullableNftTransaction) Get() *NftTransaction {
	return v.value
}

func (v *NullableNftTransaction) Set(val *NftTransaction) {
	v.value = val
	v.isSet = true
}

func (v NullableNftTransaction) IsSet() bool {
	return v.isSet
}

func (v *NullableNftTransaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNftTransaction(val *NftTransaction) *NullableNftTransaction {
	return &NullableNftTransaction{value: val, isSet: true}
}

func (v NullableNftTransaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNftTransaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


