/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FarmInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FarmInfo{}

// FarmInfo struct for FarmInfo
type FarmInfo struct {
	Network Network `json:"network"`
	Address string `json:"address"`
	Pid int64 `json:"pid"`
	Ticker string `json:"ticker"`
	Tvl string `json:"tvl"`
	RewardToken BaseToken `json:"reward_token"`
	AprYear Apr `json:"apr_year"`
	AprDaily Apr `json:"apr_daily"`
	UpdatedAt string `json:"updated_at"`
}

type _FarmInfo FarmInfo

// NewFarmInfo instantiates a new FarmInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFarmInfo(network Network, address string, pid int64, ticker string, tvl string, rewardToken BaseToken, aprYear Apr, aprDaily Apr, updatedAt string) *FarmInfo {
	this := FarmInfo{}
	this.Network = network
	this.Address = address
	this.Pid = pid
	this.Ticker = ticker
	this.Tvl = tvl
	this.RewardToken = rewardToken
	this.AprYear = aprYear
	this.AprDaily = aprDaily
	this.UpdatedAt = updatedAt
	return &this
}

// NewFarmInfoWithDefaults instantiates a new FarmInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFarmInfoWithDefaults() *FarmInfo {
	this := FarmInfo{}
	return &this
}

// GetNetwork returns the Network field value
func (o *FarmInfo) GetNetwork() Network {
	if o == nil {
		var ret Network
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *FarmInfo) GetNetworkOk() (*Network, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *FarmInfo) SetNetwork(v Network) {
	o.Network = v
}

// GetAddress returns the Address field value
func (o *FarmInfo) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *FarmInfo) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *FarmInfo) SetAddress(v string) {
	o.Address = v
}

// GetPid returns the Pid field value
func (o *FarmInfo) GetPid() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Pid
}

// GetPidOk returns a tuple with the Pid field value
// and a boolean to check if the value has been set.
func (o *FarmInfo) GetPidOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pid, true
}

// SetPid sets field value
func (o *FarmInfo) SetPid(v int64) {
	o.Pid = v
}

// GetTicker returns the Ticker field value
func (o *FarmInfo) GetTicker() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ticker
}

// GetTickerOk returns a tuple with the Ticker field value
// and a boolean to check if the value has been set.
func (o *FarmInfo) GetTickerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ticker, true
}

// SetTicker sets field value
func (o *FarmInfo) SetTicker(v string) {
	o.Ticker = v
}

// GetTvl returns the Tvl field value
func (o *FarmInfo) GetTvl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tvl
}

// GetTvlOk returns a tuple with the Tvl field value
// and a boolean to check if the value has been set.
func (o *FarmInfo) GetTvlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tvl, true
}

// SetTvl sets field value
func (o *FarmInfo) SetTvl(v string) {
	o.Tvl = v
}

// GetRewardToken returns the RewardToken field value
func (o *FarmInfo) GetRewardToken() BaseToken {
	if o == nil {
		var ret BaseToken
		return ret
	}

	return o.RewardToken
}

// GetRewardTokenOk returns a tuple with the RewardToken field value
// and a boolean to check if the value has been set.
func (o *FarmInfo) GetRewardTokenOk() (*BaseToken, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RewardToken, true
}

// SetRewardToken sets field value
func (o *FarmInfo) SetRewardToken(v BaseToken) {
	o.RewardToken = v
}

// GetAprYear returns the AprYear field value
func (o *FarmInfo) GetAprYear() Apr {
	if o == nil {
		var ret Apr
		return ret
	}

	return o.AprYear
}

// GetAprYearOk returns a tuple with the AprYear field value
// and a boolean to check if the value has been set.
func (o *FarmInfo) GetAprYearOk() (*Apr, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AprYear, true
}

// SetAprYear sets field value
func (o *FarmInfo) SetAprYear(v Apr) {
	o.AprYear = v
}

// GetAprDaily returns the AprDaily field value
func (o *FarmInfo) GetAprDaily() Apr {
	if o == nil {
		var ret Apr
		return ret
	}

	return o.AprDaily
}

// GetAprDailyOk returns a tuple with the AprDaily field value
// and a boolean to check if the value has been set.
func (o *FarmInfo) GetAprDailyOk() (*Apr, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AprDaily, true
}

// SetAprDaily sets field value
func (o *FarmInfo) SetAprDaily(v Apr) {
	o.AprDaily = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *FarmInfo) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *FarmInfo) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *FarmInfo) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o FarmInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FarmInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["network"] = o.Network
	toSerialize["address"] = o.Address
	toSerialize["pid"] = o.Pid
	toSerialize["ticker"] = o.Ticker
	toSerialize["tvl"] = o.Tvl
	toSerialize["reward_token"] = o.RewardToken
	toSerialize["apr_year"] = o.AprYear
	toSerialize["apr_daily"] = o.AprDaily
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *FarmInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"network",
		"address",
		"pid",
		"ticker",
		"tvl",
		"reward_token",
		"apr_year",
		"apr_daily",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFarmInfo := _FarmInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFarmInfo)

	if err != nil {
		return err
	}

	*o = FarmInfo(varFarmInfo)

	return err
}

type NullableFarmInfo struct {
	value *FarmInfo
	isSet bool
}

func (v NullableFarmInfo) Get() *FarmInfo {
	return v.value
}

func (v *NullableFarmInfo) Set(val *FarmInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableFarmInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableFarmInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFarmInfo(val *FarmInfo) *NullableFarmInfo {
	return &NullableFarmInfo{value: val, isSet: true}
}

func (v NullableFarmInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFarmInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


