/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TokenInfoRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenInfoRequest{}

// TokenInfoRequest struct for TokenInfoRequest
type TokenInfoRequest struct {
	Address string `json:"address"`
	Network NetworkType `json:"network"`
	// Optional list of time resolutions for price changes
	Res []ResolutionType `json:"res,omitempty"`
}

type _TokenInfoRequest TokenInfoRequest

// NewTokenInfoRequest instantiates a new TokenInfoRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenInfoRequest(address string, network NetworkType) *TokenInfoRequest {
	this := TokenInfoRequest{}
	this.Address = address
	this.Network = network
	return &this
}

// NewTokenInfoRequestWithDefaults instantiates a new TokenInfoRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenInfoRequestWithDefaults() *TokenInfoRequest {
	this := TokenInfoRequest{}
	return &this
}

// GetAddress returns the Address field value
func (o *TokenInfoRequest) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *TokenInfoRequest) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *TokenInfoRequest) SetAddress(v string) {
	o.Address = v
}

// GetNetwork returns the Network field value
func (o *TokenInfoRequest) GetNetwork() NetworkType {
	if o == nil {
		var ret NetworkType
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *TokenInfoRequest) GetNetworkOk() (*NetworkType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *TokenInfoRequest) SetNetwork(v NetworkType) {
	o.Network = v
}

// GetRes returns the Res field value if set, zero value otherwise.
func (o *TokenInfoRequest) GetRes() []ResolutionType {
	if o == nil || IsNil(o.Res) {
		var ret []ResolutionType
		return ret
	}
	return o.Res
}

// GetResOk returns a tuple with the Res field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfoRequest) GetResOk() ([]ResolutionType, bool) {
	if o == nil || IsNil(o.Res) {
		return nil, false
	}
	return o.Res, true
}

// HasRes returns a boolean if a field has been set.
func (o *TokenInfoRequest) HasRes() bool {
	if o != nil && !IsNil(o.Res) {
		return true
	}

	return false
}

// SetRes gets a reference to the given []ResolutionType and assigns it to the Res field.
func (o *TokenInfoRequest) SetRes(v []ResolutionType) {
	o.Res = v
}

func (o TokenInfoRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenInfoRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["network"] = o.Network
	if !IsNil(o.Res) {
		toSerialize["res"] = o.Res
	}
	return toSerialize, nil
}

func (o *TokenInfoRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"network",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenInfoRequest := _TokenInfoRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokenInfoRequest)

	if err != nil {
		return err
	}

	*o = TokenInfoRequest(varTokenInfoRequest)

	return err
}

type NullableTokenInfoRequest struct {
	value *TokenInfoRequest
	isSet bool
}

func (v NullableTokenInfoRequest) Get() *TokenInfoRequest {
	return v.value
}

func (v *NullableTokenInfoRequest) Set(val *TokenInfoRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenInfoRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenInfoRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenInfoRequest(val *TokenInfoRequest) *NullableTokenInfoRequest {
	return &NullableTokenInfoRequest{value: val, isSet: true}
}

func (v NullableTokenInfoRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenInfoRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


