/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Transaction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Transaction{}

// Transaction struct for Transaction
type Transaction struct {
	Timestamp string `json:"timestamp"`
	Hash string `json:"hash"`
	ChainId int32 `json:"chain_id"`
	MakerAddress string `json:"maker_address"`
	FromAddress string `json:"from_address"`
	ToAddress string `json:"to_address"`
	TxType TxType `json:"tx_type"`
	BlockInfo TransactionBlockInfo `json:"block_info"`
	EventData TransactionEventData `json:"event_data"`
}

type _Transaction Transaction

// NewTransaction instantiates a new Transaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransaction(timestamp string, hash string, chainId int32, makerAddress string, fromAddress string, toAddress string, txType TxType, blockInfo TransactionBlockInfo, eventData TransactionEventData) *Transaction {
	this := Transaction{}
	this.Timestamp = timestamp
	this.Hash = hash
	this.ChainId = chainId
	this.MakerAddress = makerAddress
	this.FromAddress = fromAddress
	this.ToAddress = toAddress
	this.TxType = txType
	this.BlockInfo = blockInfo
	this.EventData = eventData
	return &this
}

// NewTransactionWithDefaults instantiates a new Transaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionWithDefaults() *Transaction {
	this := Transaction{}
	var txType TxType = ALL
	this.TxType = txType
	return &this
}

// GetTimestamp returns the Timestamp field value
func (o *Transaction) GetTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *Transaction) SetTimestamp(v string) {
	o.Timestamp = v
}

// GetHash returns the Hash field value
func (o *Transaction) GetHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hash
}

// GetHashOk returns a tuple with the Hash field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hash, true
}

// SetHash sets field value
func (o *Transaction) SetHash(v string) {
	o.Hash = v
}

// GetChainId returns the ChainId field value
func (o *Transaction) GetChainId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetChainIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *Transaction) SetChainId(v int32) {
	o.ChainId = v
}

// GetMakerAddress returns the MakerAddress field value
func (o *Transaction) GetMakerAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MakerAddress
}

// GetMakerAddressOk returns a tuple with the MakerAddress field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetMakerAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MakerAddress, true
}

// SetMakerAddress sets field value
func (o *Transaction) SetMakerAddress(v string) {
	o.MakerAddress = v
}

// GetFromAddress returns the FromAddress field value
func (o *Transaction) GetFromAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FromAddress
}

// GetFromAddressOk returns a tuple with the FromAddress field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetFromAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromAddress, true
}

// SetFromAddress sets field value
func (o *Transaction) SetFromAddress(v string) {
	o.FromAddress = v
}

// GetToAddress returns the ToAddress field value
func (o *Transaction) GetToAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToAddress
}

// GetToAddressOk returns a tuple with the ToAddress field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetToAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToAddress, true
}

// SetToAddress sets field value
func (o *Transaction) SetToAddress(v string) {
	o.ToAddress = v
}

// GetTxType returns the TxType field value
func (o *Transaction) GetTxType() TxType {
	if o == nil {
		var ret TxType
		return ret
	}

	return o.TxType
}

// GetTxTypeOk returns a tuple with the TxType field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetTxTypeOk() (*TxType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxType, true
}

// SetTxType sets field value
func (o *Transaction) SetTxType(v TxType) {
	o.TxType = v
}

// GetBlockInfo returns the BlockInfo field value
func (o *Transaction) GetBlockInfo() TransactionBlockInfo {
	if o == nil {
		var ret TransactionBlockInfo
		return ret
	}

	return o.BlockInfo
}

// GetBlockInfoOk returns a tuple with the BlockInfo field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetBlockInfoOk() (*TransactionBlockInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlockInfo, true
}

// SetBlockInfo sets field value
func (o *Transaction) SetBlockInfo(v TransactionBlockInfo) {
	o.BlockInfo = v
}

// GetEventData returns the EventData field value
func (o *Transaction) GetEventData() TransactionEventData {
	if o == nil {
		var ret TransactionEventData
		return ret
	}

	return o.EventData
}

// GetEventDataOk returns a tuple with the EventData field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetEventDataOk() (*TransactionEventData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventData, true
}

// SetEventData sets field value
func (o *Transaction) SetEventData(v TransactionEventData) {
	o.EventData = v
}

func (o Transaction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Transaction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["hash"] = o.Hash
	toSerialize["chain_id"] = o.ChainId
	toSerialize["maker_address"] = o.MakerAddress
	toSerialize["from_address"] = o.FromAddress
	toSerialize["to_address"] = o.ToAddress
	toSerialize["tx_type"] = o.TxType
	toSerialize["block_info"] = o.BlockInfo
	toSerialize["event_data"] = o.EventData
	return toSerialize, nil
}

func (o *Transaction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"timestamp",
		"hash",
		"chain_id",
		"maker_address",
		"from_address",
		"to_address",
		"tx_type",
		"block_info",
		"event_data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransaction := _Transaction{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransaction)

	if err != nil {
		return err
	}

	*o = Transaction(varTransaction)

	return err
}

type NullableTransaction struct {
	value *Transaction
	isSet bool
}

func (v NullableTransaction) Get() *Transaction {
	return v.value
}

func (v *NullableTransaction) Set(val *Transaction) {
	v.value = val
	v.isSet = true
}

func (v NullableTransaction) IsSet() bool {
	return v.isSet
}

func (v *NullableTransaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransaction(val *Transaction) *NullableTransaction {
	return &NullableTransaction{value: val, isSet: true}
}

func (v NullableTransaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


