/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdatePairsStatusRequestPairsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePairsStatusRequestPairsInner{}

// UpdatePairsStatusRequestPairsInner struct for UpdatePairsStatusRequestPairsInner
type UpdatePairsStatusRequestPairsInner struct {
	Address string `json:"address"`
	ChainId int32 `json:"chain_id"`
	NewStatus PairState `json:"new_status"`
	Reason string `json:"reason"`
}

type _UpdatePairsStatusRequestPairsInner UpdatePairsStatusRequestPairsInner

// NewUpdatePairsStatusRequestPairsInner instantiates a new UpdatePairsStatusRequestPairsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePairsStatusRequestPairsInner(address string, chainId int32, newStatus PairState, reason string) *UpdatePairsStatusRequestPairsInner {
	this := UpdatePairsStatusRequestPairsInner{}
	this.Address = address
	this.ChainId = chainId
	this.NewStatus = newStatus
	this.Reason = reason
	return &this
}

// NewUpdatePairsStatusRequestPairsInnerWithDefaults instantiates a new UpdatePairsStatusRequestPairsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePairsStatusRequestPairsInnerWithDefaults() *UpdatePairsStatusRequestPairsInner {
	this := UpdatePairsStatusRequestPairsInner{}
	return &this
}

// GetAddress returns the Address field value
func (o *UpdatePairsStatusRequestPairsInner) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *UpdatePairsStatusRequestPairsInner) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *UpdatePairsStatusRequestPairsInner) SetAddress(v string) {
	o.Address = v
}

// GetChainId returns the ChainId field value
func (o *UpdatePairsStatusRequestPairsInner) GetChainId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *UpdatePairsStatusRequestPairsInner) GetChainIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *UpdatePairsStatusRequestPairsInner) SetChainId(v int32) {
	o.ChainId = v
}

// GetNewStatus returns the NewStatus field value
func (o *UpdatePairsStatusRequestPairsInner) GetNewStatus() PairState {
	if o == nil {
		var ret PairState
		return ret
	}

	return o.NewStatus
}

// GetNewStatusOk returns a tuple with the NewStatus field value
// and a boolean to check if the value has been set.
func (o *UpdatePairsStatusRequestPairsInner) GetNewStatusOk() (*PairState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewStatus, true
}

// SetNewStatus sets field value
func (o *UpdatePairsStatusRequestPairsInner) SetNewStatus(v PairState) {
	o.NewStatus = v
}

// GetReason returns the Reason field value
func (o *UpdatePairsStatusRequestPairsInner) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *UpdatePairsStatusRequestPairsInner) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *UpdatePairsStatusRequestPairsInner) SetReason(v string) {
	o.Reason = v
}

func (o UpdatePairsStatusRequestPairsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePairsStatusRequestPairsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["chain_id"] = o.ChainId
	toSerialize["new_status"] = o.NewStatus
	toSerialize["reason"] = o.Reason
	return toSerialize, nil
}

func (o *UpdatePairsStatusRequestPairsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"chain_id",
		"new_status",
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdatePairsStatusRequestPairsInner := _UpdatePairsStatusRequestPairsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdatePairsStatusRequestPairsInner)

	if err != nil {
		return err
	}

	*o = UpdatePairsStatusRequestPairsInner(varUpdatePairsStatusRequestPairsInner)

	return err
}

type NullableUpdatePairsStatusRequestPairsInner struct {
	value *UpdatePairsStatusRequestPairsInner
	isSet bool
}

func (v NullableUpdatePairsStatusRequestPairsInner) Get() *UpdatePairsStatusRequestPairsInner {
	return v.value
}

func (v *NullableUpdatePairsStatusRequestPairsInner) Set(val *UpdatePairsStatusRequestPairsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePairsStatusRequestPairsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePairsStatusRequestPairsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePairsStatusRequestPairsInner(val *UpdatePairsStatusRequestPairsInner) *NullableUpdatePairsStatusRequestPairsInner {
	return &NullableUpdatePairsStatusRequestPairsInner{value: val, isSet: true}
}

func (v NullableUpdatePairsStatusRequestPairsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePairsStatusRequestPairsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


