/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ResolutionType Available chart resolutions
type ResolutionType string

// List of ResolutionType
const (
	_1 ResolutionType = "1"
	_3 ResolutionType = "3"
	_5 ResolutionType = "5"
	_15 ResolutionType = "15"
	_30 ResolutionType = "30"
	_45 ResolutionType = "45"
	_1_H ResolutionType = "1H"
	_2_H ResolutionType = "2H"
	_4_H ResolutionType = "4H"
	_6_H ResolutionType = "6H"
	_12_H ResolutionType = "12H"
	_1_D ResolutionType = "1D"
	_1_W ResolutionType = "1W"
	_1_M ResolutionType = "1M"
	_6_M ResolutionType = "6M"
	_1_Y ResolutionType = "1Y"
)

// All allowed values of ResolutionType enum
var AllowedResolutionTypeEnumValues = []ResolutionType{
	"1",
	"3",
	"5",
	"15",
	"30",
	"45",
	"1H",
	"2H",
	"4H",
	"6H",
	"12H",
	"1D",
	"1W",
	"1M",
	"6M",
	"1Y",
}

func (v *ResolutionType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ResolutionType(value)
	for _, existing := range AllowedResolutionTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ResolutionType", value)
}

// NewResolutionTypeFromValue returns a pointer to a valid ResolutionType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewResolutionTypeFromValue(v string) (*ResolutionType, error) {
	ev := ResolutionType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ResolutionType: valid values are %v", v, AllowedResolutionTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ResolutionType) IsValid() bool {
	for _, existing := range AllowedResolutionTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ResolutionType value
func (v ResolutionType) Ptr() *ResolutionType {
	return &v
}

type NullableResolutionType struct {
	value *ResolutionType
	isSet bool
}

func (v NullableResolutionType) Get() *ResolutionType {
	return v.value
}

func (v *NullableResolutionType) Set(val *ResolutionType) {
	v.value = val
	v.isSet = true
}

func (v NullableResolutionType) IsSet() bool {
	return v.isSet
}

func (v *NullableResolutionType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResolutionType(val *ResolutionType) *NullableResolutionType {
	return &NullableResolutionType{value: val, isSet: true}
}

func (v NullableResolutionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResolutionType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

