/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SwapEventData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SwapEventData{}

// SwapEventData struct for SwapEventData
type SwapEventData struct {
	Amount0 float32 `json:"amount0"`
	Amount1 float32 `json:"amount1"`
	Price0 float32 `json:"price0"`
	Price1 float32 `json:"price1"`
	PriceUsd0 float32 `json:"price_usd0"`
	PriceUsd1 float32 `json:"price_usd1"`
}

type _SwapEventData SwapEventData

// NewSwapEventData instantiates a new SwapEventData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSwapEventData(amount0 float32, amount1 float32, price0 float32, price1 float32, priceUsd0 float32, priceUsd1 float32) *SwapEventData {
	this := SwapEventData{}
	this.Amount0 = amount0
	this.Amount1 = amount1
	this.Price0 = price0
	this.Price1 = price1
	this.PriceUsd0 = priceUsd0
	this.PriceUsd1 = priceUsd1
	return &this
}

// NewSwapEventDataWithDefaults instantiates a new SwapEventData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSwapEventDataWithDefaults() *SwapEventData {
	this := SwapEventData{}
	return &this
}

// GetAmount0 returns the Amount0 field value
func (o *SwapEventData) GetAmount0() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount0
}

// GetAmount0Ok returns a tuple with the Amount0 field value
// and a boolean to check if the value has been set.
func (o *SwapEventData) GetAmount0Ok() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount0, true
}

// SetAmount0 sets field value
func (o *SwapEventData) SetAmount0(v float32) {
	o.Amount0 = v
}

// GetAmount1 returns the Amount1 field value
func (o *SwapEventData) GetAmount1() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount1
}

// GetAmount1Ok returns a tuple with the Amount1 field value
// and a boolean to check if the value has been set.
func (o *SwapEventData) GetAmount1Ok() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount1, true
}

// SetAmount1 sets field value
func (o *SwapEventData) SetAmount1(v float32) {
	o.Amount1 = v
}

// GetPrice0 returns the Price0 field value
func (o *SwapEventData) GetPrice0() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Price0
}

// GetPrice0Ok returns a tuple with the Price0 field value
// and a boolean to check if the value has been set.
func (o *SwapEventData) GetPrice0Ok() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price0, true
}

// SetPrice0 sets field value
func (o *SwapEventData) SetPrice0(v float32) {
	o.Price0 = v
}

// GetPrice1 returns the Price1 field value
func (o *SwapEventData) GetPrice1() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Price1
}

// GetPrice1Ok returns a tuple with the Price1 field value
// and a boolean to check if the value has been set.
func (o *SwapEventData) GetPrice1Ok() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price1, true
}

// SetPrice1 sets field value
func (o *SwapEventData) SetPrice1(v float32) {
	o.Price1 = v
}

// GetPriceUsd0 returns the PriceUsd0 field value
func (o *SwapEventData) GetPriceUsd0() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PriceUsd0
}

// GetPriceUsd0Ok returns a tuple with the PriceUsd0 field value
// and a boolean to check if the value has been set.
func (o *SwapEventData) GetPriceUsd0Ok() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceUsd0, true
}

// SetPriceUsd0 sets field value
func (o *SwapEventData) SetPriceUsd0(v float32) {
	o.PriceUsd0 = v
}

// GetPriceUsd1 returns the PriceUsd1 field value
func (o *SwapEventData) GetPriceUsd1() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PriceUsd1
}

// GetPriceUsd1Ok returns a tuple with the PriceUsd1 field value
// and a boolean to check if the value has been set.
func (o *SwapEventData) GetPriceUsd1Ok() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceUsd1, true
}

// SetPriceUsd1 sets field value
func (o *SwapEventData) SetPriceUsd1(v float32) {
	o.PriceUsd1 = v
}

func (o SwapEventData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SwapEventData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount0"] = o.Amount0
	toSerialize["amount1"] = o.Amount1
	toSerialize["price0"] = o.Price0
	toSerialize["price1"] = o.Price1
	toSerialize["price_usd0"] = o.PriceUsd0
	toSerialize["price_usd1"] = o.PriceUsd1
	return toSerialize, nil
}

func (o *SwapEventData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amount0",
		"amount1",
		"price0",
		"price1",
		"price_usd0",
		"price_usd1",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSwapEventData := _SwapEventData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSwapEventData)

	if err != nil {
		return err
	}

	*o = SwapEventData(varSwapEventData)

	return err
}

type NullableSwapEventData struct {
	value *SwapEventData
	isSet bool
}

func (v NullableSwapEventData) Get() *SwapEventData {
	return v.value
}

func (v *NullableSwapEventData) Set(val *SwapEventData) {
	v.value = val
	v.isSet = true
}

func (v NullableSwapEventData) IsSet() bool {
	return v.isSet
}

func (v *NullableSwapEventData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSwapEventData(val *SwapEventData) *NullableSwapEventData {
	return &NullableSwapEventData{value: val, isSet: true}
}

func (v NullableSwapEventData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSwapEventData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


