/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PairOrderBookList200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PairOrderBookList200Response{}

// PairOrderBookList200Response struct for PairOrderBookList200Response
type PairOrderBookList200Response struct {
	Items []Transaction `json:"items"`
	NextCursor *string `json:"nextCursor,omitempty"`
	BackCursor *string `json:"backCursor,omitempty"`
}

type _PairOrderBookList200Response PairOrderBookList200Response

// NewPairOrderBookList200Response instantiates a new PairOrderBookList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPairOrderBookList200Response(items []Transaction) *PairOrderBookList200Response {
	this := PairOrderBookList200Response{}
	this.Items = items
	return &this
}

// NewPairOrderBookList200ResponseWithDefaults instantiates a new PairOrderBookList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPairOrderBookList200ResponseWithDefaults() *PairOrderBookList200Response {
	this := PairOrderBookList200Response{}
	return &this
}

// GetItems returns the Items field value
func (o *PairOrderBookList200Response) GetItems() []Transaction {
	if o == nil {
		var ret []Transaction
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *PairOrderBookList200Response) GetItemsOk() ([]Transaction, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *PairOrderBookList200Response) SetItems(v []Transaction) {
	o.Items = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *PairOrderBookList200Response) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairOrderBookList200Response) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *PairOrderBookList200Response) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *PairOrderBookList200Response) SetNextCursor(v string) {
	o.NextCursor = &v
}

// GetBackCursor returns the BackCursor field value if set, zero value otherwise.
func (o *PairOrderBookList200Response) GetBackCursor() string {
	if o == nil || IsNil(o.BackCursor) {
		var ret string
		return ret
	}
	return *o.BackCursor
}

// GetBackCursorOk returns a tuple with the BackCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairOrderBookList200Response) GetBackCursorOk() (*string, bool) {
	if o == nil || IsNil(o.BackCursor) {
		return nil, false
	}
	return o.BackCursor, true
}

// HasBackCursor returns a boolean if a field has been set.
func (o *PairOrderBookList200Response) HasBackCursor() bool {
	if o != nil && !IsNil(o.BackCursor) {
		return true
	}

	return false
}

// SetBackCursor gets a reference to the given string and assigns it to the BackCursor field.
func (o *PairOrderBookList200Response) SetBackCursor(v string) {
	o.BackCursor = &v
}

func (o PairOrderBookList200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PairOrderBookList200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	if !IsNil(o.NextCursor) {
		toSerialize["nextCursor"] = o.NextCursor
	}
	if !IsNil(o.BackCursor) {
		toSerialize["backCursor"] = o.BackCursor
	}
	return toSerialize, nil
}

func (o *PairOrderBookList200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPairOrderBookList200Response := _PairOrderBookList200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPairOrderBookList200Response)

	if err != nil {
		return err
	}

	*o = PairOrderBookList200Response(varPairOrderBookList200Response)

	return err
}

type NullablePairOrderBookList200Response struct {
	value *PairOrderBookList200Response
	isSet bool
}

func (v NullablePairOrderBookList200Response) Get() *PairOrderBookList200Response {
	return v.value
}

func (v *NullablePairOrderBookList200Response) Set(val *PairOrderBookList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePairOrderBookList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePairOrderBookList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePairOrderBookList200Response(val *PairOrderBookList200Response) *NullablePairOrderBookList200Response {
	return &NullablePairOrderBookList200Response{value: val, isSet: true}
}

func (v NullablePairOrderBookList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePairOrderBookList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


