/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PairInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PairInfo{}

// PairInfo struct for PairInfo
type PairInfo struct {
	Network Network `json:"network"`
	Dex Dex `json:"dex"`
	PairAddress string `json:"pair_address"`
	Ticker string `json:"ticker"`
	TransactionFee float32 `json:"transaction_fee"`
	Tokens []Token `json:"tokens"`
	Txn PairInfoTxn `json:"txn"`
	Volume PairInfoVolume `json:"volume"`
	PriceChange PairInfoVolume `json:"price_change"`
	LiquidityUsd float32 `json:"liquidity_usd"`
	LastUpdatedAt string `json:"last_updated_at"`
	CreatedAt string `json:"created_at"`
}

type _PairInfo PairInfo

// NewPairInfo instantiates a new PairInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPairInfo(network Network, dex Dex, pairAddress string, ticker string, transactionFee float32, tokens []Token, txn PairInfoTxn, volume PairInfoVolume, priceChange PairInfoVolume, liquidityUsd float32, lastUpdatedAt string, createdAt string) *PairInfo {
	this := PairInfo{}
	this.Network = network
	this.Dex = dex
	this.PairAddress = pairAddress
	this.Ticker = ticker
	this.TransactionFee = transactionFee
	this.Tokens = tokens
	this.Txn = txn
	this.Volume = volume
	this.PriceChange = priceChange
	this.LiquidityUsd = liquidityUsd
	this.LastUpdatedAt = lastUpdatedAt
	this.CreatedAt = createdAt
	return &this
}

// NewPairInfoWithDefaults instantiates a new PairInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPairInfoWithDefaults() *PairInfo {
	this := PairInfo{}
	return &this
}

// GetNetwork returns the Network field value
func (o *PairInfo) GetNetwork() Network {
	if o == nil {
		var ret Network
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *PairInfo) GetNetworkOk() (*Network, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *PairInfo) SetNetwork(v Network) {
	o.Network = v
}

// GetDex returns the Dex field value
func (o *PairInfo) GetDex() Dex {
	if o == nil {
		var ret Dex
		return ret
	}

	return o.Dex
}

// GetDexOk returns a tuple with the Dex field value
// and a boolean to check if the value has been set.
func (o *PairInfo) GetDexOk() (*Dex, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dex, true
}

// SetDex sets field value
func (o *PairInfo) SetDex(v Dex) {
	o.Dex = v
}

// GetPairAddress returns the PairAddress field value
func (o *PairInfo) GetPairAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PairAddress
}

// GetPairAddressOk returns a tuple with the PairAddress field value
// and a boolean to check if the value has been set.
func (o *PairInfo) GetPairAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PairAddress, true
}

// SetPairAddress sets field value
func (o *PairInfo) SetPairAddress(v string) {
	o.PairAddress = v
}

// GetTicker returns the Ticker field value
func (o *PairInfo) GetTicker() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ticker
}

// GetTickerOk returns a tuple with the Ticker field value
// and a boolean to check if the value has been set.
func (o *PairInfo) GetTickerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ticker, true
}

// SetTicker sets field value
func (o *PairInfo) SetTicker(v string) {
	o.Ticker = v
}

// GetTransactionFee returns the TransactionFee field value
func (o *PairInfo) GetTransactionFee() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TransactionFee
}

// GetTransactionFeeOk returns a tuple with the TransactionFee field value
// and a boolean to check if the value has been set.
func (o *PairInfo) GetTransactionFeeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionFee, true
}

// SetTransactionFee sets field value
func (o *PairInfo) SetTransactionFee(v float32) {
	o.TransactionFee = v
}

// GetTokens returns the Tokens field value
func (o *PairInfo) GetTokens() []Token {
	if o == nil {
		var ret []Token
		return ret
	}

	return o.Tokens
}

// GetTokensOk returns a tuple with the Tokens field value
// and a boolean to check if the value has been set.
func (o *PairInfo) GetTokensOk() ([]Token, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tokens, true
}

// SetTokens sets field value
func (o *PairInfo) SetTokens(v []Token) {
	o.Tokens = v
}

// GetTxn returns the Txn field value
func (o *PairInfo) GetTxn() PairInfoTxn {
	if o == nil {
		var ret PairInfoTxn
		return ret
	}

	return o.Txn
}

// GetTxnOk returns a tuple with the Txn field value
// and a boolean to check if the value has been set.
func (o *PairInfo) GetTxnOk() (*PairInfoTxn, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Txn, true
}

// SetTxn sets field value
func (o *PairInfo) SetTxn(v PairInfoTxn) {
	o.Txn = v
}

// GetVolume returns the Volume field value
func (o *PairInfo) GetVolume() PairInfoVolume {
	if o == nil {
		var ret PairInfoVolume
		return ret
	}

	return o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value
// and a boolean to check if the value has been set.
func (o *PairInfo) GetVolumeOk() (*PairInfoVolume, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Volume, true
}

// SetVolume sets field value
func (o *PairInfo) SetVolume(v PairInfoVolume) {
	o.Volume = v
}

// GetPriceChange returns the PriceChange field value
func (o *PairInfo) GetPriceChange() PairInfoVolume {
	if o == nil {
		var ret PairInfoVolume
		return ret
	}

	return o.PriceChange
}

// GetPriceChangeOk returns a tuple with the PriceChange field value
// and a boolean to check if the value has been set.
func (o *PairInfo) GetPriceChangeOk() (*PairInfoVolume, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceChange, true
}

// SetPriceChange sets field value
func (o *PairInfo) SetPriceChange(v PairInfoVolume) {
	o.PriceChange = v
}

// GetLiquidityUsd returns the LiquidityUsd field value
func (o *PairInfo) GetLiquidityUsd() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.LiquidityUsd
}

// GetLiquidityUsdOk returns a tuple with the LiquidityUsd field value
// and a boolean to check if the value has been set.
func (o *PairInfo) GetLiquidityUsdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LiquidityUsd, true
}

// SetLiquidityUsd sets field value
func (o *PairInfo) SetLiquidityUsd(v float32) {
	o.LiquidityUsd = v
}

// GetLastUpdatedAt returns the LastUpdatedAt field value
func (o *PairInfo) GetLastUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastUpdatedAt
}

// GetLastUpdatedAtOk returns a tuple with the LastUpdatedAt field value
// and a boolean to check if the value has been set.
func (o *PairInfo) GetLastUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUpdatedAt, true
}

// SetLastUpdatedAt sets field value
func (o *PairInfo) SetLastUpdatedAt(v string) {
	o.LastUpdatedAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *PairInfo) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PairInfo) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PairInfo) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o PairInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PairInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["network"] = o.Network
	toSerialize["dex"] = o.Dex
	toSerialize["pair_address"] = o.PairAddress
	toSerialize["ticker"] = o.Ticker
	toSerialize["transaction_fee"] = o.TransactionFee
	toSerialize["tokens"] = o.Tokens
	toSerialize["txn"] = o.Txn
	toSerialize["volume"] = o.Volume
	toSerialize["price_change"] = o.PriceChange
	toSerialize["liquidity_usd"] = o.LiquidityUsd
	toSerialize["last_updated_at"] = o.LastUpdatedAt
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *PairInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"network",
		"dex",
		"pair_address",
		"ticker",
		"transaction_fee",
		"tokens",
		"txn",
		"volume",
		"price_change",
		"liquidity_usd",
		"last_updated_at",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPairInfo := _PairInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPairInfo)

	if err != nil {
		return err
	}

	*o = PairInfo(varPairInfo)

	return err
}

type NullablePairInfo struct {
	value *PairInfo
	isSet bool
}

func (v NullablePairInfo) Get() *PairInfo {
	return v.value
}

func (v *NullablePairInfo) Set(val *PairInfo) {
	v.value = val
	v.isSet = true
}

func (v NullablePairInfo) IsSet() bool {
	return v.isSet
}

func (v *NullablePairInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePairInfo(val *PairInfo) *NullablePairInfo {
	return &NullablePairInfo{value: val, isSet: true}
}

func (v NullablePairInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePairInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


