/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// TransactionBlockInfo - struct for TransactionBlockInfo
type TransactionBlockInfo struct {
	EthereumTxData *EthereumTxData
	TonTxData *TonTxData
}

// EthereumTxDataAsTransactionBlockInfo is a convenience function that returns EthereumTxData wrapped in TransactionBlockInfo
func EthereumTxDataAsTransactionBlockInfo(v *EthereumTxData) TransactionBlockInfo {
	return TransactionBlockInfo{
		EthereumTxData: v,
	}
}

// TonTxDataAsTransactionBlockInfo is a convenience function that returns TonTxData wrapped in TransactionBlockInfo
func TonTxDataAsTransactionBlockInfo(v *TonTxData) TransactionBlockInfo {
	return TransactionBlockInfo{
		TonTxData: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *TransactionBlockInfo) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into EthereumTxData
	err = newStrictDecoder(data).Decode(&dst.EthereumTxData)
	if err == nil {
		jsonEthereumTxData, _ := json.Marshal(dst.EthereumTxData)
		if string(jsonEthereumTxData) == "{}" { // empty struct
			dst.EthereumTxData = nil
		} else {
			if err = validator.Validate(dst.EthereumTxData); err != nil {
				dst.EthereumTxData = nil
			} else {
				match++
			}
		}
	} else {
		dst.EthereumTxData = nil
	}

	// try to unmarshal data into TonTxData
	err = newStrictDecoder(data).Decode(&dst.TonTxData)
	if err == nil {
		jsonTonTxData, _ := json.Marshal(dst.TonTxData)
		if string(jsonTonTxData) == "{}" { // empty struct
			dst.TonTxData = nil
		} else {
			if err = validator.Validate(dst.TonTxData); err != nil {
				dst.TonTxData = nil
			} else {
				match++
			}
		}
	} else {
		dst.TonTxData = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.EthereumTxData = nil
		dst.TonTxData = nil

		return fmt.Errorf("data matches more than one schema in oneOf(TransactionBlockInfo)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(TransactionBlockInfo)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TransactionBlockInfo) MarshalJSON() ([]byte, error) {
	if src.EthereumTxData != nil {
		return json.Marshal(&src.EthereumTxData)
	}

	if src.TonTxData != nil {
		return json.Marshal(&src.TonTxData)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *TransactionBlockInfo) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.EthereumTxData != nil {
		return obj.EthereumTxData
	}

	if obj.TonTxData != nil {
		return obj.TonTxData
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj TransactionBlockInfo) GetActualInstanceValue() (interface{}) {
	if obj.EthereumTxData != nil {
		return *obj.EthereumTxData
	}

	if obj.TonTxData != nil {
		return *obj.TonTxData
	}

	// all schemas are nil
	return nil
}

type NullableTransactionBlockInfo struct {
	value *TransactionBlockInfo
	isSet bool
}

func (v NullableTransactionBlockInfo) Get() *TransactionBlockInfo {
	return v.value
}

func (v *NullableTransactionBlockInfo) Set(val *TransactionBlockInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionBlockInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionBlockInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionBlockInfo(val *TransactionBlockInfo) *NullableTransactionBlockInfo {
	return &NullableTransactionBlockInfo{value: val, isSet: true}
}

func (v NullableTransactionBlockInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionBlockInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


