/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// TransactionEventData - struct for TransactionEventData
type TransactionEventData struct {
	LiquidityEventData *LiquidityEventData
	SwapEventData *SwapEventData
}

// LiquidityEventDataAsTransactionEventData is a convenience function that returns LiquidityEventData wrapped in TransactionEventData
func LiquidityEventDataAsTransactionEventData(v *LiquidityEventData) TransactionEventData {
	return TransactionEventData{
		LiquidityEventData: v,
	}
}

// SwapEventDataAsTransactionEventData is a convenience function that returns SwapEventData wrapped in TransactionEventData
func SwapEventDataAsTransactionEventData(v *SwapEventData) TransactionEventData {
	return TransactionEventData{
		SwapEventData: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *TransactionEventData) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into LiquidityEventData
	err = newStrictDecoder(data).Decode(&dst.LiquidityEventData)
	if err == nil {
		jsonLiquidityEventData, _ := json.Marshal(dst.LiquidityEventData)
		if string(jsonLiquidityEventData) == "{}" { // empty struct
			dst.LiquidityEventData = nil
		} else {
			if err = validator.Validate(dst.LiquidityEventData); err != nil {
				dst.LiquidityEventData = nil
			} else {
				match++
			}
		}
	} else {
		dst.LiquidityEventData = nil
	}

	// try to unmarshal data into SwapEventData
	err = newStrictDecoder(data).Decode(&dst.SwapEventData)
	if err == nil {
		jsonSwapEventData, _ := json.Marshal(dst.SwapEventData)
		if string(jsonSwapEventData) == "{}" { // empty struct
			dst.SwapEventData = nil
		} else {
			if err = validator.Validate(dst.SwapEventData); err != nil {
				dst.SwapEventData = nil
			} else {
				match++
			}
		}
	} else {
		dst.SwapEventData = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.LiquidityEventData = nil
		dst.SwapEventData = nil

		return fmt.Errorf("data matches more than one schema in oneOf(TransactionEventData)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(TransactionEventData)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TransactionEventData) MarshalJSON() ([]byte, error) {
	if src.LiquidityEventData != nil {
		return json.Marshal(&src.LiquidityEventData)
	}

	if src.SwapEventData != nil {
		return json.Marshal(&src.SwapEventData)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *TransactionEventData) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.LiquidityEventData != nil {
		return obj.LiquidityEventData
	}

	if obj.SwapEventData != nil {
		return obj.SwapEventData
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj TransactionEventData) GetActualInstanceValue() (interface{}) {
	if obj.LiquidityEventData != nil {
		return *obj.LiquidityEventData
	}

	if obj.SwapEventData != nil {
		return *obj.SwapEventData
	}

	// all schemas are nil
	return nil
}

type NullableTransactionEventData struct {
	value *TransactionEventData
	isSet bool
}

func (v NullableTransactionEventData) Get() *TransactionEventData {
	return v.value
}

func (v *NullableTransactionEventData) Set(val *TransactionEventData) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionEventData) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionEventData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionEventData(val *TransactionEventData) *NullableTransactionEventData {
	return &NullableTransactionEventData{value: val, isSet: true}
}

func (v NullableTransactionEventData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionEventData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


