/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RouterHop type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RouterHop{}

// RouterHop struct for RouterHop
type RouterHop struct {
	FromToken BaseToken `json:"from_token"`
	ToToken BaseToken `json:"to_token"`
	Pair string `json:"pair"`
	Position int32 `json:"position"`
}

type _RouterHop RouterHop

// NewRouterHop instantiates a new RouterHop object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRouterHop(fromToken BaseToken, toToken BaseToken, pair string, position int32) *RouterHop {
	this := RouterHop{}
	this.FromToken = fromToken
	this.ToToken = toToken
	this.Pair = pair
	this.Position = position
	return &this
}

// NewRouterHopWithDefaults instantiates a new RouterHop object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRouterHopWithDefaults() *RouterHop {
	this := RouterHop{}
	return &this
}

// GetFromToken returns the FromToken field value
func (o *RouterHop) GetFromToken() BaseToken {
	if o == nil {
		var ret BaseToken
		return ret
	}

	return o.FromToken
}

// GetFromTokenOk returns a tuple with the FromToken field value
// and a boolean to check if the value has been set.
func (o *RouterHop) GetFromTokenOk() (*BaseToken, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromToken, true
}

// SetFromToken sets field value
func (o *RouterHop) SetFromToken(v BaseToken) {
	o.FromToken = v
}

// GetToToken returns the ToToken field value
func (o *RouterHop) GetToToken() BaseToken {
	if o == nil {
		var ret BaseToken
		return ret
	}

	return o.ToToken
}

// GetToTokenOk returns a tuple with the ToToken field value
// and a boolean to check if the value has been set.
func (o *RouterHop) GetToTokenOk() (*BaseToken, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToToken, true
}

// SetToToken sets field value
func (o *RouterHop) SetToToken(v BaseToken) {
	o.ToToken = v
}

// GetPair returns the Pair field value
func (o *RouterHop) GetPair() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pair
}

// GetPairOk returns a tuple with the Pair field value
// and a boolean to check if the value has been set.
func (o *RouterHop) GetPairOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pair, true
}

// SetPair sets field value
func (o *RouterHop) SetPair(v string) {
	o.Pair = v
}

// GetPosition returns the Position field value
func (o *RouterHop) GetPosition() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Position
}

// GetPositionOk returns a tuple with the Position field value
// and a boolean to check if the value has been set.
func (o *RouterHop) GetPositionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Position, true
}

// SetPosition sets field value
func (o *RouterHop) SetPosition(v int32) {
	o.Position = v
}

func (o RouterHop) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RouterHop) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["from_token"] = o.FromToken
	toSerialize["to_token"] = o.ToToken
	toSerialize["pair"] = o.Pair
	toSerialize["position"] = o.Position
	return toSerialize, nil
}

func (o *RouterHop) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"from_token",
		"to_token",
		"pair",
		"position",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRouterHop := _RouterHop{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRouterHop)

	if err != nil {
		return err
	}

	*o = RouterHop(varRouterHop)

	return err
}

type NullableRouterHop struct {
	value *RouterHop
	isSet bool
}

func (v NullableRouterHop) Get() *RouterHop {
	return v.value
}

func (v *NullableRouterHop) Set(val *RouterHop) {
	v.value = val
	v.isSet = true
}

func (v NullableRouterHop) IsSet() bool {
	return v.isSet
}

func (v *NullableRouterHop) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRouterHop(val *RouterHop) *NullableRouterHop {
	return &NullableRouterHop{value: val, isSet: true}
}

func (v NullableRouterHop) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRouterHop) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


