/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NftAssetInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NftAssetInfo{}

// NftAssetInfo struct for NftAssetInfo
type NftAssetInfo struct {
	ChainId int32 `json:"chain_id"`
	Address string `json:"address"`
	Owner *string `json:"owner,omitempty"`
	Minter *string `json:"minter,omitempty"`
	TokenUri *string `json:"token_uri,omitempty"`
	TokenId string `json:"token_id"`
	RawMetadata *string `json:"raw_metadata,omitempty"`
	Amount *string `json:"amount,omitempty"`
	TokenType string `json:"token_type"`
	Name *string `json:"name,omitempty"`
	ImageUri *string `json:"image_uri,omitempty"`
	Description *string `json:"description,omitempty"`
	MintBlockNumber *int32 `json:"mint_block_number,omitempty"`
	MintTransactionHash *string `json:"mint_transaction_hash,omitempty"`
	MintTimestamp *string `json:"mint_timestamp,omitempty"`
}

type _NftAssetInfo NftAssetInfo

// NewNftAssetInfo instantiates a new NftAssetInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNftAssetInfo(chainId int32, address string, tokenId string, tokenType string) *NftAssetInfo {
	this := NftAssetInfo{}
	this.ChainId = chainId
	this.Address = address
	this.TokenId = tokenId
	this.TokenType = tokenType
	return &this
}

// NewNftAssetInfoWithDefaults instantiates a new NftAssetInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNftAssetInfoWithDefaults() *NftAssetInfo {
	this := NftAssetInfo{}
	return &this
}

// GetChainId returns the ChainId field value
func (o *NftAssetInfo) GetChainId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *NftAssetInfo) GetChainIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *NftAssetInfo) SetChainId(v int32) {
	o.ChainId = v
}

// GetAddress returns the Address field value
func (o *NftAssetInfo) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *NftAssetInfo) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *NftAssetInfo) SetAddress(v string) {
	o.Address = v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *NftAssetInfo) GetOwner() string {
	if o == nil || IsNil(o.Owner) {
		var ret string
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftAssetInfo) GetOwnerOk() (*string, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *NftAssetInfo) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given string and assigns it to the Owner field.
func (o *NftAssetInfo) SetOwner(v string) {
	o.Owner = &v
}

// GetMinter returns the Minter field value if set, zero value otherwise.
func (o *NftAssetInfo) GetMinter() string {
	if o == nil || IsNil(o.Minter) {
		var ret string
		return ret
	}
	return *o.Minter
}

// GetMinterOk returns a tuple with the Minter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftAssetInfo) GetMinterOk() (*string, bool) {
	if o == nil || IsNil(o.Minter) {
		return nil, false
	}
	return o.Minter, true
}

// HasMinter returns a boolean if a field has been set.
func (o *NftAssetInfo) HasMinter() bool {
	if o != nil && !IsNil(o.Minter) {
		return true
	}

	return false
}

// SetMinter gets a reference to the given string and assigns it to the Minter field.
func (o *NftAssetInfo) SetMinter(v string) {
	o.Minter = &v
}

// GetTokenUri returns the TokenUri field value if set, zero value otherwise.
func (o *NftAssetInfo) GetTokenUri() string {
	if o == nil || IsNil(o.TokenUri) {
		var ret string
		return ret
	}
	return *o.TokenUri
}

// GetTokenUriOk returns a tuple with the TokenUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftAssetInfo) GetTokenUriOk() (*string, bool) {
	if o == nil || IsNil(o.TokenUri) {
		return nil, false
	}
	return o.TokenUri, true
}

// HasTokenUri returns a boolean if a field has been set.
func (o *NftAssetInfo) HasTokenUri() bool {
	if o != nil && !IsNil(o.TokenUri) {
		return true
	}

	return false
}

// SetTokenUri gets a reference to the given string and assigns it to the TokenUri field.
func (o *NftAssetInfo) SetTokenUri(v string) {
	o.TokenUri = &v
}

// GetTokenId returns the TokenId field value
func (o *NftAssetInfo) GetTokenId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value
// and a boolean to check if the value has been set.
func (o *NftAssetInfo) GetTokenIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenId, true
}

// SetTokenId sets field value
func (o *NftAssetInfo) SetTokenId(v string) {
	o.TokenId = v
}

// GetRawMetadata returns the RawMetadata field value if set, zero value otherwise.
func (o *NftAssetInfo) GetRawMetadata() string {
	if o == nil || IsNil(o.RawMetadata) {
		var ret string
		return ret
	}
	return *o.RawMetadata
}

// GetRawMetadataOk returns a tuple with the RawMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftAssetInfo) GetRawMetadataOk() (*string, bool) {
	if o == nil || IsNil(o.RawMetadata) {
		return nil, false
	}
	return o.RawMetadata, true
}

// HasRawMetadata returns a boolean if a field has been set.
func (o *NftAssetInfo) HasRawMetadata() bool {
	if o != nil && !IsNil(o.RawMetadata) {
		return true
	}

	return false
}

// SetRawMetadata gets a reference to the given string and assigns it to the RawMetadata field.
func (o *NftAssetInfo) SetRawMetadata(v string) {
	o.RawMetadata = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *NftAssetInfo) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftAssetInfo) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *NftAssetInfo) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *NftAssetInfo) SetAmount(v string) {
	o.Amount = &v
}

// GetTokenType returns the TokenType field value
func (o *NftAssetInfo) GetTokenType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenType
}

// GetTokenTypeOk returns a tuple with the TokenType field value
// and a boolean to check if the value has been set.
func (o *NftAssetInfo) GetTokenTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenType, true
}

// SetTokenType sets field value
func (o *NftAssetInfo) SetTokenType(v string) {
	o.TokenType = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *NftAssetInfo) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftAssetInfo) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *NftAssetInfo) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *NftAssetInfo) SetName(v string) {
	o.Name = &v
}

// GetImageUri returns the ImageUri field value if set, zero value otherwise.
func (o *NftAssetInfo) GetImageUri() string {
	if o == nil || IsNil(o.ImageUri) {
		var ret string
		return ret
	}
	return *o.ImageUri
}

// GetImageUriOk returns a tuple with the ImageUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftAssetInfo) GetImageUriOk() (*string, bool) {
	if o == nil || IsNil(o.ImageUri) {
		return nil, false
	}
	return o.ImageUri, true
}

// HasImageUri returns a boolean if a field has been set.
func (o *NftAssetInfo) HasImageUri() bool {
	if o != nil && !IsNil(o.ImageUri) {
		return true
	}

	return false
}

// SetImageUri gets a reference to the given string and assigns it to the ImageUri field.
func (o *NftAssetInfo) SetImageUri(v string) {
	o.ImageUri = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *NftAssetInfo) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftAssetInfo) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *NftAssetInfo) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *NftAssetInfo) SetDescription(v string) {
	o.Description = &v
}

// GetMintBlockNumber returns the MintBlockNumber field value if set, zero value otherwise.
func (o *NftAssetInfo) GetMintBlockNumber() int32 {
	if o == nil || IsNil(o.MintBlockNumber) {
		var ret int32
		return ret
	}
	return *o.MintBlockNumber
}

// GetMintBlockNumberOk returns a tuple with the MintBlockNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftAssetInfo) GetMintBlockNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.MintBlockNumber) {
		return nil, false
	}
	return o.MintBlockNumber, true
}

// HasMintBlockNumber returns a boolean if a field has been set.
func (o *NftAssetInfo) HasMintBlockNumber() bool {
	if o != nil && !IsNil(o.MintBlockNumber) {
		return true
	}

	return false
}

// SetMintBlockNumber gets a reference to the given int32 and assigns it to the MintBlockNumber field.
func (o *NftAssetInfo) SetMintBlockNumber(v int32) {
	o.MintBlockNumber = &v
}

// GetMintTransactionHash returns the MintTransactionHash field value if set, zero value otherwise.
func (o *NftAssetInfo) GetMintTransactionHash() string {
	if o == nil || IsNil(o.MintTransactionHash) {
		var ret string
		return ret
	}
	return *o.MintTransactionHash
}

// GetMintTransactionHashOk returns a tuple with the MintTransactionHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftAssetInfo) GetMintTransactionHashOk() (*string, bool) {
	if o == nil || IsNil(o.MintTransactionHash) {
		return nil, false
	}
	return o.MintTransactionHash, true
}

// HasMintTransactionHash returns a boolean if a field has been set.
func (o *NftAssetInfo) HasMintTransactionHash() bool {
	if o != nil && !IsNil(o.MintTransactionHash) {
		return true
	}

	return false
}

// SetMintTransactionHash gets a reference to the given string and assigns it to the MintTransactionHash field.
func (o *NftAssetInfo) SetMintTransactionHash(v string) {
	o.MintTransactionHash = &v
}

// GetMintTimestamp returns the MintTimestamp field value if set, zero value otherwise.
func (o *NftAssetInfo) GetMintTimestamp() string {
	if o == nil || IsNil(o.MintTimestamp) {
		var ret string
		return ret
	}
	return *o.MintTimestamp
}

// GetMintTimestampOk returns a tuple with the MintTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftAssetInfo) GetMintTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.MintTimestamp) {
		return nil, false
	}
	return o.MintTimestamp, true
}

// HasMintTimestamp returns a boolean if a field has been set.
func (o *NftAssetInfo) HasMintTimestamp() bool {
	if o != nil && !IsNil(o.MintTimestamp) {
		return true
	}

	return false
}

// SetMintTimestamp gets a reference to the given string and assigns it to the MintTimestamp field.
func (o *NftAssetInfo) SetMintTimestamp(v string) {
	o.MintTimestamp = &v
}

func (o NftAssetInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NftAssetInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["chain_id"] = o.ChainId
	toSerialize["address"] = o.Address
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !IsNil(o.Minter) {
		toSerialize["minter"] = o.Minter
	}
	if !IsNil(o.TokenUri) {
		toSerialize["token_uri"] = o.TokenUri
	}
	toSerialize["token_id"] = o.TokenId
	if !IsNil(o.RawMetadata) {
		toSerialize["raw_metadata"] = o.RawMetadata
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	toSerialize["token_type"] = o.TokenType
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ImageUri) {
		toSerialize["image_uri"] = o.ImageUri
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.MintBlockNumber) {
		toSerialize["mint_block_number"] = o.MintBlockNumber
	}
	if !IsNil(o.MintTransactionHash) {
		toSerialize["mint_transaction_hash"] = o.MintTransactionHash
	}
	if !IsNil(o.MintTimestamp) {
		toSerialize["mint_timestamp"] = o.MintTimestamp
	}
	return toSerialize, nil
}

func (o *NftAssetInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"chain_id",
		"address",
		"token_id",
		"token_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNftAssetInfo := _NftAssetInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNftAssetInfo)

	if err != nil {
		return err
	}

	*o = NftAssetInfo(varNftAssetInfo)

	return err
}

type NullableNftAssetInfo struct {
	value *NftAssetInfo
	isSet bool
}

func (v NullableNftAssetInfo) Get() *NftAssetInfo {
	return v.value
}

func (v *NullableNftAssetInfo) Set(val *NftAssetInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableNftAssetInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableNftAssetInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNftAssetInfo(val *NftAssetInfo) *NullableNftAssetInfo {
	return &NullableNftAssetInfo{value: val, isSet: true}
}

func (v NullableNftAssetInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNftAssetInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


