/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the APIErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &APIErrorResponse{}

// APIErrorResponse struct for APIErrorResponse
type APIErrorResponse struct {
	Errors []APIErrorResponseErrorsInner `json:"errors,omitempty"`
}

// NewAPIErrorResponse instantiates a new APIErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIErrorResponse() *APIErrorResponse {
	this := APIErrorResponse{}
	return &this
}

// NewAPIErrorResponseWithDefaults instantiates a new APIErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIErrorResponseWithDefaults() *APIErrorResponse {
	this := APIErrorResponse{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *APIErrorResponse) GetErrors() []APIErrorResponseErrorsInner {
	if o == nil || IsNil(o.Errors) {
		var ret []APIErrorResponseErrorsInner
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIErrorResponse) GetErrorsOk() ([]APIErrorResponseErrorsInner, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *APIErrorResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []APIErrorResponseErrorsInner and assigns it to the Errors field.
func (o *APIErrorResponse) SetErrors(v []APIErrorResponseErrorsInner) {
	o.Errors = v
}

func (o APIErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o APIErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableAPIErrorResponse struct {
	value *APIErrorResponse
	isSet bool
}

func (v NullableAPIErrorResponse) Get() *APIErrorResponse {
	return v.value
}

func (v *NullableAPIErrorResponse) Set(val *APIErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIErrorResponse(val *APIErrorResponse) *NullableAPIErrorResponse {
	return &NullableAPIErrorResponse{value: val, isSet: true}
}

func (v NullableAPIErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


