/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the APIErrorResponseErrorsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &APIErrorResponseErrorsInner{}

// APIErrorResponseErrorsInner struct for APIErrorResponseErrorsInner
type APIErrorResponseErrorsInner struct {
	Type string `json:"type"`
	Code *APIErrorCode `json:"code,omitempty"`
	Message string `json:"message"`
	Param *string `json:"param,omitempty"`
}

type _APIErrorResponseErrorsInner APIErrorResponseErrorsInner

// NewAPIErrorResponseErrorsInner instantiates a new APIErrorResponseErrorsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIErrorResponseErrorsInner(type_ string, message string) *APIErrorResponseErrorsInner {
	this := APIErrorResponseErrorsInner{}
	this.Type = type_
	this.Message = message
	return &this
}

// NewAPIErrorResponseErrorsInnerWithDefaults instantiates a new APIErrorResponseErrorsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIErrorResponseErrorsInnerWithDefaults() *APIErrorResponseErrorsInner {
	this := APIErrorResponseErrorsInner{}
	return &this
}

// GetType returns the Type field value
func (o *APIErrorResponseErrorsInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *APIErrorResponseErrorsInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *APIErrorResponseErrorsInner) SetType(v string) {
	o.Type = v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *APIErrorResponseErrorsInner) GetCode() APIErrorCode {
	if o == nil || IsNil(o.Code) {
		var ret APIErrorCode
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIErrorResponseErrorsInner) GetCodeOk() (*APIErrorCode, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *APIErrorResponseErrorsInner) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given APIErrorCode and assigns it to the Code field.
func (o *APIErrorResponseErrorsInner) SetCode(v APIErrorCode) {
	o.Code = &v
}

// GetMessage returns the Message field value
func (o *APIErrorResponseErrorsInner) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *APIErrorResponseErrorsInner) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *APIErrorResponseErrorsInner) SetMessage(v string) {
	o.Message = v
}

// GetParam returns the Param field value if set, zero value otherwise.
func (o *APIErrorResponseErrorsInner) GetParam() string {
	if o == nil || IsNil(o.Param) {
		var ret string
		return ret
	}
	return *o.Param
}

// GetParamOk returns a tuple with the Param field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIErrorResponseErrorsInner) GetParamOk() (*string, bool) {
	if o == nil || IsNil(o.Param) {
		return nil, false
	}
	return o.Param, true
}

// HasParam returns a boolean if a field has been set.
func (o *APIErrorResponseErrorsInner) HasParam() bool {
	if o != nil && !IsNil(o.Param) {
		return true
	}

	return false
}

// SetParam gets a reference to the given string and assigns it to the Param field.
func (o *APIErrorResponseErrorsInner) SetParam(v string) {
	o.Param = &v
}

func (o APIErrorResponseErrorsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o APIErrorResponseErrorsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	toSerialize["message"] = o.Message
	if !IsNil(o.Param) {
		toSerialize["param"] = o.Param
	}
	return toSerialize, nil
}

func (o *APIErrorResponseErrorsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAPIErrorResponseErrorsInner := _APIErrorResponseErrorsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAPIErrorResponseErrorsInner)

	if err != nil {
		return err
	}

	*o = APIErrorResponseErrorsInner(varAPIErrorResponseErrorsInner)

	return err
}

type NullableAPIErrorResponseErrorsInner struct {
	value *APIErrorResponseErrorsInner
	isSet bool
}

func (v NullableAPIErrorResponseErrorsInner) Get() *APIErrorResponseErrorsInner {
	return v.value
}

func (v *NullableAPIErrorResponseErrorsInner) Set(val *APIErrorResponseErrorsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIErrorResponseErrorsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIErrorResponseErrorsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIErrorResponseErrorsInner(val *APIErrorResponseErrorsInner) *NullableAPIErrorResponseErrorsInner {
	return &NullableAPIErrorResponseErrorsInner{value: val, isSet: true}
}

func (v NullableAPIErrorResponseErrorsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIErrorResponseErrorsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


