/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PairListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PairListRequest{}

// PairListRequest struct for PairListRequest
type PairListRequest struct {
	Networks []NetworkType `json:"networks,omitempty"`
	SortBy *string `json:"sort_by,omitempty"`
	SortValue *string `json:"sort_value,omitempty"`
	OrderBy *OrderBy `json:"order_by,omitempty"`
	// search by ticker or dex name
	Search *string `json:"search,omitempty"`
	MinLiquidityUsd *float64 `json:"min_liquidity_usd,omitempty"`
	MaxLiquidityUsd *float64 `json:"max_liquidity_usd,omitempty"`
	DexNames []string `json:"dex_names,omitempty"`
	DexProtocols []string `json:"dex_protocols,omitempty"`
	DexFactoryTypes []string `json:"dex_factory_types,omitempty"`
	Cursor *string `json:"cursor,omitempty"`
	Count int32 `json:"count"`
}

type _PairListRequest PairListRequest

// NewPairListRequest instantiates a new PairListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPairListRequest(count int32) *PairListRequest {
	this := PairListRequest{}
	var sortBy string = "liquidity"
	this.SortBy = &sortBy
	var orderBy OrderBy = DESC
	this.OrderBy = &orderBy
	this.Count = count
	return &this
}

// NewPairListRequestWithDefaults instantiates a new PairListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPairListRequestWithDefaults() *PairListRequest {
	this := PairListRequest{}
	var sortBy string = "liquidity"
	this.SortBy = &sortBy
	var orderBy OrderBy = DESC
	this.OrderBy = &orderBy
	var count int32 = 10
	this.Count = count
	return &this
}

// GetNetworks returns the Networks field value if set, zero value otherwise.
func (o *PairListRequest) GetNetworks() []NetworkType {
	if o == nil || IsNil(o.Networks) {
		var ret []NetworkType
		return ret
	}
	return o.Networks
}

// GetNetworksOk returns a tuple with the Networks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairListRequest) GetNetworksOk() ([]NetworkType, bool) {
	if o == nil || IsNil(o.Networks) {
		return nil, false
	}
	return o.Networks, true
}

// HasNetworks returns a boolean if a field has been set.
func (o *PairListRequest) HasNetworks() bool {
	if o != nil && !IsNil(o.Networks) {
		return true
	}

	return false
}

// SetNetworks gets a reference to the given []NetworkType and assigns it to the Networks field.
func (o *PairListRequest) SetNetworks(v []NetworkType) {
	o.Networks = v
}

// GetSortBy returns the SortBy field value if set, zero value otherwise.
func (o *PairListRequest) GetSortBy() string {
	if o == nil || IsNil(o.SortBy) {
		var ret string
		return ret
	}
	return *o.SortBy
}

// GetSortByOk returns a tuple with the SortBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairListRequest) GetSortByOk() (*string, bool) {
	if o == nil || IsNil(o.SortBy) {
		return nil, false
	}
	return o.SortBy, true
}

// HasSortBy returns a boolean if a field has been set.
func (o *PairListRequest) HasSortBy() bool {
	if o != nil && !IsNil(o.SortBy) {
		return true
	}

	return false
}

// SetSortBy gets a reference to the given string and assigns it to the SortBy field.
func (o *PairListRequest) SetSortBy(v string) {
	o.SortBy = &v
}

// GetSortValue returns the SortValue field value if set, zero value otherwise.
func (o *PairListRequest) GetSortValue() string {
	if o == nil || IsNil(o.SortValue) {
		var ret string
		return ret
	}
	return *o.SortValue
}

// GetSortValueOk returns a tuple with the SortValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairListRequest) GetSortValueOk() (*string, bool) {
	if o == nil || IsNil(o.SortValue) {
		return nil, false
	}
	return o.SortValue, true
}

// HasSortValue returns a boolean if a field has been set.
func (o *PairListRequest) HasSortValue() bool {
	if o != nil && !IsNil(o.SortValue) {
		return true
	}

	return false
}

// SetSortValue gets a reference to the given string and assigns it to the SortValue field.
func (o *PairListRequest) SetSortValue(v string) {
	o.SortValue = &v
}

// GetOrderBy returns the OrderBy field value if set, zero value otherwise.
func (o *PairListRequest) GetOrderBy() OrderBy {
	if o == nil || IsNil(o.OrderBy) {
		var ret OrderBy
		return ret
	}
	return *o.OrderBy
}

// GetOrderByOk returns a tuple with the OrderBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairListRequest) GetOrderByOk() (*OrderBy, bool) {
	if o == nil || IsNil(o.OrderBy) {
		return nil, false
	}
	return o.OrderBy, true
}

// HasOrderBy returns a boolean if a field has been set.
func (o *PairListRequest) HasOrderBy() bool {
	if o != nil && !IsNil(o.OrderBy) {
		return true
	}

	return false
}

// SetOrderBy gets a reference to the given OrderBy and assigns it to the OrderBy field.
func (o *PairListRequest) SetOrderBy(v OrderBy) {
	o.OrderBy = &v
}

// GetSearch returns the Search field value if set, zero value otherwise.
func (o *PairListRequest) GetSearch() string {
	if o == nil || IsNil(o.Search) {
		var ret string
		return ret
	}
	return *o.Search
}

// GetSearchOk returns a tuple with the Search field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairListRequest) GetSearchOk() (*string, bool) {
	if o == nil || IsNil(o.Search) {
		return nil, false
	}
	return o.Search, true
}

// HasSearch returns a boolean if a field has been set.
func (o *PairListRequest) HasSearch() bool {
	if o != nil && !IsNil(o.Search) {
		return true
	}

	return false
}

// SetSearch gets a reference to the given string and assigns it to the Search field.
func (o *PairListRequest) SetSearch(v string) {
	o.Search = &v
}

// GetMinLiquidityUsd returns the MinLiquidityUsd field value if set, zero value otherwise.
func (o *PairListRequest) GetMinLiquidityUsd() float64 {
	if o == nil || IsNil(o.MinLiquidityUsd) {
		var ret float64
		return ret
	}
	return *o.MinLiquidityUsd
}

// GetMinLiquidityUsdOk returns a tuple with the MinLiquidityUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairListRequest) GetMinLiquidityUsdOk() (*float64, bool) {
	if o == nil || IsNil(o.MinLiquidityUsd) {
		return nil, false
	}
	return o.MinLiquidityUsd, true
}

// HasMinLiquidityUsd returns a boolean if a field has been set.
func (o *PairListRequest) HasMinLiquidityUsd() bool {
	if o != nil && !IsNil(o.MinLiquidityUsd) {
		return true
	}

	return false
}

// SetMinLiquidityUsd gets a reference to the given float64 and assigns it to the MinLiquidityUsd field.
func (o *PairListRequest) SetMinLiquidityUsd(v float64) {
	o.MinLiquidityUsd = &v
}

// GetMaxLiquidityUsd returns the MaxLiquidityUsd field value if set, zero value otherwise.
func (o *PairListRequest) GetMaxLiquidityUsd() float64 {
	if o == nil || IsNil(o.MaxLiquidityUsd) {
		var ret float64
		return ret
	}
	return *o.MaxLiquidityUsd
}

// GetMaxLiquidityUsdOk returns a tuple with the MaxLiquidityUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairListRequest) GetMaxLiquidityUsdOk() (*float64, bool) {
	if o == nil || IsNil(o.MaxLiquidityUsd) {
		return nil, false
	}
	return o.MaxLiquidityUsd, true
}

// HasMaxLiquidityUsd returns a boolean if a field has been set.
func (o *PairListRequest) HasMaxLiquidityUsd() bool {
	if o != nil && !IsNil(o.MaxLiquidityUsd) {
		return true
	}

	return false
}

// SetMaxLiquidityUsd gets a reference to the given float64 and assigns it to the MaxLiquidityUsd field.
func (o *PairListRequest) SetMaxLiquidityUsd(v float64) {
	o.MaxLiquidityUsd = &v
}

// GetDexNames returns the DexNames field value if set, zero value otherwise.
func (o *PairListRequest) GetDexNames() []string {
	if o == nil || IsNil(o.DexNames) {
		var ret []string
		return ret
	}
	return o.DexNames
}

// GetDexNamesOk returns a tuple with the DexNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairListRequest) GetDexNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.DexNames) {
		return nil, false
	}
	return o.DexNames, true
}

// HasDexNames returns a boolean if a field has been set.
func (o *PairListRequest) HasDexNames() bool {
	if o != nil && !IsNil(o.DexNames) {
		return true
	}

	return false
}

// SetDexNames gets a reference to the given []string and assigns it to the DexNames field.
func (o *PairListRequest) SetDexNames(v []string) {
	o.DexNames = v
}

// GetDexProtocols returns the DexProtocols field value if set, zero value otherwise.
func (o *PairListRequest) GetDexProtocols() []string {
	if o == nil || IsNil(o.DexProtocols) {
		var ret []string
		return ret
	}
	return o.DexProtocols
}

// GetDexProtocolsOk returns a tuple with the DexProtocols field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairListRequest) GetDexProtocolsOk() ([]string, bool) {
	if o == nil || IsNil(o.DexProtocols) {
		return nil, false
	}
	return o.DexProtocols, true
}

// HasDexProtocols returns a boolean if a field has been set.
func (o *PairListRequest) HasDexProtocols() bool {
	if o != nil && !IsNil(o.DexProtocols) {
		return true
	}

	return false
}

// SetDexProtocols gets a reference to the given []string and assigns it to the DexProtocols field.
func (o *PairListRequest) SetDexProtocols(v []string) {
	o.DexProtocols = v
}

// GetDexFactoryTypes returns the DexFactoryTypes field value if set, zero value otherwise.
func (o *PairListRequest) GetDexFactoryTypes() []string {
	if o == nil || IsNil(o.DexFactoryTypes) {
		var ret []string
		return ret
	}
	return o.DexFactoryTypes
}

// GetDexFactoryTypesOk returns a tuple with the DexFactoryTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairListRequest) GetDexFactoryTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.DexFactoryTypes) {
		return nil, false
	}
	return o.DexFactoryTypes, true
}

// HasDexFactoryTypes returns a boolean if a field has been set.
func (o *PairListRequest) HasDexFactoryTypes() bool {
	if o != nil && !IsNil(o.DexFactoryTypes) {
		return true
	}

	return false
}

// SetDexFactoryTypes gets a reference to the given []string and assigns it to the DexFactoryTypes field.
func (o *PairListRequest) SetDexFactoryTypes(v []string) {
	o.DexFactoryTypes = v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *PairListRequest) GetCursor() string {
	if o == nil || IsNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairListRequest) GetCursorOk() (*string, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *PairListRequest) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *PairListRequest) SetCursor(v string) {
	o.Cursor = &v
}

// GetCount returns the Count field value
func (o *PairListRequest) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *PairListRequest) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *PairListRequest) SetCount(v int32) {
	o.Count = v
}

func (o PairListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PairListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Networks) {
		toSerialize["networks"] = o.Networks
	}
	if !IsNil(o.SortBy) {
		toSerialize["sort_by"] = o.SortBy
	}
	if !IsNil(o.SortValue) {
		toSerialize["sort_value"] = o.SortValue
	}
	if !IsNil(o.OrderBy) {
		toSerialize["order_by"] = o.OrderBy
	}
	if !IsNil(o.Search) {
		toSerialize["search"] = o.Search
	}
	if !IsNil(o.MinLiquidityUsd) {
		toSerialize["min_liquidity_usd"] = o.MinLiquidityUsd
	}
	if !IsNil(o.MaxLiquidityUsd) {
		toSerialize["max_liquidity_usd"] = o.MaxLiquidityUsd
	}
	if !IsNil(o.DexNames) {
		toSerialize["dex_names"] = o.DexNames
	}
	if !IsNil(o.DexProtocols) {
		toSerialize["dex_protocols"] = o.DexProtocols
	}
	if !IsNil(o.DexFactoryTypes) {
		toSerialize["dex_factory_types"] = o.DexFactoryTypes
	}
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	toSerialize["count"] = o.Count
	return toSerialize, nil
}

func (o *PairListRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPairListRequest := _PairListRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPairListRequest)

	if err != nil {
		return err
	}

	*o = PairListRequest(varPairListRequest)

	return err
}

type NullablePairListRequest struct {
	value *PairListRequest
	isSet bool
}

func (v NullablePairListRequest) Get() *PairListRequest {
	return v.value
}

func (v *NullablePairListRequest) Set(val *PairListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePairListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePairListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePairListRequest(val *PairListRequest) *NullablePairListRequest {
	return &NullablePairListRequest{value: val, isSet: true}
}

func (v NullablePairListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePairListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


