/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdatePairsStatus200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePairsStatus200Response{}

// UpdatePairsStatus200Response struct for UpdatePairsStatus200Response
type UpdatePairsStatus200Response struct {
	// Successfully updated pairs
	UpdatedPairs []string `json:"updated_pairs"`
}

type _UpdatePairsStatus200Response UpdatePairsStatus200Response

// NewUpdatePairsStatus200Response instantiates a new UpdatePairsStatus200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePairsStatus200Response(updatedPairs []string) *UpdatePairsStatus200Response {
	this := UpdatePairsStatus200Response{}
	this.UpdatedPairs = updatedPairs
	return &this
}

// NewUpdatePairsStatus200ResponseWithDefaults instantiates a new UpdatePairsStatus200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePairsStatus200ResponseWithDefaults() *UpdatePairsStatus200Response {
	this := UpdatePairsStatus200Response{}
	return &this
}

// GetUpdatedPairs returns the UpdatedPairs field value
func (o *UpdatePairsStatus200Response) GetUpdatedPairs() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.UpdatedPairs
}

// GetUpdatedPairsOk returns a tuple with the UpdatedPairs field value
// and a boolean to check if the value has been set.
func (o *UpdatePairsStatus200Response) GetUpdatedPairsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedPairs, true
}

// SetUpdatedPairs sets field value
func (o *UpdatePairsStatus200Response) SetUpdatedPairs(v []string) {
	o.UpdatedPairs = v
}

func (o UpdatePairsStatus200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePairsStatus200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["updated_pairs"] = o.UpdatedPairs
	return toSerialize, nil
}

func (o *UpdatePairsStatus200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"updated_pairs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdatePairsStatus200Response := _UpdatePairsStatus200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdatePairsStatus200Response)

	if err != nil {
		return err
	}

	*o = UpdatePairsStatus200Response(varUpdatePairsStatus200Response)

	return err
}

type NullableUpdatePairsStatus200Response struct {
	value *UpdatePairsStatus200Response
	isSet bool
}

func (v NullableUpdatePairsStatus200Response) Get() *UpdatePairsStatus200Response {
	return v.value
}

func (v *NullableUpdatePairsStatus200Response) Set(val *UpdatePairsStatus200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePairsStatus200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePairsStatus200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePairsStatus200Response(val *UpdatePairsStatus200Response) *NullableUpdatePairsStatus200Response {
	return &NullableUpdatePairsStatus200Response{value: val, isSet: true}
}

func (v NullableUpdatePairsStatus200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePairsStatus200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


