/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Network type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Network{}

// Network struct for Network
type Network struct {
	Name string `json:"name"`
	ChainId int32 `json:"chain_id"`
	Dexes *int32 `json:"dexes,omitempty"`
	Pairs *int32 `json:"pairs,omitempty"`
	Tvl *string `json:"tvl,omitempty"`
}

type _Network Network

// NewNetwork instantiates a new Network object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetwork(name string, chainId int32) *Network {
	this := Network{}
	this.Name = name
	this.ChainId = chainId
	return &this
}

// NewNetworkWithDefaults instantiates a new Network object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkWithDefaults() *Network {
	this := Network{}
	return &this
}

// GetName returns the Name field value
func (o *Network) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Network) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Network) SetName(v string) {
	o.Name = v
}

// GetChainId returns the ChainId field value
func (o *Network) GetChainId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *Network) GetChainIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *Network) SetChainId(v int32) {
	o.ChainId = v
}

// GetDexes returns the Dexes field value if set, zero value otherwise.
func (o *Network) GetDexes() int32 {
	if o == nil || IsNil(o.Dexes) {
		var ret int32
		return ret
	}
	return *o.Dexes
}

// GetDexesOk returns a tuple with the Dexes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Network) GetDexesOk() (*int32, bool) {
	if o == nil || IsNil(o.Dexes) {
		return nil, false
	}
	return o.Dexes, true
}

// HasDexes returns a boolean if a field has been set.
func (o *Network) HasDexes() bool {
	if o != nil && !IsNil(o.Dexes) {
		return true
	}

	return false
}

// SetDexes gets a reference to the given int32 and assigns it to the Dexes field.
func (o *Network) SetDexes(v int32) {
	o.Dexes = &v
}

// GetPairs returns the Pairs field value if set, zero value otherwise.
func (o *Network) GetPairs() int32 {
	if o == nil || IsNil(o.Pairs) {
		var ret int32
		return ret
	}
	return *o.Pairs
}

// GetPairsOk returns a tuple with the Pairs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Network) GetPairsOk() (*int32, bool) {
	if o == nil || IsNil(o.Pairs) {
		return nil, false
	}
	return o.Pairs, true
}

// HasPairs returns a boolean if a field has been set.
func (o *Network) HasPairs() bool {
	if o != nil && !IsNil(o.Pairs) {
		return true
	}

	return false
}

// SetPairs gets a reference to the given int32 and assigns it to the Pairs field.
func (o *Network) SetPairs(v int32) {
	o.Pairs = &v
}

// GetTvl returns the Tvl field value if set, zero value otherwise.
func (o *Network) GetTvl() string {
	if o == nil || IsNil(o.Tvl) {
		var ret string
		return ret
	}
	return *o.Tvl
}

// GetTvlOk returns a tuple with the Tvl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Network) GetTvlOk() (*string, bool) {
	if o == nil || IsNil(o.Tvl) {
		return nil, false
	}
	return o.Tvl, true
}

// HasTvl returns a boolean if a field has been set.
func (o *Network) HasTvl() bool {
	if o != nil && !IsNil(o.Tvl) {
		return true
	}

	return false
}

// SetTvl gets a reference to the given string and assigns it to the Tvl field.
func (o *Network) SetTvl(v string) {
	o.Tvl = &v
}

func (o Network) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Network) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["chain_id"] = o.ChainId
	if !IsNil(o.Dexes) {
		toSerialize["dexes"] = o.Dexes
	}
	if !IsNil(o.Pairs) {
		toSerialize["pairs"] = o.Pairs
	}
	if !IsNil(o.Tvl) {
		toSerialize["tvl"] = o.Tvl
	}
	return toSerialize, nil
}

func (o *Network) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"chain_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetwork := _Network{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNetwork)

	if err != nil {
		return err
	}

	*o = Network(varNetwork)

	return err
}

type NullableNetwork struct {
	value *Network
	isSet bool
}

func (v NullableNetwork) Get() *Network {
	return v.value
}

func (v *NullableNetwork) Set(val *Network) {
	v.value = val
	v.isSet = true
}

func (v NullableNetwork) IsSet() bool {
	return v.isSet
}

func (v *NullableNetwork) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetwork(val *Network) *NullableNetwork {
	return &NullableNetwork{value: val, isSet: true}
}

func (v NullableNetwork) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetwork) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


