/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NftAssetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NftAssetRequest{}

// NftAssetRequest struct for NftAssetRequest
type NftAssetRequest struct {
	Address string `json:"address"`
	TokenId string `json:"token_id"`
	Network NetworkType `json:"network"`
}

type _NftAssetRequest NftAssetRequest

// NewNftAssetRequest instantiates a new NftAssetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNftAssetRequest(address string, tokenId string, network NetworkType) *NftAssetRequest {
	this := NftAssetRequest{}
	this.Address = address
	this.TokenId = tokenId
	this.Network = network
	return &this
}

// NewNftAssetRequestWithDefaults instantiates a new NftAssetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNftAssetRequestWithDefaults() *NftAssetRequest {
	this := NftAssetRequest{}
	return &this
}

// GetAddress returns the Address field value
func (o *NftAssetRequest) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *NftAssetRequest) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *NftAssetRequest) SetAddress(v string) {
	o.Address = v
}

// GetTokenId returns the TokenId field value
func (o *NftAssetRequest) GetTokenId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value
// and a boolean to check if the value has been set.
func (o *NftAssetRequest) GetTokenIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenId, true
}

// SetTokenId sets field value
func (o *NftAssetRequest) SetTokenId(v string) {
	o.TokenId = v
}

// GetNetwork returns the Network field value
func (o *NftAssetRequest) GetNetwork() NetworkType {
	if o == nil {
		var ret NetworkType
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *NftAssetRequest) GetNetworkOk() (*NetworkType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *NftAssetRequest) SetNetwork(v NetworkType) {
	o.Network = v
}

func (o NftAssetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NftAssetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["token_id"] = o.TokenId
	toSerialize["network"] = o.Network
	return toSerialize, nil
}

func (o *NftAssetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"token_id",
		"network",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNftAssetRequest := _NftAssetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNftAssetRequest)

	if err != nil {
		return err
	}

	*o = NftAssetRequest(varNftAssetRequest)

	return err
}

type NullableNftAssetRequest struct {
	value *NftAssetRequest
	isSet bool
}

func (v NullableNftAssetRequest) Get() *NftAssetRequest {
	return v.value
}

func (v *NullableNftAssetRequest) Set(val *NftAssetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNftAssetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNftAssetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNftAssetRequest(val *NftAssetRequest) *NullableNftAssetRequest {
	return &NullableNftAssetRequest{value: val, isSet: true}
}

func (v NullableNftAssetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNftAssetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


