/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TokenInfo400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenInfo400Response{}

// TokenInfo400Response struct for TokenInfo400Response
type TokenInfo400Response struct {
	// A human-readable explanation specific to this occurrence of the problem
	Message string `json:"message"`
	// The HTTP status code for this occurrence of the problem
	Status int32 `json:"status"`
}

type _TokenInfo400Response TokenInfo400Response

// NewTokenInfo400Response instantiates a new TokenInfo400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenInfo400Response(message string, status int32) *TokenInfo400Response {
	this := TokenInfo400Response{}
	this.Message = message
	this.Status = status
	return &this
}

// NewTokenInfo400ResponseWithDefaults instantiates a new TokenInfo400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenInfo400ResponseWithDefaults() *TokenInfo400Response {
	this := TokenInfo400Response{}
	return &this
}

// GetMessage returns the Message field value
func (o *TokenInfo400Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *TokenInfo400Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *TokenInfo400Response) SetMessage(v string) {
	o.Message = v
}

// GetStatus returns the Status field value
func (o *TokenInfo400Response) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TokenInfo400Response) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TokenInfo400Response) SetStatus(v int32) {
	o.Status = v
}

func (o TokenInfo400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenInfo400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *TokenInfo400Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenInfo400Response := _TokenInfo400Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokenInfo400Response)

	if err != nil {
		return err
	}

	*o = TokenInfo400Response(varTokenInfo400Response)

	return err
}

type NullableTokenInfo400Response struct {
	value *TokenInfo400Response
	isSet bool
}

func (v NullableTokenInfo400Response) Get() *TokenInfo400Response {
	return v.value
}

func (v *NullableTokenInfo400Response) Set(val *TokenInfo400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenInfo400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenInfo400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenInfo400Response(val *TokenInfo400Response) *NullableTokenInfo400Response {
	return &NullableTokenInfo400Response{value: val, isSet: true}
}

func (v NullableTokenInfo400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenInfo400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


