/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProtocolInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProtocolInfo{}

// ProtocolInfo struct for ProtocolInfo
type ProtocolInfo struct {
	// The unique identifier of the protocol (e.g., UniswapV2Factory).
	Id *string `json:"id,omitempty"`
	// Total value locked in the protocol.
	Tvl float64 `json:"tvl"`
	// Average liquidity found per pair within this protocol.
	AverageLiquidityPerPair float64 `json:"average_liquidity_per_pair"`
	// Maximum liquidity found in any single pair within this protocol.
	MaxLiquidity float64 `json:"max_liquidity"`
	// The total number of pairs available in this protocol.
	CountPairs int32 `json:"count_pairs"`
}

type _ProtocolInfo ProtocolInfo

// NewProtocolInfo instantiates a new ProtocolInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProtocolInfo(tvl float64, averageLiquidityPerPair float64, maxLiquidity float64, countPairs int32) *ProtocolInfo {
	this := ProtocolInfo{}
	this.Tvl = tvl
	this.AverageLiquidityPerPair = averageLiquidityPerPair
	this.MaxLiquidity = maxLiquidity
	this.CountPairs = countPairs
	return &this
}

// NewProtocolInfoWithDefaults instantiates a new ProtocolInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProtocolInfoWithDefaults() *ProtocolInfo {
	this := ProtocolInfo{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProtocolInfo) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtocolInfo) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProtocolInfo) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProtocolInfo) SetId(v string) {
	o.Id = &v
}

// GetTvl returns the Tvl field value
func (o *ProtocolInfo) GetTvl() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Tvl
}

// GetTvlOk returns a tuple with the Tvl field value
// and a boolean to check if the value has been set.
func (o *ProtocolInfo) GetTvlOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tvl, true
}

// SetTvl sets field value
func (o *ProtocolInfo) SetTvl(v float64) {
	o.Tvl = v
}

// GetAverageLiquidityPerPair returns the AverageLiquidityPerPair field value
func (o *ProtocolInfo) GetAverageLiquidityPerPair() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.AverageLiquidityPerPair
}

// GetAverageLiquidityPerPairOk returns a tuple with the AverageLiquidityPerPair field value
// and a boolean to check if the value has been set.
func (o *ProtocolInfo) GetAverageLiquidityPerPairOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AverageLiquidityPerPair, true
}

// SetAverageLiquidityPerPair sets field value
func (o *ProtocolInfo) SetAverageLiquidityPerPair(v float64) {
	o.AverageLiquidityPerPair = v
}

// GetMaxLiquidity returns the MaxLiquidity field value
func (o *ProtocolInfo) GetMaxLiquidity() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MaxLiquidity
}

// GetMaxLiquidityOk returns a tuple with the MaxLiquidity field value
// and a boolean to check if the value has been set.
func (o *ProtocolInfo) GetMaxLiquidityOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxLiquidity, true
}

// SetMaxLiquidity sets field value
func (o *ProtocolInfo) SetMaxLiquidity(v float64) {
	o.MaxLiquidity = v
}

// GetCountPairs returns the CountPairs field value
func (o *ProtocolInfo) GetCountPairs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CountPairs
}

// GetCountPairsOk returns a tuple with the CountPairs field value
// and a boolean to check if the value has been set.
func (o *ProtocolInfo) GetCountPairsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountPairs, true
}

// SetCountPairs sets field value
func (o *ProtocolInfo) SetCountPairs(v int32) {
	o.CountPairs = v
}

func (o ProtocolInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProtocolInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["tvl"] = o.Tvl
	toSerialize["average_liquidity_per_pair"] = o.AverageLiquidityPerPair
	toSerialize["max_liquidity"] = o.MaxLiquidity
	toSerialize["count_pairs"] = o.CountPairs
	return toSerialize, nil
}

func (o *ProtocolInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tvl",
		"average_liquidity_per_pair",
		"max_liquidity",
		"count_pairs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProtocolInfo := _ProtocolInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProtocolInfo)

	if err != nil {
		return err
	}

	*o = ProtocolInfo(varProtocolInfo)

	return err
}

type NullableProtocolInfo struct {
	value *ProtocolInfo
	isSet bool
}

func (v NullableProtocolInfo) Get() *ProtocolInfo {
	return v.value
}

func (v *NullableProtocolInfo) Set(val *ProtocolInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableProtocolInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableProtocolInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProtocolInfo(val *ProtocolInfo) *NullableProtocolInfo {
	return &NullableProtocolInfo{value: val, isSet: true}
}

func (v NullableProtocolInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProtocolInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


