/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NftCollectionListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NftCollectionListRequest{}

// NftCollectionListRequest struct for NftCollectionListRequest
type NftCollectionListRequest struct {
	Network NetworkType `json:"network"`
	Cursor *string `json:"cursor,omitempty"`
	Count int32 `json:"count"`
}

type _NftCollectionListRequest NftCollectionListRequest

// NewNftCollectionListRequest instantiates a new NftCollectionListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNftCollectionListRequest(network NetworkType, count int32) *NftCollectionListRequest {
	this := NftCollectionListRequest{}
	this.Network = network
	this.Count = count
	return &this
}

// NewNftCollectionListRequestWithDefaults instantiates a new NftCollectionListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNftCollectionListRequestWithDefaults() *NftCollectionListRequest {
	this := NftCollectionListRequest{}
	var count int32 = 10
	this.Count = count
	return &this
}

// GetNetwork returns the Network field value
func (o *NftCollectionListRequest) GetNetwork() NetworkType {
	if o == nil {
		var ret NetworkType
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *NftCollectionListRequest) GetNetworkOk() (*NetworkType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *NftCollectionListRequest) SetNetwork(v NetworkType) {
	o.Network = v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *NftCollectionListRequest) GetCursor() string {
	if o == nil || IsNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NftCollectionListRequest) GetCursorOk() (*string, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *NftCollectionListRequest) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *NftCollectionListRequest) SetCursor(v string) {
	o.Cursor = &v
}

// GetCount returns the Count field value
func (o *NftCollectionListRequest) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *NftCollectionListRequest) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *NftCollectionListRequest) SetCount(v int32) {
	o.Count = v
}

func (o NftCollectionListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NftCollectionListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["network"] = o.Network
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	toSerialize["count"] = o.Count
	return toSerialize, nil
}

func (o *NftCollectionListRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"network",
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNftCollectionListRequest := _NftCollectionListRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNftCollectionListRequest)

	if err != nil {
		return err
	}

	*o = NftCollectionListRequest(varNftCollectionListRequest)

	return err
}

type NullableNftCollectionListRequest struct {
	value *NftCollectionListRequest
	isSet bool
}

func (v NullableNftCollectionListRequest) Get() *NftCollectionListRequest {
	return v.value
}

func (v *NullableNftCollectionListRequest) Set(val *NftCollectionListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNftCollectionListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNftCollectionListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNftCollectionListRequest(val *NftCollectionListRequest) *NullableNftCollectionListRequest {
	return &NullableNftCollectionListRequest{value: val, isSet: true}
}

func (v NullableNftCollectionListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNftCollectionListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


