/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TokenInfoPriceChangesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenInfoPriceChangesInner{}

// TokenInfoPriceChangesInner struct for TokenInfoPriceChangesInner
type TokenInfoPriceChangesInner struct {
	Resolution *ResolutionType `json:"resolution,omitempty"`
	OpenPrice *float32 `json:"open_price,omitempty"`
	ClosePrice *float32 `json:"close_price,omitempty"`
	HighPrice *float32 `json:"high_price,omitempty"`
	LowPrice *float32 `json:"low_price,omitempty"`
	Volume *float32 `json:"volume,omitempty"`
	ChangePct *float32 `json:"change_pct,omitempty"`
	VolatilityPct *float32 `json:"volatility_pct,omitempty"`
}

// NewTokenInfoPriceChangesInner instantiates a new TokenInfoPriceChangesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenInfoPriceChangesInner() *TokenInfoPriceChangesInner {
	this := TokenInfoPriceChangesInner{}
	return &this
}

// NewTokenInfoPriceChangesInnerWithDefaults instantiates a new TokenInfoPriceChangesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenInfoPriceChangesInnerWithDefaults() *TokenInfoPriceChangesInner {
	this := TokenInfoPriceChangesInner{}
	return &this
}

// GetResolution returns the Resolution field value if set, zero value otherwise.
func (o *TokenInfoPriceChangesInner) GetResolution() ResolutionType {
	if o == nil || IsNil(o.Resolution) {
		var ret ResolutionType
		return ret
	}
	return *o.Resolution
}

// GetResolutionOk returns a tuple with the Resolution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfoPriceChangesInner) GetResolutionOk() (*ResolutionType, bool) {
	if o == nil || IsNil(o.Resolution) {
		return nil, false
	}
	return o.Resolution, true
}

// HasResolution returns a boolean if a field has been set.
func (o *TokenInfoPriceChangesInner) HasResolution() bool {
	if o != nil && !IsNil(o.Resolution) {
		return true
	}

	return false
}

// SetResolution gets a reference to the given ResolutionType and assigns it to the Resolution field.
func (o *TokenInfoPriceChangesInner) SetResolution(v ResolutionType) {
	o.Resolution = &v
}

// GetOpenPrice returns the OpenPrice field value if set, zero value otherwise.
func (o *TokenInfoPriceChangesInner) GetOpenPrice() float32 {
	if o == nil || IsNil(o.OpenPrice) {
		var ret float32
		return ret
	}
	return *o.OpenPrice
}

// GetOpenPriceOk returns a tuple with the OpenPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfoPriceChangesInner) GetOpenPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.OpenPrice) {
		return nil, false
	}
	return o.OpenPrice, true
}

// HasOpenPrice returns a boolean if a field has been set.
func (o *TokenInfoPriceChangesInner) HasOpenPrice() bool {
	if o != nil && !IsNil(o.OpenPrice) {
		return true
	}

	return false
}

// SetOpenPrice gets a reference to the given float32 and assigns it to the OpenPrice field.
func (o *TokenInfoPriceChangesInner) SetOpenPrice(v float32) {
	o.OpenPrice = &v
}

// GetClosePrice returns the ClosePrice field value if set, zero value otherwise.
func (o *TokenInfoPriceChangesInner) GetClosePrice() float32 {
	if o == nil || IsNil(o.ClosePrice) {
		var ret float32
		return ret
	}
	return *o.ClosePrice
}

// GetClosePriceOk returns a tuple with the ClosePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfoPriceChangesInner) GetClosePriceOk() (*float32, bool) {
	if o == nil || IsNil(o.ClosePrice) {
		return nil, false
	}
	return o.ClosePrice, true
}

// HasClosePrice returns a boolean if a field has been set.
func (o *TokenInfoPriceChangesInner) HasClosePrice() bool {
	if o != nil && !IsNil(o.ClosePrice) {
		return true
	}

	return false
}

// SetClosePrice gets a reference to the given float32 and assigns it to the ClosePrice field.
func (o *TokenInfoPriceChangesInner) SetClosePrice(v float32) {
	o.ClosePrice = &v
}

// GetHighPrice returns the HighPrice field value if set, zero value otherwise.
func (o *TokenInfoPriceChangesInner) GetHighPrice() float32 {
	if o == nil || IsNil(o.HighPrice) {
		var ret float32
		return ret
	}
	return *o.HighPrice
}

// GetHighPriceOk returns a tuple with the HighPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfoPriceChangesInner) GetHighPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.HighPrice) {
		return nil, false
	}
	return o.HighPrice, true
}

// HasHighPrice returns a boolean if a field has been set.
func (o *TokenInfoPriceChangesInner) HasHighPrice() bool {
	if o != nil && !IsNil(o.HighPrice) {
		return true
	}

	return false
}

// SetHighPrice gets a reference to the given float32 and assigns it to the HighPrice field.
func (o *TokenInfoPriceChangesInner) SetHighPrice(v float32) {
	o.HighPrice = &v
}

// GetLowPrice returns the LowPrice field value if set, zero value otherwise.
func (o *TokenInfoPriceChangesInner) GetLowPrice() float32 {
	if o == nil || IsNil(o.LowPrice) {
		var ret float32
		return ret
	}
	return *o.LowPrice
}

// GetLowPriceOk returns a tuple with the LowPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfoPriceChangesInner) GetLowPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.LowPrice) {
		return nil, false
	}
	return o.LowPrice, true
}

// HasLowPrice returns a boolean if a field has been set.
func (o *TokenInfoPriceChangesInner) HasLowPrice() bool {
	if o != nil && !IsNil(o.LowPrice) {
		return true
	}

	return false
}

// SetLowPrice gets a reference to the given float32 and assigns it to the LowPrice field.
func (o *TokenInfoPriceChangesInner) SetLowPrice(v float32) {
	o.LowPrice = &v
}

// GetVolume returns the Volume field value if set, zero value otherwise.
func (o *TokenInfoPriceChangesInner) GetVolume() float32 {
	if o == nil || IsNil(o.Volume) {
		var ret float32
		return ret
	}
	return *o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfoPriceChangesInner) GetVolumeOk() (*float32, bool) {
	if o == nil || IsNil(o.Volume) {
		return nil, false
	}
	return o.Volume, true
}

// HasVolume returns a boolean if a field has been set.
func (o *TokenInfoPriceChangesInner) HasVolume() bool {
	if o != nil && !IsNil(o.Volume) {
		return true
	}

	return false
}

// SetVolume gets a reference to the given float32 and assigns it to the Volume field.
func (o *TokenInfoPriceChangesInner) SetVolume(v float32) {
	o.Volume = &v
}

// GetChangePct returns the ChangePct field value if set, zero value otherwise.
func (o *TokenInfoPriceChangesInner) GetChangePct() float32 {
	if o == nil || IsNil(o.ChangePct) {
		var ret float32
		return ret
	}
	return *o.ChangePct
}

// GetChangePctOk returns a tuple with the ChangePct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfoPriceChangesInner) GetChangePctOk() (*float32, bool) {
	if o == nil || IsNil(o.ChangePct) {
		return nil, false
	}
	return o.ChangePct, true
}

// HasChangePct returns a boolean if a field has been set.
func (o *TokenInfoPriceChangesInner) HasChangePct() bool {
	if o != nil && !IsNil(o.ChangePct) {
		return true
	}

	return false
}

// SetChangePct gets a reference to the given float32 and assigns it to the ChangePct field.
func (o *TokenInfoPriceChangesInner) SetChangePct(v float32) {
	o.ChangePct = &v
}

// GetVolatilityPct returns the VolatilityPct field value if set, zero value otherwise.
func (o *TokenInfoPriceChangesInner) GetVolatilityPct() float32 {
	if o == nil || IsNil(o.VolatilityPct) {
		var ret float32
		return ret
	}
	return *o.VolatilityPct
}

// GetVolatilityPctOk returns a tuple with the VolatilityPct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInfoPriceChangesInner) GetVolatilityPctOk() (*float32, bool) {
	if o == nil || IsNil(o.VolatilityPct) {
		return nil, false
	}
	return o.VolatilityPct, true
}

// HasVolatilityPct returns a boolean if a field has been set.
func (o *TokenInfoPriceChangesInner) HasVolatilityPct() bool {
	if o != nil && !IsNil(o.VolatilityPct) {
		return true
	}

	return false
}

// SetVolatilityPct gets a reference to the given float32 and assigns it to the VolatilityPct field.
func (o *TokenInfoPriceChangesInner) SetVolatilityPct(v float32) {
	o.VolatilityPct = &v
}

func (o TokenInfoPriceChangesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenInfoPriceChangesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Resolution) {
		toSerialize["resolution"] = o.Resolution
	}
	if !IsNil(o.OpenPrice) {
		toSerialize["open_price"] = o.OpenPrice
	}
	if !IsNil(o.ClosePrice) {
		toSerialize["close_price"] = o.ClosePrice
	}
	if !IsNil(o.HighPrice) {
		toSerialize["high_price"] = o.HighPrice
	}
	if !IsNil(o.LowPrice) {
		toSerialize["low_price"] = o.LowPrice
	}
	if !IsNil(o.Volume) {
		toSerialize["volume"] = o.Volume
	}
	if !IsNil(o.ChangePct) {
		toSerialize["change_pct"] = o.ChangePct
	}
	if !IsNil(o.VolatilityPct) {
		toSerialize["volatility_pct"] = o.VolatilityPct
	}
	return toSerialize, nil
}

type NullableTokenInfoPriceChangesInner struct {
	value *TokenInfoPriceChangesInner
	isSet bool
}

func (v NullableTokenInfoPriceChangesInner) Get() *TokenInfoPriceChangesInner {
	return v.value
}

func (v *NullableTokenInfoPriceChangesInner) Set(val *TokenInfoPriceChangesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenInfoPriceChangesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenInfoPriceChangesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenInfoPriceChangesInner(val *TokenInfoPriceChangesInner) *NullableTokenInfoPriceChangesInner {
	return &NullableTokenInfoPriceChangesInner{value: val, isSet: true}
}

func (v NullableTokenInfoPriceChangesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenInfoPriceChangesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


