/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PairInfoTxn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PairInfoTxn{}

// PairInfoTxn struct for PairInfoTxn
type PairInfoTxn struct {
	M5 TxnPairStat `json:"m5"`
	H1 TxnPairStat `json:"h1"`
	H6 TxnPairStat `json:"h6"`
	H24 TxnPairStat `json:"h24"`
}

type _PairInfoTxn PairInfoTxn

// NewPairInfoTxn instantiates a new PairInfoTxn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPairInfoTxn(m5 TxnPairStat, h1 TxnPairStat, h6 TxnPairStat, h24 TxnPairStat) *PairInfoTxn {
	this := PairInfoTxn{}
	this.M5 = m5
	this.H1 = h1
	this.H6 = h6
	this.H24 = h24
	return &this
}

// NewPairInfoTxnWithDefaults instantiates a new PairInfoTxn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPairInfoTxnWithDefaults() *PairInfoTxn {
	this := PairInfoTxn{}
	return &this
}

// GetM5 returns the M5 field value
func (o *PairInfoTxn) GetM5() TxnPairStat {
	if o == nil {
		var ret TxnPairStat
		return ret
	}

	return o.M5
}

// GetM5Ok returns a tuple with the M5 field value
// and a boolean to check if the value has been set.
func (o *PairInfoTxn) GetM5Ok() (*TxnPairStat, bool) {
	if o == nil {
		return nil, false
	}
	return &o.M5, true
}

// SetM5 sets field value
func (o *PairInfoTxn) SetM5(v TxnPairStat) {
	o.M5 = v
}

// GetH1 returns the H1 field value
func (o *PairInfoTxn) GetH1() TxnPairStat {
	if o == nil {
		var ret TxnPairStat
		return ret
	}

	return o.H1
}

// GetH1Ok returns a tuple with the H1 field value
// and a boolean to check if the value has been set.
func (o *PairInfoTxn) GetH1Ok() (*TxnPairStat, bool) {
	if o == nil {
		return nil, false
	}
	return &o.H1, true
}

// SetH1 sets field value
func (o *PairInfoTxn) SetH1(v TxnPairStat) {
	o.H1 = v
}

// GetH6 returns the H6 field value
func (o *PairInfoTxn) GetH6() TxnPairStat {
	if o == nil {
		var ret TxnPairStat
		return ret
	}

	return o.H6
}

// GetH6Ok returns a tuple with the H6 field value
// and a boolean to check if the value has been set.
func (o *PairInfoTxn) GetH6Ok() (*TxnPairStat, bool) {
	if o == nil {
		return nil, false
	}
	return &o.H6, true
}

// SetH6 sets field value
func (o *PairInfoTxn) SetH6(v TxnPairStat) {
	o.H6 = v
}

// GetH24 returns the H24 field value
func (o *PairInfoTxn) GetH24() TxnPairStat {
	if o == nil {
		var ret TxnPairStat
		return ret
	}

	return o.H24
}

// GetH24Ok returns a tuple with the H24 field value
// and a boolean to check if the value has been set.
func (o *PairInfoTxn) GetH24Ok() (*TxnPairStat, bool) {
	if o == nil {
		return nil, false
	}
	return &o.H24, true
}

// SetH24 sets field value
func (o *PairInfoTxn) SetH24(v TxnPairStat) {
	o.H24 = v
}

func (o PairInfoTxn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PairInfoTxn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["m5"] = o.M5
	toSerialize["h1"] = o.H1
	toSerialize["h6"] = o.H6
	toSerialize["h24"] = o.H24
	return toSerialize, nil
}

func (o *PairInfoTxn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"m5",
		"h1",
		"h6",
		"h24",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPairInfoTxn := _PairInfoTxn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPairInfoTxn)

	if err != nil {
		return err
	}

	*o = PairInfoTxn(varPairInfoTxn)

	return err
}

type NullablePairInfoTxn struct {
	value *PairInfoTxn
	isSet bool
}

func (v NullablePairInfoTxn) Get() *PairInfoTxn {
	return v.value
}

func (v *NullablePairInfoTxn) Set(val *PairInfoTxn) {
	v.value = val
	v.isSet = true
}

func (v NullablePairInfoTxn) IsSet() bool {
	return v.isSet
}

func (v *NullablePairInfoTxn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePairInfoTxn(val *PairInfoTxn) *NullablePairInfoTxn {
	return &NullablePairInfoTxn{value: val, isSet: true}
}

func (v NullablePairInfoTxn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePairInfoTxn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


