/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EthereumTxData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EthereumTxData{}

// EthereumTxData struct for EthereumTxData
type EthereumTxData struct {
	BlockNumber int32 `json:"block_number"`
	LogIndex int32 `json:"log_index"`
	GasUsed int32 `json:"gas_used"`
	FeeUsd float32 `json:"fee_usd"`
}

type _EthereumTxData EthereumTxData

// NewEthereumTxData instantiates a new EthereumTxData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEthereumTxData(blockNumber int32, logIndex int32, gasUsed int32, feeUsd float32) *EthereumTxData {
	this := EthereumTxData{}
	this.BlockNumber = blockNumber
	this.LogIndex = logIndex
	this.GasUsed = gasUsed
	this.FeeUsd = feeUsd
	return &this
}

// NewEthereumTxDataWithDefaults instantiates a new EthereumTxData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEthereumTxDataWithDefaults() *EthereumTxData {
	this := EthereumTxData{}
	return &this
}

// GetBlockNumber returns the BlockNumber field value
func (o *EthereumTxData) GetBlockNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BlockNumber
}

// GetBlockNumberOk returns a tuple with the BlockNumber field value
// and a boolean to check if the value has been set.
func (o *EthereumTxData) GetBlockNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlockNumber, true
}

// SetBlockNumber sets field value
func (o *EthereumTxData) SetBlockNumber(v int32) {
	o.BlockNumber = v
}

// GetLogIndex returns the LogIndex field value
func (o *EthereumTxData) GetLogIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LogIndex
}

// GetLogIndexOk returns a tuple with the LogIndex field value
// and a boolean to check if the value has been set.
func (o *EthereumTxData) GetLogIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogIndex, true
}

// SetLogIndex sets field value
func (o *EthereumTxData) SetLogIndex(v int32) {
	o.LogIndex = v
}

// GetGasUsed returns the GasUsed field value
func (o *EthereumTxData) GetGasUsed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GasUsed
}

// GetGasUsedOk returns a tuple with the GasUsed field value
// and a boolean to check if the value has been set.
func (o *EthereumTxData) GetGasUsedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GasUsed, true
}

// SetGasUsed sets field value
func (o *EthereumTxData) SetGasUsed(v int32) {
	o.GasUsed = v
}

// GetFeeUsd returns the FeeUsd field value
func (o *EthereumTxData) GetFeeUsd() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.FeeUsd
}

// GetFeeUsdOk returns a tuple with the FeeUsd field value
// and a boolean to check if the value has been set.
func (o *EthereumTxData) GetFeeUsdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeeUsd, true
}

// SetFeeUsd sets field value
func (o *EthereumTxData) SetFeeUsd(v float32) {
	o.FeeUsd = v
}

func (o EthereumTxData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EthereumTxData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["block_number"] = o.BlockNumber
	toSerialize["log_index"] = o.LogIndex
	toSerialize["gas_used"] = o.GasUsed
	toSerialize["fee_usd"] = o.FeeUsd
	return toSerialize, nil
}

func (o *EthereumTxData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"block_number",
		"log_index",
		"gas_used",
		"fee_usd",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEthereumTxData := _EthereumTxData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEthereumTxData)

	if err != nil {
		return err
	}

	*o = EthereumTxData(varEthereumTxData)

	return err
}

type NullableEthereumTxData struct {
	value *EthereumTxData
	isSet bool
}

func (v NullableEthereumTxData) Get() *EthereumTxData {
	return v.value
}

func (v *NullableEthereumTxData) Set(val *EthereumTxData) {
	v.value = val
	v.isSet = true
}

func (v NullableEthereumTxData) IsSet() bool {
	return v.isSet
}

func (v *NullableEthereumTxData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEthereumTxData(val *EthereumTxData) *NullableEthereumTxData {
	return &NullableEthereumTxData{value: val, isSet: true}
}

func (v NullableEthereumTxData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEthereumTxData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


