/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RouterTxArgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RouterTxArgs{}

// RouterTxArgs struct for RouterTxArgs
type RouterTxArgs struct {
	ToAddress string `json:"to_address"`
	AmountIn string `json:"amount_in"`
	MinimumAmountOut string `json:"minimum_amount_out"`
	ChainId int32 `json:"chain_id"`
	// max gas limit for router swap
	GasLimit int32 `json:"gas_limit"`
	// msg.value for router if need swap ETH to WETH and etc...
	Value string `json:"value"`
}

type _RouterTxArgs RouterTxArgs

// NewRouterTxArgs instantiates a new RouterTxArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRouterTxArgs(toAddress string, amountIn string, minimumAmountOut string, chainId int32, gasLimit int32, value string) *RouterTxArgs {
	this := RouterTxArgs{}
	this.ToAddress = toAddress
	this.AmountIn = amountIn
	this.MinimumAmountOut = minimumAmountOut
	this.ChainId = chainId
	this.GasLimit = gasLimit
	this.Value = value
	return &this
}

// NewRouterTxArgsWithDefaults instantiates a new RouterTxArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRouterTxArgsWithDefaults() *RouterTxArgs {
	this := RouterTxArgs{}
	return &this
}

// GetToAddress returns the ToAddress field value
func (o *RouterTxArgs) GetToAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToAddress
}

// GetToAddressOk returns a tuple with the ToAddress field value
// and a boolean to check if the value has been set.
func (o *RouterTxArgs) GetToAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToAddress, true
}

// SetToAddress sets field value
func (o *RouterTxArgs) SetToAddress(v string) {
	o.ToAddress = v
}

// GetAmountIn returns the AmountIn field value
func (o *RouterTxArgs) GetAmountIn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AmountIn
}

// GetAmountInOk returns a tuple with the AmountIn field value
// and a boolean to check if the value has been set.
func (o *RouterTxArgs) GetAmountInOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountIn, true
}

// SetAmountIn sets field value
func (o *RouterTxArgs) SetAmountIn(v string) {
	o.AmountIn = v
}

// GetMinimumAmountOut returns the MinimumAmountOut field value
func (o *RouterTxArgs) GetMinimumAmountOut() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MinimumAmountOut
}

// GetMinimumAmountOutOk returns a tuple with the MinimumAmountOut field value
// and a boolean to check if the value has been set.
func (o *RouterTxArgs) GetMinimumAmountOutOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinimumAmountOut, true
}

// SetMinimumAmountOut sets field value
func (o *RouterTxArgs) SetMinimumAmountOut(v string) {
	o.MinimumAmountOut = v
}

// GetChainId returns the ChainId field value
func (o *RouterTxArgs) GetChainId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *RouterTxArgs) GetChainIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *RouterTxArgs) SetChainId(v int32) {
	o.ChainId = v
}

// GetGasLimit returns the GasLimit field value
func (o *RouterTxArgs) GetGasLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GasLimit
}

// GetGasLimitOk returns a tuple with the GasLimit field value
// and a boolean to check if the value has been set.
func (o *RouterTxArgs) GetGasLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GasLimit, true
}

// SetGasLimit sets field value
func (o *RouterTxArgs) SetGasLimit(v int32) {
	o.GasLimit = v
}

// GetValue returns the Value field value
func (o *RouterTxArgs) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *RouterTxArgs) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *RouterTxArgs) SetValue(v string) {
	o.Value = v
}

func (o RouterTxArgs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RouterTxArgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["to_address"] = o.ToAddress
	toSerialize["amount_in"] = o.AmountIn
	toSerialize["minimum_amount_out"] = o.MinimumAmountOut
	toSerialize["chain_id"] = o.ChainId
	toSerialize["gas_limit"] = o.GasLimit
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *RouterTxArgs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"to_address",
		"amount_in",
		"minimum_amount_out",
		"chain_id",
		"gas_limit",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRouterTxArgs := _RouterTxArgs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRouterTxArgs)

	if err != nil {
		return err
	}

	*o = RouterTxArgs(varRouterTxArgs)

	return err
}

type NullableRouterTxArgs struct {
	value *RouterTxArgs
	isSet bool
}

func (v NullableRouterTxArgs) Get() *RouterTxArgs {
	return v.value
}

func (v *NullableRouterTxArgs) Set(val *RouterTxArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableRouterTxArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableRouterTxArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRouterTxArgs(val *RouterTxArgs) *NullableRouterTxArgs {
	return &NullableRouterTxArgs{value: val, isSet: true}
}

func (v NullableRouterTxArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRouterTxArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


