/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Dex type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Dex{}

// Dex struct for Dex
type Dex struct {
	Name string `json:"name"`
	Factory string `json:"factory"`
	ChainId int32 `json:"chain_id"`
	LpTokenSymbol string `json:"lp_token_symbol"`
}

type _Dex Dex

// NewDex instantiates a new Dex object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDex(name string, factory string, chainId int32, lpTokenSymbol string) *Dex {
	this := Dex{}
	this.Name = name
	this.Factory = factory
	this.ChainId = chainId
	this.LpTokenSymbol = lpTokenSymbol
	return &this
}

// NewDexWithDefaults instantiates a new Dex object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDexWithDefaults() *Dex {
	this := Dex{}
	return &this
}

// GetName returns the Name field value
func (o *Dex) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Dex) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Dex) SetName(v string) {
	o.Name = v
}

// GetFactory returns the Factory field value
func (o *Dex) GetFactory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Factory
}

// GetFactoryOk returns a tuple with the Factory field value
// and a boolean to check if the value has been set.
func (o *Dex) GetFactoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Factory, true
}

// SetFactory sets field value
func (o *Dex) SetFactory(v string) {
	o.Factory = v
}

// GetChainId returns the ChainId field value
func (o *Dex) GetChainId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *Dex) GetChainIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *Dex) SetChainId(v int32) {
	o.ChainId = v
}

// GetLpTokenSymbol returns the LpTokenSymbol field value
func (o *Dex) GetLpTokenSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LpTokenSymbol
}

// GetLpTokenSymbolOk returns a tuple with the LpTokenSymbol field value
// and a boolean to check if the value has been set.
func (o *Dex) GetLpTokenSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LpTokenSymbol, true
}

// SetLpTokenSymbol sets field value
func (o *Dex) SetLpTokenSymbol(v string) {
	o.LpTokenSymbol = v
}

func (o Dex) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Dex) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["factory"] = o.Factory
	toSerialize["chain_id"] = o.ChainId
	toSerialize["lp_token_symbol"] = o.LpTokenSymbol
	return toSerialize, nil
}

func (o *Dex) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"factory",
		"chain_id",
		"lp_token_symbol",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDex := _Dex{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDex)

	if err != nil {
		return err
	}

	*o = Dex(varDex)

	return err
}

type NullableDex struct {
	value *Dex
	isSet bool
}

func (v NullableDex) Get() *Dex {
	return v.value
}

func (v *NullableDex) Set(val *Dex) {
	v.value = val
	v.isSet = true
}

func (v NullableDex) IsSet() bool {
	return v.isSet
}

func (v *NullableDex) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDex(val *Dex) *NullableDex {
	return &NullableDex{value: val, isSet: true}
}

func (v NullableDex) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDex) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


