/*
avi

avi api swagger

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DexInfoListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DexInfoListRequest{}

// DexInfoListRequest struct for DexInfoListRequest
type DexInfoListRequest struct {
	Network *NetworkType `json:"network,omitempty"`
}

// NewDexInfoListRequest instantiates a new DexInfoListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDexInfoListRequest() *DexInfoListRequest {
	this := DexInfoListRequest{}
	return &this
}

// NewDexInfoListRequestWithDefaults instantiates a new DexInfoListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDexInfoListRequestWithDefaults() *DexInfoListRequest {
	this := DexInfoListRequest{}
	return &this
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *DexInfoListRequest) GetNetwork() NetworkType {
	if o == nil || IsNil(o.Network) {
		var ret NetworkType
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DexInfoListRequest) GetNetworkOk() (*NetworkType, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *DexInfoListRequest) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given NetworkType and assigns it to the Network field.
func (o *DexInfoListRequest) SetNetwork(v NetworkType) {
	o.Network = &v
}

func (o DexInfoListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DexInfoListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	return toSerialize, nil
}

type NullableDexInfoListRequest struct {
	value *DexInfoListRequest
	isSet bool
}

func (v NullableDexInfoListRequest) Get() *DexInfoListRequest {
	return v.value
}

func (v *NullableDexInfoListRequest) Set(val *DexInfoListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDexInfoListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDexInfoListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDexInfoListRequest(val *DexInfoListRequest) *NullableDexInfoListRequest {
	return &NullableDexInfoListRequest{value: val, isSet: true}
}

func (v NullableDexInfoListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDexInfoListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


